### ISSUE TITLE
After restart BackgroundGeolocation, app_name appears in the center of the phone screen for a while and then disappears soon.

### ISSUE THREAD

**Issue by barunsoft0819** [transistorsoft/background-geolocation-lt#100]
## Your Environment
* Plugin version: 1.4.0
* Platform: Android
* OS version: Window
* Device manufacturer / model:
* Plugin config

## Steps to Reproduce

**Sorry, There is a mistake. It happens when I restart BackgroundGeolocation**

https://drive.google.com/file/d/1zFIqJDLmDzbbTtjVz7g0fFW1cyefpyhP/view?usp=sharing

**Comment by christocracy** [comment]
Show me a screen recording of this?

**Comment by barunsoft0819** [comment]
https://drive.google.com/file/d/1zFIqJDLmDzbbTtjVz7g0fFW1cyefpyhP/view?usp=sharing

**Comment by christocracy** [comment]
I have never seen this before.  Show me your AndroidManifest.

The plugin *is* launching an invisible Activity.  Configure `config.setDisableLocationAuthorizationAlert(true)`

**Comment by barunsoft0819** [comment]
Ok, thanks
