### ISSUE TITLE
battery optimization?

### ISSUE THREAD

**Issue by barunsoft0819** [transistorsoft/background-geolocation-lt#101]
## Your Environment
* Plugin version: 1.4.0
* Platform: Android
* OS version:
* Device manufacturer / model: Galaxy (SM-G610L)
* Plugin config
geoConfig.updateWithBuilder()
                .setDebug(false)
                .setLogLevel(0)
                .setDisableLocationAuthorizationAlert(true)
                .setTriggerActivities("in_vehicle, on_bicycle, running, walking")
                .setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
                .setStopOnTerminate(false)
                .setForegroundService(true)
                .setStartOnBoot(true)
                .setStopTimeout(3L)
                .setActivityRecognitionInterval ( 20 * 1000 )
                .setMinimumActivityRecognitionConfidence ( 85 )
                .setMotionTriggerDelay ( 60 * 1000 )
                .setDistanceFilter(50f)
                .setDisableStopDetection ( true )
                .setElasticityMultiplier(2f)
                .setHttpTimeout(10 * 1000)
                .setAutoSync(false)
                .setBatchSync(true)
                .setUrl(ApiConfig.LOCATIONS_URL)

## Expected Behavior

If inside a building, the coordinates sometimes collect very long distances.
Can I filter this value?

Can you tell me the settings for battery optimization?
(Are there any related sample sources with the same conditions?)

## Actual Behavior

1. If inside a building, the coordinates sometimes collect very long distances.
2. Sometimes I use more than 10% of my battery per day.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by barunsoft0819** [comment]
If you are inside a building, the coordinates intermittently collect very long distances.
Can you filter this value?

**Comment by christocracy** [comment]
Please do not ignore the issue template.  It's impossible to comment without knowing how you configure the plugin.  The issue template asked for that information (you deleted all that).



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
