### ISSUE TITLE
Plugin Detects Driving late 

### ISSUE THREAD

**Issue by attriaman2520** [transistorsoft/background-geolocation-lt#102]
## Your Environment
* Plugin version: 
* Platform: iOS or Android : iOS 
* OS version: 10.15.2
* Device manufacturer / model: iPhone 11
* Plugin config

## Expected Behavior
We are using this plugin to draw trip taken by user using driving/running/walking/bicycle for particular day. For "In Vehicle"  tirp we want it to be started from exact location. It should not be off the starting and ending point. Could you let us know how we should proceed?

## Actual Behavior
But driving trip is only detected when use has moved considerable distance So route drawn of trip is always sometime off the starting and ending point.

## Steps to Reproduce

1. Our Distance Filter is set to 10 meters
2.
3.
4.

## Context
We are using this plugin to draw trip taken by user using driving/running/walking/bicycle for particular day.

**Comment by christocracy** [comment]
You may offer a UI button to the user, eg `[Start Trip]`, which executed `BackgroundGeolocation.changePace(true)` (after calling `.start()`.  This will manually toggle the plugin into the *moving* state. 

There is **no possible way** for iOS to *automatically* initiate tracking without a delay of T least 200 meters.  We're fortunate iOS even allows *this*.

**Comment by sunilw123** [comment]
Is this true even if we are using Prevent Suspend? Sometimes it shows the tracking starting point accurately and sometimes it shows after going some distance...so instead of showing the starting point from home it shows it from the middle of the street.
