### ISSUE TITLE
Plugin detects driving late

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/background-geolocation-lt#103]
Chris, you commented on this issue 5 days ago.  Can you tell me if your answer of having to go 200 meters is true even if we are using Prevent Suspend?  Sometimes it shows the tracking starting point accurately and sometimes it shows after going some distance...so instead of showing the starting point from home, it shows it from the middle of the street.  We want to be consistent the way life360 is somehow able to always show the starting and ending point of a drive.

##Your Environment
Plugin version:
Platform: iOS or Android : iOS
OS version: 10.15.2
Device manufacturer / model: iPhone 11
Plugin config
Expected Behavior
We are using this plugin to draw trip taken by user using driving/running/walking/bicycle for particular day. For "In Vehicle" tirp we want it to be started from exact location. It should not be off the starting and ending point. Could you let us know how we should proceed?

Actual Behavior
But driving trip is only detected when use has moved considerable distance So route drawn of trip is always sometime off the starting and ending point.

Steps to Reproduce
Our Distance Filter is set to 10 meters
Context
We are using this plugin to draw trip taken by user using driving/running/walking/bicycle for particular day.

Debug logs
@christocracy
 
Member
christocracy commented 5 days ago
You may offer a UI button to the user, eg [Start Trip], which executed BackgroundGeolocation.changePace(true) (after calling .start(). This will manually toggle the plugin into the moving state.

There is no possible way for iOS to automatically initiate tracking without a delay of T least 200 meters. We're fortunate iOS even allows this.

**Comment by christocracy** [comment]
`preventSuspend` is a *brittle hack* that no longer works well with latest iOS.

If your app is terminated (by user or the OS), `preventSuspend` has no effect since that app is now terminated.

You  **cannot** rely on `preventSuspend: true`.
