### ISSUE TITLE
"Permission required" notification configuration settings

### ISSUE THREAD

**Issue by mobiRic** [transistorsoft/background-geolocation-lt#104]
## Your Environment
* Plugin version: 3.1.7 (363)
* Platform: Android
* OS version: API 29
* Device manufacturer / model:
* Plugin config

    ╔═════════════════════════════════════════════
    ║ TSLocationManager version: 3.1.7 (363)
    ╠═════════════════════════════════════════════
    ╟─ Google Pixel @ 10 (native)
    {
      "activityRecognitionInterval": 10000,
      "allowIdenticalLocations": false,
      "authorization": {},
      "autoSync": true,
      "autoSyncThreshold": 0,
      "batchSync": true,
      "configUrl": "",
      "debug": true,
      "deferTime": 0,
      "desiredAccuracy": 100,
      "desiredOdometerAccuracy": 100,
      "disableAutoSyncOnCellular": false,
      "disableElasticity": false,
      "disableLocationAuthorizationAlert": false,
      "disableMotionActivityUpdates": false,
      "disableStopDetection": false,
      "distanceFilter": 10,
      "elasticityMultiplier": 1,
      "enableHeadless": false,
      "enableTimestampMeta": false,
      "encrypt": false,
      "extras": {},
      "fastestLocationUpdateInterval": 5000,
      "forceReloadOnBoot": false,
      "forceReloadOnGeofence": false,
      "forceReloadOnHeartbeat": false,
      "forceReloadOnLocationChange": false,
      "forceReloadOnMotionChange": false,
      "forceReloadOnSchedule": false,
      "foregroundService": true,
      "geofenceInitialTriggerEntry": true,
      "geofenceModeHighAccuracy": false,
      "geofenceProximityRadius": 1000,
      "geofenceTemplate": "",
      "headers": {},
      "headlessJobService": "",
      "heartbeatInterval": -1,
      "httpRootProperty": "location",
      "httpTimeout": 60000,
      "isMoving": true,
      "locationAuthorizationRequest": "Always",
      "locationTemplate": "",
      "locationTimeout": 60,
      "locationUpdateInterval": 5000,
      "locationsOrderDirection": "ASC",
      "logLevel": 5,
      "logMaxDays": 3,
      "maxBatchSize": 100,
      "maxDaysToPersist": 1,
      "maxRecordsToPersist": -1,
      "method": "POST",
      "minimumActivityRecognitionConfidence": 75,
      "motionTriggerDelay": 0,
      "notification": {
        "layout": "",
        "title": "Background Tracking is active",
        "text": "Tap to return to the app",
        "color": "#e1251b",
        "channelName": "TSLocationManager",
        "smallIcon": "drawable\/rapid_icon_white_small",
        "largeIcon": "",
        "priority": 0,
        "strings": {},
        "actions": []
      },
      "params": {
        "device": {
          "uuid": "7670d179aa311175",
          "model": "Pixel",
          "platform": "Android",
          "manufacturer": "Google",
          "os_version": "10",
          "version": "2.3.0 (debug) Parse",
          "userId": 3480,
          "build": 45,
          "framework": "Native",
          "domain": "rapiddeployqa.com",
          "connectionType": "wifi"
        },
        "Type": "RecordTelemetry"
      },
      "persist": true,
      "persistMode": 2,
      "schedule": [],
      "scheduleUseAlarmManager": false,
      "speedJumpFilter": 300,
      "startOnBoot": true,
      "stationaryRadius": 25,
      "stopAfterElapsedMinutes": 0,
      "stopOnStationary": false,
      "stopOnTerminate": false,
      "stopTimeout": 5,
      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
      "url": "",
      "useSignificantChangesOnly": false,
      "enabled": true,
      "schedulerEnabled": false,
      "trackingMode": 1,
      "odometer": 0,
      "isFirstBoot": false,
      "didLaunchInBackground": false
    }

## Expected Behavior
When the location "Allow all the time" permission is cancelled, with the app actively tracking, the "Permission required" notification should use a color and icon configurable by the app, or should use the config for the foreground tracking notification.

## Actual Behavior
Notification displays without color on the default Android icon.

## Steps to Reproduce
1. Run the app
2. Start tracking
3. Background app and go to app's permission settings
4. Disable Location permission

## Context
Configure the "Permission required" notification

## Debug logs
can't find anything in the logs

**Comment by mobiRic** [comment]
In case the template info above is not clear, we are just hoping to find out:
1. is that notification customizable?
2. how to do it?

**Comment by christocracy** [comment]
I believe the permission notification comes automatically [from the library](https://github.com/transistorsoft/background-geolocation-lt/blob/master/android/background-geolocation/build.gradle#L55) that background-geolocation uses for requesting permissions [android-permissions](https://github.com/nishkarsh/android-permissions).

I'm not aware of any way to customize that notification.

**Comment by mobiRic** [comment]
Thanks, will investigate further on that side of things. Perhaps we can preempt that notification somehow.

**Comment by mobiRic** [comment]
Resolved by duplicating relevant `NotificationService` code from that library into our project, and changing the icon in there.
