### ISSUE TITLE
In Android, when minifyEnabled=true and proguard setting is set in gradle files an error occured.

### ISSUE THREAD

**Issue by navdeepsingh007** [transistorsoft/background-geolocation-lt#105]
## Your Environment
* Plugin version: 3.1.7
* Platform: Android

## Expected Behavior
Build should run without any Gradle error 

## Actual Behavior
Gradle error occured  while minifyEnabled is set true and proguard line is added for Plugin setup.

## Steps to Reproduce
minifyEnabled true
proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro" 
1.  Set minifyEnabled to true.
2.  Add proguard line for plugin setup.

## Context
I created a dummy project for transistorsoft plugin setup as my production project was throwing same error when minifyEnabled is set to true and proguard line for plugin setup is set. 

Downloaded the release (1.4.0) : https://github.com/transistorsoft/background-geolocation-lt/releases

Referred this link for Plugin setup :  https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/INSTALL-ANDROID.md 

## Debug logs
Here is the error that occurs when I am trying to create a build:

Build file 'E:\AndroidProjects\SAMPLES\DemoTransistorSoftSetup\app\build.gradle' line: 24

A problem occurred evaluating project ':app'.
> Could not get unknown property 'background_geolocation' for BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=true, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[E:\AndroidProjects\SAMPLES\DemoTransistorSoftSetup\app\build\intermediates\proguard-files\proguard-android-optimize.txt-4.1.2, E:\AndroidProjects\SAMPLES\DemoTransistorSoftSetup\app\proguard-rules.pro], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.

The line 24 points to below line in gradle file:
proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"

Added the screenshot of the same.
![Transistorsoft_Plugin_error](https://user-images.githubusercontent.com/5499158/107739399-c8d11180-6d2e-11eb-8621-29db66fc19e8.png)

**Comment by navdeepsingh007** [comment]
Also, I tried to change the proguard line from:

proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"

to

proguardFiles "${background-geolocation.projectDir}/proguard-rules.pro"

but it also didn't worked.

**Comment by christocracy** [comment]
Did you do [*this part*](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/INSTALL-ANDROID.md#open_file_folder-appbuildgradle)?

**Comment by navdeepsingh007** [comment]
Yes, I am done with this part. Please go through the **context** of my question.

**Comment by navdeepsingh007** [comment]
@christocracy The old plugin version 2.12.12 we had used in our App is not pushing location updates for Android 10 and Android 11. We thought that upgrading the plugin version might resolve the issue but getting this error.

**Comment by navdeepsingh007** [comment]
Hi @christocracy, plugin version 3.1.7 with minifyEnabled set to false in build.gradle file is not working.

**Comment by christocracy** [comment]
Post your *entire* `android/app/build.gradle`

**Comment by navdeepsingh007** [comment]
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.example.demotransistorsoftsetup"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

// Get a reference to background-geolocation project.
Project background_geolocation = project(':background-geolocation')

// Apply background-geolocation's custom app.gradle file
apply from: "${background_geolocation.projectDir}/app.gradle"

dependencies {
    implementation background_geolocation
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

**Comment by navdeepsingh007** [comment]
Below is the **_android/background-geolocation.proguard-rules.pro_** which is showing errors. Please go through the attached screenshot.

# BackgroundGeolocation lib tslocationmanager.aar is *already* proguarded
-keep class com.transistorsoft.** { *; }
-dontwarn com.transistorsoft.**

# BackgroundGeolocation (EventBus)
-keepclassmembers class * extends de.greenrobot.event.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

# logback
-keep class ch.qos.** { *; }
-keep class org.slf4j.** { *; }
-dontwarn ch.qos.logback.core.net.*

# OkHttp3
-dontwarn okio.**
-dontwarn okhttp3.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

![image](https://user-images.githubusercontent.com/5499158/108950056-9529ac00-768b-11eb-8e67-2098ee487941.png)
