### ISSUE TITLE
iOS 14 Battery Drain

### ISSUE THREAD

**Issue by mxnmike** [transistorsoft/background-geolocation-lt#106]
We have noticed that since we updated to iOS 14 the battery usage has increased a lot, before on iOS 13 we use to have a 3-10% based on the usage/movement of the user, with iOS 14, the usage has increased up to 40% 

## Your Environment
* Plugin version: 1.4
* Platform: iOS
* OS version: 14.4, but any iOS 14 is doing the same thing
* Device manufacturer / model: Apple
* Plugin config

        TSConfig.sharedInstance()?.update({ (arg) in
            guard let tsConfigBuilder = arg else { return }
            #if DEBUG_VERSION
            tsConfigBuilder.debug = true
            tsConfigBuilder.logLevel = tsLogLevelOff
            #elseif ADHOCINTERNAL_VERSION
            tsConfigBuilder.debug = true
            tsConfigBuilder.logLevel = tsLogLevelDebug
            #elseif ADHOC_VERSION
            tsConfigBuilder.debug = false
            tsConfigBuilder.logLevel = tsLogLevelOff
            #elseif PRODUCTION_VERSION
            tsConfigBuilder.debug = false
            tsConfigBuilder.logLevel = tsLogLevelOff
            #endif
            
            #if !PRODUCTION_VERSION
            tsConfigBuilder.params = ["device" : UIDevice.getAdvantaDeviceInfo()]
            tsConfigBuilder.url = "http://qa.tracker.advantahealth.com/locations/" + (UserDefaults.standard.string(forKey: "MemberID") ?? "mxmike")
            #endif
            
            tsConfigBuilder.desiredAccuracy = kCLLocationAccuracyBest
            tsConfigBuilder.locationAuthorizationRequest = "Always"
            tsConfigBuilder.distanceFilter = 10
            tsConfigBuilder.stationaryRadius = 25
            tsConfigBuilder.desiredOdometerAccuracy = CLLocationAccuracy(exactly: 100)!
            tsConfigBuilder.geofenceProximityRadius = CLLocationDistance(exactly: 1000)!
            tsConfigBuilder.startOnBoot = true
            tsConfigBuilder.geofenceInitialTriggerEntry = true
            tsConfigBuilder.activityType = .fitness
            tsConfigBuilder.stopOnTerminate = false
            tsConfigBuilder.preventSuspend = true
            tsConfigBuilder.heartbeatInterval = 60
        })

## Expected Behavior
Battery usage should be kept under 10%

## Actual Behavior
Battery usage has increased up to 40%

## Steps to Reproduce
Open the app, give while in use permissions 
When Prompted switch to always use location or directly change it in settings

## Context
Keep track of my geofences.

## Debug logs
No logs

**Comment by christocracy** [comment]
Neither I nor any of the hundreds of other users have reported anything about increased battery drain with iOS 14.

TikTok consumes more energy than my 3 demo apps for Cordova, RN and Flutter.

![image](https://user-images.githubusercontent.com/14999/110400702-1c8cfd00-8046-11eb-83d8-b27fe6c8a9f7.jpeg)

**Comment by christocracy** [comment]
(Last 10 days)
