### ISSUE TITLE
How can I avoid trips in malls, can we do this in this plugin

### ISSUE THREAD

**Issue by GurpalRajput** [transistorsoft/background-geolocation-lt#107]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version: Ios 14
* Device manufacturer / model: I phone 7 plus
* Plugin config

## Expected Behavior

I just want to avoid trips, when I am in malls, is there anything which can help me on this, desiredOdometerAccuracy is what I had tried to change but it won't works I had set its value to 10.

## Actual Behavior

By use of this desiredOdometerAccuracy in config malls trip should be restricted.

## Steps to Reproduce

1. make a trip to any mall and see, it will create trips inside that too
2.
3.
4.

## Context

I want to track a user but not for malls and under the buidings

**Comment by christocracy** [comment]
No there's no way for the plugin to determine it's "in a mall".  You'll have to implement your own custom filtering to exclude undesired location from your database.
