### ISSUE TITLE
Sometimes background-geolocation file is empty

### ISSUE THREAD

**Issue by GurpalRajput** [transistorsoft/background-geolocation-lt#108]
## Your Environment
* Plugin version:
* Platform: iOS or Android IOS
* OS version: 14.4
* Device manufacturer / model:
* Plugin config
     builder.debug = DEBUG_LOCATION;   // Enable debug mode for having notifications while moving in location!!!!
            builder.logLevel = tsLogLevelOff;
            builder.desiredAccuracy = kCLLocationAccuracyBest;
            builder.distanceFilter = 20; // filter for mooving across area. Currently changed to 3 meters
            builder.stopOnTerminate = NO;
            builder.startOnBoot = YES;
            builder.elasticityMultiplier = 2;
           // builder.stationaryRadius = 1;
           //  builder.stopOnStationary = NO;
           // builder.disableElasticity = YES;
            builder.autoSync = YES;
            builder.url = urlString;
            builder.method = @"PUT";
            builder.desiredOdometerAccuracy = 10.0;
           // builder.heartbeatInterval = 900;
           // builder.stopTimeout = 15;
            builder.headers = @{@"Content-Type": @"application/json; charset=utf-8",
                    @"Authorization": server.token
            };

## Expected Behavior

it should share logs file filled with log 

## Actual Behavior

log file is empty

## Steps to Reproduce

1. tapping on log share function
2. then pop up ask us to email the log and then it shows empty
3.
4.

## Context

I just want to grab logs for debugging

**Comment by christocracy** [comment]
>builder.logLevel = tsLogLevelOff;

You can expect **no logs** wit that setting.
