### ISSUE TITLE
How to send address from the desired location?

### ISSUE THREAD

**Issue by multiplezonesservices** [transistorsoft/background-geolocation-lt#109]
## Your Environment
* Plugin version: 3.2.2
* Platform: Android: 
* OS version: All
* Device manufacturer / model: All
* Plugin config
config.updateWithBuilder()
.setDebug(false) // Sound Fx / notifications during development
.setLogLevel(5) // Verbose logging during development
.setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
.setDistanceFilter(distanceFilter)
.setLocationUpdateInterval(60000l)
.setStopTimeout(1L)
.setStationaryRadius(20)
.setExtras(extras)
.setActivityRecognitionInterval(10000l)
.setAllowIdenticalLocations(false)
.setHeartbeatInterval(60)
.setStopOnTerminate(false)
.setForegroundService(true)
.setStartOnBoot(true)
.setDesiredOdometerAccuracy(100f)
.setHeadlessJobService("net.mzi.trackengine.HeadlessJobService")
.setEnableHeadless(true)
.setUrl(baseUrl + "PostCoordinatesPlus/")
.setHeader("Content-Type", "application/json")
.commit();

## Expected Behavior
Want to send location address in json whenever new latitude and longitude capturing. 

## Actual Behavior
Not able to send actual address, because getting address is time taking process, and after app is killing from recent apps, I am not able to get address from my method, where this plugin is sending location without any issue, Please suggest a way to send address respect to all the locations without any issue, thanks.

## Steps to Reproduce
No steps as It's just a request query to solve my issue.

## Context
I just want to send address string respect of all the locations.

**Comment by christocracy** [comment]
What you're talking about is called "reverse geocoding".  Background Geolocation SDK has nothing to do with this.

You generally have to pay for reverse geocoding services and this is a task best performed at the server, not on the mobile client, since it performs an extra http request (and http requests consume *a lot* of battery.
