### ISSUE TITLE
Fetch values from the frame work

### ISSUE THREAD

**Issue by SowmiyaMadesh** [transistorsoft/background-geolocation-lt#11]
Version iOS : 11.1.6
iOS Native App.

I have integrated TSLocationManager,TSBackgroundFetch Frameworks
i can see the logs and notification in the debug mode

Where i can fetch the result values like DWELL TIME , ENTRY and EXIT and pass it through URL on Forground/Background.

Is there ay Kindof docs for this. Can you please help me out of this
Thanks in advance.

**Comment by christocracy** [comment]
I'm working on docs *right now*.

If you've configured the plugin with an `#url`, the plugin's HTTP service will *automatically* post a geofence event to your server.

```obj-c
TSLocationManager *bgGeo = [TSLocationManager sharedInstance];
void(^callback)(TSGeofencesChangeEvent*) = ^void(TSGeofencesChangeEvent* event) {
  NSLog(@"*** Geofence event: %@", [event toDictionary]);
};

[bgGeo onGeofencesChange:callback]; 
```

**Comment by SowmiyaMadesh** [comment]
Sorry to bother you again will this function onGeofence will trigger once the region ENTER,EXIT when the app was terminated by enabling PreventSuspend and by disabling stopOnTerminate options by Configuring.

And once the event triggers we get the Values from toDictionary the DWELL Time was not there is there any separate function for getting the DWELL values or Do I need to calculate the time Range from TimeStamp?

I have configured iOS Native in Swift Language And  in Android

**Comment by christocracy** [comment]
>when the app was terminated by enabling PreventSuspend

`preventSuspend` has nothing to do with this.

If you want geofences to operate when app is terminated, simply configure `stopOnTerminate: NO`

>DWELL Time was not there is there any separate function for getting the DWELL 

The `DWELL` transition is controlled by the `loiteringDelay` you configured on the geofence itself.  There's no such thing as "calculating the dwell time".

**Comment by SowmiyaMadesh** [comment]
Hi, 
Thanks for the help. It works now.
