### ISSUE TITLE
sync location with my server every few mins.

### ISSUE THREAD

**Issue by lovemobile1234** [transistorsoft/background-geolocation-lt#111]
bgGeo.configure({
  url: 'http://my_url',
  params: {
    myParams: {foo: 'bar'}
  }
});

I want to update my server every 1 minute.
how can I handle this?

**Comment by christocracy** [comment]
This is not the *Cordova Background Geolocation* repo.   This is the **Pure Native** version.

https://github.com/transistorsoft/cordova-background-geolocation-lt
