### ISSUE TITLE
CLLocation 'floor' support

### ISSUE THREAD

**Issue by zac** [transistorsoft/background-geolocation-lt#112]
## Your Environment
* Plugin version: 1.4.0
* Platform: iOS
* OS version: 14.7.1
* Device manufacturer / model: Apple / iPhone 12 Pro

## Feature Request
It would be very helpful to be able to get the 'floor' property ([documentation here](https://developer.apple.com/documentation/corelocation/cllocation/1616762-floor#)) and ensure it's uploaded to the server. One possible implementation: if it were made available via a 'floor_level' property in the template, that could allow access to this property.

## Context
In some cases, it can be helpful to have the floor property on the CLLocation to determine if we're inside a building that belongs to the [Apple Indoor Maps Program](https://register.apple.com/indoor). If we have a 'floor' integer, then we know we're inside one of those buildings. If we don't have a floor integer (it's nil), then we know we aren't.

**Comment by christocracy** [comment]
Floor is already implemented.

**Comment by zac** [comment]
> Floor is already implemented.

@christocracy Great! Thanks for the quick reply. I'm not seeing anything in the [documentation](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-iOS.md#config-nsstring-locationtemplate-undefined) (I would have expected it under the "Template Tags" section), but if I just reference 'floor' in the template, that will work?
