### ISSUE TITLE
Background locations stopped working after few days on iOS 14

### ISSUE THREAD

**Issue by amanattri09** [transistorsoft/background-geolocation-lt#115]
Plugin stop updating locations to server when app is put in background for couple of days. We were not using "prevent suspend".

## Your Environment
* Platform: iOS
* OS version  : 14.4
* Device manufacturer / model: Apple
* Plugin config
builder.desiredAccuracy = kCLLocationAccuracyBest;
    builder.stopOnTerminate = NO;
    builder.startOnBoot = YES;
    builder.autoSync = YES;
    builder.batchSync = YES;
    builder.maxBatchSize = 5;
    builder.elasticityMultiplier = 2;

## Expected Behavior
Plugin should keep working in background always even after killing app  

## Actual Behavior
Plugin stopped working after few days of app in background 

## Steps to Reproduce
Keep app in background for few days

**Comment by sunilw123** [comment]
@christocracy Can you please answer this question??

**Comment by barunsoft0819** [comment]
@christocracy Can you please answer this question??

**Comment by christocracy** [comment]
I experience no issue with sample app that I keep running uninterrupted for months at a time.  I’m using latest iOS 15.2.1.
