### ISSUE TITLE
Uncaught Exception: Invalid latitude: -114.05992704473897

### ISSUE THREAD

**Issue by tegaologe** [transistorsoft/background-geolocation-lt#118]
Version 4.7.2
Android version 9
Samsung

Config
`bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 100.0,
            stopOnTerminate: true,
            startOnBoot: true,
            enableHeadless: true,
            debug: true,
            heartbeatInterval: 60,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
`

Everytime  geolocation background it will crash with this error
E/TSLocationManager(11749): [c.t.l.a.BackgroundGeolocation$w0 uncaughtException]
E/TSLocationManager(11749):   ‼️  Uncaught Exception: Invalid latitude: -114.05992704473897

only on android

**Comment by christocracy** [comment]
This is not the flutter_background_geolocation repo.
