### ISSUE TITLE
NullPointerException on call BackgroundGeolocation.getInstance()

### ISSUE THREAD

**Issue by PothpothBR** [transistorsoft/background-geolocation-lt#121]
## Description
Hello, I'm having a problem with the `BackgroundGeolocation` component, it generates a nullpointer when calling `BackgroundGeolocation.getInstance()`.

## Your Environment
package: tslocationmanager.aar 3.0.26
ram: 4,0 GB
model: moto e32 Android 11

## Expected Behavior
It was expected the `BackgroundGeolocation` component to return a new instance of it using app context;

## Actual Behavior
There seems to be a check within the logic that is getting an andrioid task that does not have `RunningTaskInfo.baseActivity' or `RunningTaskInfo.baseActivity.getPackageName()`. The only way to fix this was to mute the method call and thus mute the whole api.
This problem only occurs on some specific devices like some Motorola MotoG32 android 11, Motorola MotoG52 android 12.
The first time the app is started, this problem does not happen, on subsequent attempts the error always occurs, apparently if the background task is not running it is not a problem, but recreating it or recovering it.

## Steps to Reproduce
1. Call `BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(getApplicationContext(), getIntent());`.
2. Run app once.
3. Close app.
3. Force stop (sometimes it is necessary to reproduce).
4. Rerun the app.

## Context
The component is started in the `onStart` method of the application base class, and is used during the entire time that the device is on, whether the user is using the application or not.

## Code to error
in `onStart`:
```java
public class MainDrawerActivity extends BaseActivity {

    @Override
    public void onStart() {
        super.onStart();
        // ...initialize the activity...

        FacadeBackgroundGeolocation.startBackgroundGeolocation(MainDrawerActivity.this);
    }
```

in `FacadeBackgroundGeolocation`:
```java
public static void startBackgroundGeolocation (Context context) {
        boolean debug = App.DEBUG;

        // Consult
        loadConfiguration();

        // Get a reference to the SDK
        final BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(context); // raise here
```

## Debug logs
```traceback
java.lang.NullPointerException: Attempt to invoke virtual method
java.lang.String android.content.ComponentName.getPackageName()' on a null object reference at
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.isMainActivityActive(Unknown Source:70) at
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.e(Unknown Source:45)
at
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>( Unknown Source:286)
at
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
at
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getinstance(Unknown Source:15)
at
com.app.utils.FacadeBackgroundGeolocation.startBackgroundGeolocation(FacadeBackgroundGeolocation.java:51)
at com.app.MainDrawerActivity.onStart( MainDrawer Activity.java:109)

```

**Comment by christocracy** [comment]
I no update this repo for pure native apps.

I support only cross-platform frameworks Cordova, Capacitor, React Native and Flutter.
