### ISSUE TITLE
Gradle is severely out of date.

### ISSUE THREAD

**Issue by jay81979** [transistorsoft/background-geolocation-lt#122]
Hi. Can I get a working version of this library?

**Comment by christocracy** [comment]
This library is no longer updated for use in native apps.

I support only cross-platform frameworks Cordova, Capacitor, React Native and Flutter.

**Comment by rlemasquerier** [comment]
Hello @christocracy !

Just out of curiosity, why is the native lib not maintained ? I assume most of the native side of the work is done and maintained, as you are keeping the cross platform SDKs up to date.

I am currently evaluating different options to develop an activity tracker, and as we are planning to develop a module for both Flutter and WatchOS, I'm curious to hear about the reasons behind this choice (if that something you agree to share of course ! :) )

**Comment by jay81979** [comment]
@rlemasquerier I wouldn't bother. The reason he is supporting cross platform and dropped native is because he is lazy. Native is harder to maintain. Cross platform is astoundingly out of date.
