### ISSUE TITLE
Android: Display tost message like "License valicdation faliure..." 

### ISSUE THREAD

**Issue by hirenkumar** [transistorsoft/background-geolocation-lt#14]
It’s display message like “license validation Failure backgroundGeolocation is running in evaluation mode” when I come back after restart phone , I have also set my license key and name in meta data 

## Your Environment
* OS version: 7.0 Nougat
* Device manufacturer / model: Moto G4
* Plugin config

"isMoving": false,
"enabled": true,
"odometer": 0,
 "schedulerEnabled": false,
 "trackingMode": "location",
"distanceFilter": 5, "desiredAccuracy": 0,
"desiredOdometerAccuracy": 100,
"locationUpdateInterval": 5,
 "fastestLocationUpdateInterval": 5,
 "locationTimeout": 60,
 "deferTime": 0,
 "disableElasticity": false,
 "elasticityMultiplier": 1,
 "allowIdenticalLocations": false,
 "activityRecognitionInterval": 10000,
 "minimumActivityRecognitionConfidence": 75,
 "triggerActivities": "in_vehicle,on_bicycle,on_foot,running,walking",
 "disableStopDetection": false,
 "stationaryRadius": 25,
 "stopTimeout": 5,
 "stopOnStationary": false,
 "url": "",
 "method": "POST",
 "autoSync": true,
 "autoSyncThreshold": 0,
 "batchSync": false,
 "maxBatchSize": -1,
 "params": {},
 "headers": {},
 "extras": {},
 "httpRootProperty": "location",
 "locationTemplate": "",
 "geofenceTemplate": "",
 "persist": true,
 "maxDaysToPersist": 1,
 "maxRecordsToPersist": -1,
 "locationsOrderDirection": "ASC",
 "httpTimeout": 60000,
 "geofenceProximityRadius": 1000,
 "geofenceInitialTriggerEntry": true,
 "stopOnTerminate": true,
 "startOnBoot": false,
 "heartbeatInterval": 900,
 "foregroundService": true,
 "notificationPriority": 0,
 "notificationTitle": "",
 "notificationText": "Location Service activated",
 "notificationColor": "",
 "notificationIcon": "",
 "notificationSmallIcon": "mipmap\/logo",
 "notificationLargeIcon": "",
 "forceReloadOnLocationChange": false,
 "forceReloadOnMotionChange": false,
 "forceReloadOnGeofence": false,
 "forceReloadOnBoot": false,
 "forceReloadOnHeartbeat": false,
 "forceReloadOnSchedule": false,
 "stopAfterElapsedMinutes": 0,
 "schedule": [],
 "configureUrl": "",
"configureInterval": -1,
 "debug": false,
"logLevel": 5,
 "logMaxDays": 3

**Comment by christocracy** [comment]
Show me your AndroidManifest, with license key redacted
