### ISSUE TITLE
API is called even there is no Geofence Event

### ISSUE THREAD

**Issue by SowmiyaMadesh** [transistorsoft/background-geolocation-lt#15]
In the attached log you can see API is called even there is no Geofence Triggered. Let me know how to config to push data to server only if there is a Geofence (ENTRY, DWELL, EXIT)

* Platform:  Android Native

[](url)
[TS-Log-03-23-18.txt](https://github.com/transistorsoft/background-geolocation-lt/files/1847420/TS-Log-03-23-18.txt)

**Comment by christocracy** [comment]
If you only want to monitor geofences, you must start the plugin with the `#startGeofences` method.

- `#start` = Location + Geofence tracking
- `#startGeofences` = Geofences only.

**Comment by SowmiyaMadesh** [comment]
Changed to startGeofences method. now API is called only on Geofences. But Im not able to get Geofence for EXIT. 
TSGeofence.Builder builder = new TSGeofence.Builder();
        builder.setRadius(200);
        builder.setNotifyOnEntry(true);
        builder.setNotifyOnExit(true);
        builder.setNotifyOnDwell(true);
        builder.setLoiteringDelay(20000);
TSGeofence tsGeofence = new TSGeofence(builder);

        bgGeo.addGeofence(tsGeofence);
        bgGeo.onHttp(createHttpResponseCallback());
        bgGeo.onMotionChange(createMotionChangeCallback());
        bgGeo.onLocation(createLocationCallback());
        bgGeo.onGeofence(createGeofenceCallback());
        bgGeo.onConnectivityChange(createConnectivityChangeCallback());
        bgGeo.onLocationProviderChange(createProviderChangeCallback());

        bgGeo.startGeofences(new TSCallback() {
            @Override
            public void onSuccess() {
                Log.e("Only Geofence", "Monitor");
            }

            @Override
            public void onFailure(String s) {

            }
        });
