### ISSUE TITLE
IOS and Android Plugins Not Sending Any Location Updates After About A Week

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/background-geolocation-lt#16]
Hello Chris,

I am sending mail behalf of Sunil for location update issue on iOS and Android device.

iOS Device(version 11.2.6) has been sending location server almost 7 to 8 days after that iOS is getting stopped to sending location to server. Its started sending location to server while relaunching the app. Below is the iOS configuration. 
Plugin will 

NSDictionary *config = @{
                             @"desiredAccuracy": @(0),
                             @"distanceFilter": @(10),
                             @"debug": @(false),
                             @"desiredOdometerAccuracy":@(5),
                             @"stopOnTerminate":@(false),
                             @"heartbeatInterval":@(900),
                             @"stopTimeout":@(15),
                             @"logLevel": @(5),
                             @"url":urlString,
                             @"preventSuspend":@(true),
                             @"method":@"PUT",
                             @"headers":@{
                                     @"Content-Type":@"application/json; charset=utf-8",
                                     @"Authorization":server.token
                                     },
                             @"autoSync":@(true)
                             };

Android device (version 7.1.1) has been sending location to server almost 3 to 4 days in hard close state after that device is getting stopped to sending location to server. Below is the android configuration.
Config.Builder builder = new Config.Builder()
        .setDebug(true)
        .setLogLevel(5)
        .setSchedule(schedule)
        .setForegroundService(true)
        .setStartOnBoot(true)
        .setStopOnStationary(false)
        .setDesiredOdometerAccuracy(5.0)
        .setStopOnTerminate(false)
        .setLocationUpdateInterval((long)5000)
        .setIsMoving(true)
        .setDesiredAccuracy(0)
        .setAutoSync(true)
        .setUrl(requestUrl)
        .setHeaders(headers)
        .setDistanceFilter(10)
        .setMethod("PUT")
        .setHttpTimeout(30000)
        .setFastestLocationUpdateInterval((long)10000);

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Need plugin logs (attached as file).  

Easiest way to fetch logs is via:

`BackgroundGeolocation#emailLog`
 method.

**Comment by sunilw123** [comment]
[background-geolocation (2).log.gz](https://github.com/transistorsoft/background-geolocation-lt/files/1870239/background-geolocation.2.log.gz)
[background-geolocation (1).log.gz](https://github.com/transistorsoft/background-geolocation-lt/files/1870240/background-geolocation.1.log.gz)
Check out these files

**Comment by christocracy** [comment]
#### Logfile 1
- This log is < 30s long.  Nothing unusual here
#### Logfile 2
- This log spans `03-29` - `03-30`.  What particular time interval are you interested in with this log?
#### Logfile 3
- This file  *contains* the previous Logfile 2
- Again, what *specific* time interval are you interested in?
#### Logfile 4
- This file *contains* the previous Logfile 3.
- What *specific* time interval are you interested in?
#### Logfile 5
- Once again, this file contains the previous Logfile 4
- What specific time interval are you interested in?

There's no point sending t log from the *same* device fetched at *different* times.  Your Logfile 5 contains all the information of the previous 4 files.

What *specific* intervals are you interested in?  I see nothing unusual in these logs.

**Comment by satishkolawale** [comment]
We did not receive location from plugin between 30 Mar 7:46 PM PST to 31 Mar 11:54 AM PST.
Also we tried below cases between above timeline
1. We re-installed the app from device
2. We tried the logout and login again but did not receive any location from plugin.

**Comment by sunilw123** [comment]
Hey Chris, any direction on this?  From March 30th at 7:48pst to March 31st 11:54am we did not get any location updates from the plugin..please let us know why that could be happening?

**Comment by christocracy** [comment]
You say "March 30th at 7:48pst to March 31st".  Is the log file recording times in PST?  I have no idea.

I need to know specific times you're interested in of the *log file*.

**Comment by satishkolawale** [comment]
Hello Chris,

 Here i'm uploading four log files of four different users. For all of them when they put their app in foreground only then we got the location update but when the application is in hard closed or in background mode we are not able to get the location update for them. Their location setting is set to "Always" but still it is not working we are not getting location from plugin. 

[background-geolocation.log](https://github.com/transistorsoft/background-geolocation-lt/files/1892988/background-geolocation.log)
[background-geolocation(1).log](https://github.com/transistorsoft/background-geolocation-lt/files/1892990/background-geolocation.1.log)
[background-geolocation(2).log](https://github.com/transistorsoft/background-geolocation-lt/files/1892991/background-geolocation.2.log)
[background-geolocation(3).log](https://github.com/transistorsoft/background-geolocation-lt/files/1892992/background-geolocation.3.log)

Could you please let us know what is the actual problem. Why we are not able to get the location data for them?

**Comment by christocracy** [comment]
> but when the application is in hard closed or in background mode we are not able to get the location update for them

When the app is terminated by the user, the only thing that will  cause the OS to reboot your app is when the device moves *at least* 200 meters away from the last known location.

If the user terminates the app and stays in bed for 7 days, your app will not re-awaken *at all*.  The device *must* move.

**Comment by sunilw123** [comment]
Chris the issue we are finding is that the user is  moving. My sister went
from Chicago to Madison Wisconsin and we got no updates. When the phone was
in background or hard closed we got no updates. What are we doing wrong
that this could happen?  What we are finding is that we get one location
update for users who first download our app. Then if they close it then we
get no further updates. When I call them and go over al the settings and
they click around more in the app then all of a sudden it starts working
properly. And bear in mind that their settings were all correct. For some
reason then opening it up again and clicking around more got the app to
start sending the location data. But this has happened for almost every
user. What could we be doing wrong that this is happening? We have the logs
for those users that we uploaded for you.
Sunil

**Comment by sunilw123** [comment]
Chris, any answer on this?

**Comment by satishkolawale** [comment]
Hello Chris,
We did not receive location update on iOS version 10.3.2 between 2018-04-17 03:51:15 UTC to 2018-04-18 07:27:30 UTC. He has moved almost 10 miles from one place to another place.
Please have a look log file and let us know.
[background-geolocation.log.gz](https://github.com/transistorsoft/background-geolocation-lt/files/1924526/background-geolocation.log.gz)

**Comment by christocracy** [comment]
I need time references **corresponding to the log file**, which are not in UTC, they're recorded in the local time of the device.  Tell me the specific date-range to observe **in log file**.

**Comment by sunilw123** [comment]
Chris this person was in India so IST is 5 hours and 30 minutes ahead of UTC.  So the range is 4-17-18 at 9:21:15 through 4-18-18 12:57:30.  Let me know if you need anything else. thx

**Comment by sunilw123** [comment]
Chris any advice on why this is happening and how we can fix?

**Comment by christocracy** [comment]
Does it work correctly in the simulator?

**Comment by satishkolawale** [comment]
Also we did receive location on Karbonn Android one OS 6.0.1 from 18th April 2018 18:26:52 IST. It was stopped the sending location to server while travelling to other place. Everyday we traveled almost 15 miles form one place to other place but did not received any location. Please have a look device log of android device.
[background-geolocation.log.gz](https://github.com/transistorsoft/background-geolocation-lt/files/1930875/background-geolocation.log.gz)

**Comment by christocracy** [comment]
@satishkolawale  Your logs are full of HTTP errors.  Are you not checking for this?

```
04-19 09:53:37.401 WARN [HttpService$HttpCallback onResponse] 
  ⚠️  Response: 404, Not Found
.
.
.
04-19 18:38:28.730 WARN [HttpService$HttpCallback onFailure] 
  ⚠️  Response: 0, Unable to resolve host "serendipityawaits.com": No address associated with hostname
```

**Comment by satishkolawale** [comment]
@christocracy We are not checking HTTP errors from response.

**Comment by satishkolawale** [comment]
@christocracy 
We did a test on iOS simulators on freeway mode. We used below iOS simulators for testing
1. iPhone 7(11.2)     Background
2. iPhone 7(10.2)     HardClose
3. iPhone 8(11.2)     Foreground
4. iPhone X(11.2)     Background
5. iPhone SE(10.2)   HardClose

We received location updates till internet was On. We turned off the WiFi of the mac. Then we received notifications on simulators with background app. After 20 hours, we turned on Wifi and no location updates are receiving.
**Conclusion:** Freeway drive stopped working after the internet got disconnected and it did not restart after turning on the Internet.

**Comment by sunilw123** [comment]
Chris can we set up a call to go over this and get answers from you??

**Comment by christocracy** [comment]
@sunilw123 I have no answers for you.

>After 20 hours, we turned on Wifi and no location updates are receiving.

What do the logs show?

**Comment by satishkolawale** [comment]
@christocracy There is no log after stopping location updates in the background-geolocation file.

**Comment by satishkolawale** [comment]
Hello Chris,
I receive location updates from morning around 2 May 10:00 AM IST to end of the day(2 May 6:44 PM IST) on Android device . Then i hard closed the app and traveled almost 3.7 miles from office to Home. Also today morning i traveled 3.7 miles from Home to office but i did not receive any location update. I am using Android Moto E4 Plus OS version 7.1.1. Please have a look log file and let us know your thoughts on it.

[background-geolocation.log.gz](https://github.com/transistorsoft/background-geolocation-lt/files/1969648/background-geolocation.log.gz)

**Comment by christocracy** [comment]
Is *this* the `6:44 PM` you're talking about (ie: `18:44` in logs) ?
```
05-02 18:43:02.460 INFO [BootReceiver onReceive] 
╔═════════════════════════════════════════════
║ BootReceiver: com.serendipityawaits
╠═════════════════════════════════════════════
╟─ android.intent.action.MY_PACKAGE_REPLACED

05-02 18:43:02.476 INFO [Settings print] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Settings
╠═════════════════════════════════════════════
{
  "isMoving": false,
  "enabled": true,
  "odometer": 0,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 10,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 5,
  "locationUpdateInterval": 5000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "elasticityMultiplier": 1,
  "allowIdenticalLocations": false,
  "activityRecognitionInterval": 10000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 5,
  "stopOnStationary": false,
  "url": "http:\/\/serendipityawaits.com\/php\/public\/user-location\/1255",
  "method": "PUT",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "params": {},
  "headers": {
    "Content-Type": "application\/json",
    "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjU1IiwiaXNzIjoiaHR0cDpcL1wvc2VyZW5kaXBpdHlhd2FpdHMuY29tXC9waHBcL3B1YmxpY1wvdXNlcnNcL2xvZ2luIiwiaWF0IjoiMTUyNTIzOTAyMCIsImV4cCI6IjE1NTY3NzUwMjAiLCJuYmYiOiIxNTI1MjM5MDIwIiwianRpIjoiNGQwYzhhYzdjYjc2NjM1ZWVhYTRlMWY4NWFkNzQ0MmMifQ.W5WCRdWQHLaOsc9_bBq6t2i0IkK3BqFkcMblCQu93Z0"
  },
  "extras": {},
  "httpRootProperty": "location",
  "locationTemplate": "",
  "geofenceTemplate": "",
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 30000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": -1,
  "foregroundService": true,
  "notificationPriority": 0,
  "notificationTitle": "",
  "notificationText": "Location Service activated",
  "notificationColor": "",
  "notificationIcon": "",
  "notificationSmallIcon": "",
  "notificationLargeIcon": "",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [
    "1-7 00:00-6:00"
  ],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": true,
  "logLevel": 5,
  "logMaxDays": 3
}╚═════════════════════════════════════════════
05-02 18:43:02.533 INFO [BackgroundGeolocationService onStartCommand] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Service started
╠═════════════════════════════════════════════

05-02 18:43:02.551 INFO [BackgroundGeolocationService startForeground] 
  ✅  Started in foreground
05-02 18:43:02.570 INFO [BackgroundGeolocationService requestActivityUpdates] 
  🎾  Start activity updates: 10000
05-02 18:43:02.587 INFO [BackgroundGeolocationService setPace] 
  🔵  setPace: null → false
05-02 18:43:02.819 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
05-02 18:43:03.277 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-02 18:43:03.760 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location:1001
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 18.511224,73.923546 acc=27 et=+1d19h51m3s570ms], age: 93ms, time: 1525266783666

05-02 18:43:03.785 DEBUG [TSLocationManager calculateMedianAccuracy] 26.843
05-02 18:43:10.025 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-02 18:43:17.061 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location:1001
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 18.511239,73.923567 acc=26 et=+1d19h51m16s847ms], age: 117ms, time: 1525266796944

05-02 18:43:17.092 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false
05-02 18:43:17.127 DEBUG [TSLocationManager calculateMedianAccuracy] 26.596
05-02 18:43:17.160 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 4b7c62d6-bfda-4678-a71c-a4aeec8b37f9
05-02 18:43:17.206 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

05-02 18:43:17.239 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
05-02 18:43:17.250 INFO [HttpService createRequest] 
  🔵  HTTP PUT: 4b7c62d6-bfda-4678-a71c-a4aeec8b37f9
05-02 18:43:18.047 INFO [HttpService$HttpCallback onResponse] 
  🔵  Response: 200
05-02 18:43:18.074 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: 4b7c62d6-bfda-4678-a71c-a4aeec8b37f9
05-02 18:43:21.351 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-02 18:44:17.505 INFO [Sensors print] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="3-axis Accelerometer", vendor="Bosch", version=1, type=1, maxRange=39.24, resolution=0.009810001, power=0.25, minDelay=10000}
╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
╟─ ✅  MAGNETOMETER: {Sensor name="Compass", vendor="Vendor", version=1, type=2, maxRange=1228.8, resolution=0.15, power=0.35, minDelay=10000}
╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
╚═════════════════════════════════════════════
05-02 18:44:17.523 INFO [BackgroundGeolocation <init>] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 2.11.1
╠═════════════════════════════════════════════

05-02 18:44:17.534 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:11910000)
05-02 18:44:17.549 DEBUG [SQLiteLocationDAO dbh] 
  ✅  Opened database
05-02 18:44:17.558 DEBUG [SQLiteLocationDAO prune] 
  ℹ️  PRUNE -1 days
05-02 18:44:17.575 DEBUG [GeofenceDAO dbh] 
  ✅  Opened database
05-02 18:44:17.589 INFO [BackgroundGeolocation <init>] 
  🔵  Connecting to GooglePlayServices...
05-02 18:44:17.597 INFO [BackgroundGeolocationService onStartCommand] 
╔═════════════════════════════════════════════
║ BackgroundGeolocation Service started
╠═════════════════════════════════════════════

05-02 18:44:17.609 INFO [BackgroundGeolocationService startForeground] 
  ✅  Started in foreground
05-02 18:44:17.627 INFO [BackgroundGeolocationService requestActivityUpdates] 
  🎾  Start activity updates: 10000
05-02 18:44:17.656 INFO [BackgroundGeolocationService setPace] 
  🔵  setPace: null → false
05-02 18:44:17.958 INFO [LocationService onLocation] 
  ℹ️  Location availability: true
05-02 18:44:18.366 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
05-02 18:44:18.379 DEBUG [BackgroundGeolocation isMainActivityActive] NO
05-02 18:44:18.879 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location:1001
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 18.511236,73.923550 acc=26 et=+1d19h52m18s670ms], age: 112ms, time: 1525266858767

05-02 18:44:18.894 DEBUG [TSLocationManager calculateMedianAccuracy] 26.448
05-02 18:44:29.835 INFO [LocationService onLocation] 
  ℹ️  Location availability: false
05-02 18:44:32.680 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location:1001
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 18.511246,73.923558 acc=26 et=+1d19h52m31s923ms], age: 660ms, time: 1525266872019

05-02 18:44:32.711 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false
05-02 18:44:32.734 DEBUG [TSLocationManager calculateMedianAccuracy] 26.4195
05-02 18:44:32.761 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 62baaa27-f6be-460e-8110-548a46be7d79
05-02 18:44:32.762 INFO [LocationService onLocation] 
  ℹ️  Location availability: true

```

**Comment by christocracy** [comment]
I've [released a new version](https://github.com/transistorsoft/background-geolocation-lt) of the iOS and Android SDK.

This Setup and API are **significantly different** from the one you're using.  You should remove and completely install this from scratch.

- See the new [Setup Instructions](https://github.com/transistorsoft/background-geolocation-lt#large_blue_diamond-setup-guides)
- The API is **significantly changed**.  See the new [API Docs](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README.md)

**Comment by sunilw123** [comment]
Hi Chris. Will this new plugin fix the issue we are facing where tracking
stops?  Please advise. Thx.
Sunil

**Comment by christocracy** [comment]
I have no idea what your issue is and none of the hundreds of other customers are experiencing your issue, but it’s the version I use.  And there’s better docs now.

**Comment by satishkolawale** [comment]
@christocracy  Yes i am talking about 05-02 18:44:32.762. After that, i did not receive any location.

**Comment by sandipchaudhari** [comment]
Chris, the log uploaded by Satish in previous post (part of which has been pasted above) does seem to have direct information for investigation.

1.  If you look at the log, towards bottom of it, last entries for 05-02, it constantly and correctly shows location co-ordinates of Pentagon Towers in Magarpatta, Pune i.e. our office location.
2. Just before leaving office, around 05-02 20:* IST, Satish hard closed the app.
3. Then Satish went home (around 4+ km away). No location updates were received. There are no log entries. Satish did go home and he did carry the phone with him.
4. Next day morning Satish returned to office with the phone. Still no location updates in the log.
5. Finally, Satish started the app again, got the debug log message, shared the log here.
6. The log seems to show it's final few entries after Satish started the app.

Please let us know if you would need any more info and update us as soon as you can...

Appreciate it. Thanks.

**Comment by christocracy** [comment]
Have you implemented the new version yet?

**Comment by sandipchaudhari** [comment]
Chris, the new version will mean quite a few changes and re-testing of lot of features at our end. We do not want to do that right now in the current phase of our deliverable, maybe in the future...

**Comment by christocracy** [comment]
And you now have the benefit of documentation with the latest version that you did not have with the version you currently use.

**Comment by sandipchaudhari** [comment]
Chris:
1. Would those changes fix the issue?
2. Were you able to replicate the issue mentioned?
3. At our end it would not be few hours, lot more than that, as we will have to re-test all features that are related to location updates.

Should the version we have integrated not work? It works for all other cases....
It seems (based on logs), when plugin finds there is no motion, user is 100% still and user closes the app in background mode, it stops working?

**Comment by christocracy** [comment]
>1  Would those changes fix the issue?

As I [said above](https://github.com/transistorsoft/background-geolocation-lt/issues/16#issuecomment-386498034) to @sunilw123's same question, I have no idea.  Try it and see.

>2 Were you able to replicate the issue mentioned?

No.

>3 At our end it would not be few hours

Have you looked at the new docs?

**Comment by sandipchaudhari** [comment]
Yes I did. They look good. It might not take lot of time for integration.
But I think you are missing the point I am trying to raise here, in case we integrate new plugin...

- we will still have to test all features at our end, that are currently working with existing plugin except one. These tests take more than a week!

Has it been integrated by other clients?

**Comment by christocracy** [comment]
My Cordova and React Native customers have been using this version for 2 months.

The changes are mostly improved public API changes, specifically designed to assist native developers such as yourself.

Little of the internal functionality was touched.

I do not test with the version you're using.  You should update to the latest version ASAP so we're using the same version.
