### ISSUE TITLE
Geofence is triggered every time when the app is reopened

### ISSUE THREAD

**Issue by SowmiyaMadesh** [transistorsoft/background-geolocation-lt#17]
* Platform: Android Native
Geofence ENTYR, DWELL are logged correctly in my server. But when I exit the app and reopened it, the 
app restarts the Geofence montioring from ENTRY , DWELL even though I was in the same region entire time.
Let me know do I have to change any settings. Attached Log here
[TS-Log-04-02-18.txt](https://github.com/transistorsoft/background-geolocation-lt/files/1868120/TS-Log-04-02-18.txt)

Thanks.

**Comment by christocracy** [comment]
Are you calling `#addGeofence` when your app boots?

**Comment by SowmiyaMadesh** [comment]
I'm adding GeoFences in onCreate. 

[TS-Source-04-04-18.txt](https://github.com/transistorsoft/background-geolocation-lt/files/1875805/TS-Source-04-04-18.txt)

**Comment by christocracy** [comment]
Well that's your problem.  The plugin stores it geofences in its database.  If you **re-create** geofences when your app boots, the plugin may *already* have been monitoring that geofence you just **re-created**.

When you re-create a geofence that *already* exists, the plugin will destroy the existing record from its database, stop-monitoring existing geofence and begin monitoring the new instance (firing it immediately if already inside.
