### ISSUE TITLE
Passing URL with header authorization

### ISSUE THREAD

**Issue by Jeyavijay** [transistorsoft/background-geolocation-lt#18]
Hi Chris,

The app with geofence tracking is in good state but we have the the url and need to send the token value in the header.

While configuring the URL how to Pass header values to the server.
Can you please help me out 

Thanks in Advance.

**Comment by christocracy** [comment]
The SDK offers a `headers` config option.

**Comment by Jeyavijay** [comment]
Thanks for your support :)

**Comment by Jeyavijay** [comment]
Hi,
Instead of configuring the URL when the app starts. If i configured every time when OnGeofence event triggered means will the data passing to the server work like one time configuration.
The reason is every time on triggering the event have to send different values to the server.

You advised me earlier to configure the url once in the app instead of configuring again and again while triggering.

**Comment by christocracy** [comment]
By the time the `onGeofence` event fires, the HTTP request has already been sent.

Show me an example of these "different values" you wish to send with each geofence.

**Comment by Jeyavijay** [comment]
Hi,
In extras field have to send different values like location id,location name and address based on the geofence entries. Like this below


 "extras": {
                "qsDevice_name": "iPhone SE",
                "qsVersion": "iOS 11.2.6”,
                "locationId": "61560",
                "name": "Next Fit Clubs",
                "address": "129 Stryker Lane",
                "city": "Hillsborough",
                "state": "NJ",
                "locationType": "club"
            },

**Comment by christocracy** [comment]
- `qsDevice_name` is a constant.  can be applied to `#params`
- `qsVersion` is a constant.  can be applied to `#params`

All your other data can be appended to the [`TSGeofence #extras`](https://github.com/transistorsoft/background-geolocation-lt/blob/ios-android-refactor/docs/README-iOS.md#property-nsdictionary-extras-optional-arbitrary-meta-data) option when you create the geofence.

**Comment by Jeyavijay** [comment]
yeah those are constants but the below details like locationid, name, address, city are all dynamic . So i have to post that data to the server. That's why i requested you how to handle this thing. Whether in Ongeofence or any other ways are possible?

**Comment by christocracy** [comment]
You’re not doing reverse geolocation on the device, are you?

**Comment by Jeyavijay** [comment]
No i'm not.

the confusion is not to post the data repeatedly for a same location triggering. Thats the reason i'm seeking for a solution!!

**Comment by christocracy** [comment]
This issue is titled “
Passing URL with header authorization”.  Is that solved?

**Comment by Jeyavijay** [comment]
Yeah using header its working fine
