### ISSUE TITLE
Missing Documentation for HeadLess Mode for Android Native

### ISSUE THREAD

**Issue by jsfunfun** [transistorsoft/background-geolocation-lt#19]
The docs for this topic appear to be blank:

https://github.com/transistorsoft/background-geolocation-lt/wiki

## Your Environment
* Plugin version: all
* Platform: Android
* OS version: 5.1 up
* Device manufacturer / model: n/a
* Plugin config: enableHeadless = true

**Comment by christocracy** [comment]
Yes, I think I have to add a bit of code to the project.  In the meantime, you can copy what I did for the `react-native-background-geolocation` version.

**:warning:** I haven't tested any of this in native environment.  I've copied this implementation from the Cordova / React Native versions.

#### Step 1:  `AndroidManifest.xml`
- Add the following `<service>` and <receiver>`.  Replace `com.your.namespace.HeadlessJobService` / `com.your.namespace.HeadlessBroadcastReceiver` with your own custom classes.  The `JobService` is used when device api `>= lollipop`.  Otherwise `BroadcastReceiver` is used.

```diff
<application android:label="@string/app_name"
        android:supportsRtl="true">

+        <service android:name="com.your.namespace.HeadlessJobService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true" />

+        <receiver android:name="com.your.namespace.HeadlessBroadcastReceiver">
+            <intent-filter>
+                <action android:name="${applicationId}.tslocationmanager.event.LOCATION" />
+                <action android:name="${applicationId}.tslocationmanager.event.MOTIONCHANGE" />
+                <action android:name="${applicationId}.tslocationmanager.event.ACTIVITYCHANGE" />
+                <action android:name="${applicationId}.tslocationmanager.event.PROVIDERCHANGE" />
+                <action android:name="${applicationId}.tslocationmanager.event.POWERSAVECHANGE" />
+                <action android:name="${applicationId}.tslocationmanager.event.HEARTBEAT" />
+                <action android:name="${applicationId}.tslocationmanager.event.GEOFENCE" />
+                <action android:name="${applicationId}.tslocationmanager.event.HTTP" />
+                <action android:name="${applicationId}.tslocationmanager.event.SCHEDULE" />
+                <action android:name="${applicationId}.tslocationmanager.event.BOOT" />
+                <action android:name="${applicationId}.tslocationmanager.event.TERMINATE" />
+            </intent-filter>
+        </receiver>

    </application>
```

#### Step 3:  Create 3 Java files in your app:

*HeadlessBroadcastReceiver.java*
```java
package com.your.namespace;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import com.transistorsoft.locationmanager.logger.TSLog;

import org.json.JSONException;
import org.json.JSONObject;

public class HeadlessBroadcastReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        Bundle extras = intent.getExtras();

        try {
            String eventName = extras.getString("event");
            TSLog.logger.debug("\uD83D\uDC80  event: " + eventName);

            JSONObject event = new JSONObject(extras.getString("params"));

            HeadlessTask.invoke(context.getApplicationContext(), eventName, event, new CompletionHandler());
        } catch (JSONException e) {
            TSLog.logger.error(TSLog.error(e.getMessage()));
            e.printStackTrace();
        }
    }

    class CompletionHandler implements HeadlessTask.Callback {
        public void finish() {
            // Do nothing with BroadcastReceiver.
        }
    }
}
```

*HeadlessJobService.java*
```java
package com.your.namespace;

import android.annotation.TargetApi;
import android.app.job.JobParameters;
import android.app.job.JobService;
import android.os.PersistableBundle;

import com.transistorsoft.locationmanager.logger.TSLog;

import org.json.JSONException;
import org.json.JSONObject;

@TargetApi(21)
public class HeadlessJobService extends JobService {

    @Override
    public boolean onStartJob(final JobParameters params) {
        PersistableBundle extras = params.getExtras();
        try {
            String eventName = extras.getString("event");
            TSLog.logger.debug("\uD83D\uDC80  event: " + eventName);

            JSONObject event = new JSONObject(extras.getString("params"));
            HeadlessTask.invoke(getApplicationContext(), eventName, event, new CompletionHandler(params));
        } catch (JSONException e) {
            TSLog.logger.error(TSLog.error(e.getMessage()));
            jobFinished(params, false);
            e.printStackTrace();
        }
        return true;
    }
    @Override
    public boolean onStopJob(JobParameters params) {
        TSLog.logger.debug("HeadlessJobService onStopJob");
        jobFinished(params, false);
        return true;
    }

    class CompletionHandler implements HeadlessTask.Callback {
        private JobParameters mParams;
        public CompletionHandler(JobParameters params) {
            mParams = params;
        }
        public void finish() {
            jobFinished(mParams, false);
        }
    }
}
```

*HeadlessTask.java*
```java
package com.your.namespace;

import android.content.Context;

import com.transistorsoft.locationmanager.adapter.BackgroundGeolocation;
import com.transistorsoft.locationmanager.logger.TSLog;

import org.json.JSONObject;


public class HeadlessTask {
    static void invoke(Context context, String event, JSONObject params, HeadlessTask.Callback completionHandler) {
        TSLog.logger.debug("[HeadlessTask] " + event + ", params: " + params.toString());

        // Do some work...

        // Signal completion of task.
        completionHandler.finish();
    }

    interface Callback {
        void finish();
    }
}
```

**Comment by jsfunfun** [comment]
in the manifest xml file you have the intent keys such as: ... tslocationmanager.event.GEOFENCE .. wouldn't those normally be visible to my app if they existed? I don't see those defined in any of the TS namespaces? consequently, I was hoping the service/broadcast/receivers I wrote to get the geo event base on your example would work... i'm not getting any geofence events.. zero .. both in the app, in your demo app, nor in this receiver... what am i missing about geofence callbacks? thanks...

**Comment by christocracy** [comment]
Are you attempting to get geofences to fire from mocked locations or real-world field-testing?

**Comment by christocracy** [comment]
>I was hoping the service/broadcast/receivers I wrote 

You probably wrote those handlers in the context of your MainActivity.

MainActivity doesn’t exist in Headless Mode.  You will have to simply encapsulate that code into a separate class which you import into both your Activity context as well as HeadlessTask context.

**Comment by jsfunfun** [comment]
re: "mocked locations or real-world field-testing?".. from real-world - on my Android phone..... real GPS coords that i exist at... the log shows it finds the points... (in both my own app, and your demo app nearly unchanged).. but in both the onGeofence call back never happens...

```
                     ╔═════════════════════════════════════════════
                     ║ TSGeofenceManager found 7/20 within 1000 meters
                     ╠═════════════════════════════════════════════
                     ╟─ 🎾  13.  - Starbucks
                     ╟─ 🎾  15.  - McDonald's Street Corner
                     ╟─ 🎾  14.  - ACME Oranges
                     ╟─ 🎾  12.  - Arlington - Lower Circle
                     ╟─ 🎾  16.  - Arlington Composte House
                     ╟─ 🎾  11.  - Arlington - Big 4-way
                     ╟─ 🎾  10.  - Arlington - Tree
                     ╚═════════════════════════════════════════════
```

I have TS create/configure/start all encapsulated in my own class - in my own "module" that is linked to my app... everything executed in the module - in headless mode. The design goal is that the "module" is the coordinator of it all. I had most of it working - even the onLocation callback was working in .. but onGeofence call back never would work - which is why I had to reach out to you... 

so my issues are still (a) encapsulated in a class, the onGeofence CB never fires, and (b) none of the headless receivers get fired I guess because I don't know what the proper filter names are (eg: *.tslocationmanager.event.GEOFENCE... what's the context of the "*") .. if those don't match up exactly to what you are firing events with then I'm not sure I'd get any of them..

Do I have to add my license file to the build to get that callback? I didn't see that anywhere as a requirement... 

Thanks for your input...

**Comment by christocracy** [comment]
Also add this to your `TSConfig`:
```java
TSConfig config = TSConfig.getInstance();
config.updateWithBuilder()
  config.setHeadlessJobService("com.your.namespace.HeadlessJobService")
  .
  .
  .
  .commit();
```

Where `com.your.namespace.HeadlessJobService` corresponds to the `<service />` defined in `AndroidManifest.xml`

```xml
<service android:name="com.your.namespace.HeadlessJobService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true" />
```

As for the `<intent-filter> <action />`, you don't need to worry about those names or whether they're available upon `BackgroundGeolocation`.  Just paste them exactly as shown.

**Comment by mobiRic** [comment]
If I'm using the SDK in a native Android app, and configuring it to send my locations to the API and nothing else, would the correct option be to `setEnableHeadless(false)`?

Will that still provide reliable background tracking all handled by TransistorSoft?

Or should I be configuring a `HeadlessJobService` and a `HeadlessBroadcastReceiver` that both just do nothing?
