### ISSUE TITLE
iOS React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by kalyan711987kalyan** [transistorsoft/background-geolocation-lt#2]
## Xcode 9
* Plugin version:
* Platform: iOS 10

I'm integrating you SDK. But while running, I'm getting "React/RCTEventEmitter.h' file not found""
Any help would be thanks full.

**Comment by christocracy** [comment]
This repo is not ready for use.

Are you implementing using React Native?  This is the wrong repo for that.

**Comment by kalyan711987kalyan** [comment]
Hi Christocracy,
One of your client bought your SDK.I integrated your SDK and running into these issues:
![screen shot 2017-11-23 at 12 11 13 pm](https://user-images.githubusercontent.com/1528160/33161285-728212ce-d048-11e7-970a-ccad03ec28d1.png)
Please provide steps to integrate "background-geolocation-lt" in my project.
