### ISSUE TITLE
Android - TSGeofenceCallback::onGeofence is not called on initial launch

### ISSUE THREAD

**Issue by jsfunfun** [transistorsoft/background-geolocation-lt#20]
In the TS provided "demo" app for Android, if one adds a GeoFence waypoint - the TSGeofenceCallback::onGeofence method is never called.

## Your Environment
* Plugin version: background-geolocation-lt-0.1.0
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Nexus
* Plugin config

config options are:
```
	config.updateWithBuilder()
	.setDebug(true)
	.setLogLevel(5)
	.setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
	.setDistanceFilter(50f)
	.setStopTimeout(1L)
	.setForegroundService(true)
	.setStopOnTerminate(false)
	.setStartOnBoot(true)
	.setGeofenceInitialTriggerEntry(true)
	.commit();
```

## Expected Behavior
The callback method that was registered should be called:
```
	private TSGeofenceCallback createGeofenceCallback() {
		return new TSGeofenceCallback() {
			@Override
			public void onGeofence(GeofenceEvent event) {
				TSLog.logger.debug("[geofence] " + event.toJson());
			}
		};
	}
```

## Actual Behavior
Nothing is called

## Steps to Reproduce
Download the TS sample demo app. Open in Android Studio. Register the callback:

```
	// Listen to geofence event
	
	bgGeo.onGeofence(createGeofenceCallback());
```

Add a waypoint such as:

```
	// **NOTE** PUT YOUR OWN CURRENT LOCATION AS THE WAYPOINT
	TSGeofence tsGeofence = new TSGeofence.Builder()
			.setIdentifier("LIBERTY BELL")
			.setRadius(100f)
			.setLatitude(39.949603f)
			.setLongitude(-75.150283f)
			.setNotifyOnEntry(true)
			.setNotifyOnExit(true)
			.setNotifyOnDwell(true)
			.build();

	bgGeo.addGeofence(tsGeofence, new TSCallback()
	{
		@Override
		public void onSuccess()
		{
			Log.i(TAG, "addGeofence:onSuccess");
		}

		@Override
		public void onFailure(String s)
		{
			Log.i(TAG, "addGeofence:onFailure " + s);
		}
	});
```

## Context
have onGeofence called.

## Debug logs
[Logs-GeoFence-Event-Not-Fired.txt](https://github.com/transistorsoft/background-geolocation-lt/files/2081180/Logs-GeoFence-Event-Not-Fired.txt)

[TS-GeoFence-Event-Not-Fired.zip](https://github.com/transistorsoft/background-geolocation-lt/files/2081182/TS-GeoFence-Event-Not-Fired.zip)

**Comment by christocracy** [comment]
The minimum reliable geofence radius is `150` meters.  First try with radius `200`.

**Comment by christocracy** [comment]
This has nothing to do with geofences not firing, but I wonder what's going on with the plugin's logger database?  
```
W/System: ClassLoader referenced unknown path: /data/app/com.transistorsoft.backgroundgeolocation.demo-1/lib/arm
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/JOE: STARTED APP
I/art: Do partial code cache collection, code=29KB, data=25KB
       After code cache collection, code=29KB, data=25KB
       Increasing code cache capacity to 128KB
I/art: Do partial code cache collection, code=61KB, data=49KB
       After code cache collection, code=60KB, data=48KB
       Increasing code cache capacity to 256KB
E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
             (14) os_unix.c:32456: (13) open(/data/data/com.transistorsoft.backgroundgeolocation.demo/databases/transistor_logback.db) - 
E/SQLiteDatabase: Failed to open database '/data/data/com.transistorsoft.backgroundgeolocation.demo/databases/transistor_logback.db'.
```

**Comment by jsfunfun** [comment]
Chris - in your TS library, in the addGeofence or addGeofences calls - you are not checking and or returning the correct error condition. those always return onSuccess when I add points.. However I built my own impl and app using the raw Google api and I see they return onFailure when adding the same point or points... The error is code: 1000 - see pic

That error code means GEOFENCE_NOT_AVAILABLE... -see pic

Why?

Because people's android phones can be set to any of 3 choices for GPS... 

and for GeoFencing to work -- at least on my Nexus it has to be set to HiResultion - see pic..

once I changed my device setting to High res, i immediately got my call back in my own RECEIVER intent / and in my app code for my current geoFence!!!

Then I ran my impl of your lib and I immediately got my "in app" callback of onGeofence .. but those enternal broadcast/receive module -- not being called at all still.. still a problem .. is my app going to wake up on a reboot and call my internal "app" version of onGeofence .. or is it going to call the Headless receiver (i have it configed for headless)...

Could you fix that issue and call onFailure with the google returned error codes?

Thanks for your input..

-JS


<img width="868" alt="screen shot 2018-06-08 at 5 59 11 pm" src="https://user-images.githubusercontent.com/3376550/41194444-57a67e1c-6be9-11e8-8c5b-d5ce7c1edbfc.png">
<img width="751" alt="screen shot 2018-06-08 at 5 57 25 pm" src="https://user-images.githubusercontent.com/3376550/41194445-57b11304-6be9-11e8-8ad3-f0a3f04327e5.png">
<img width="519" alt="screen shot 2018-06-08 at 5 55 24 pm" src="https://user-images.githubusercontent.com/3376550/41194446-57c0ed60-6be9-11e8-8ace-f6b4e9cd2f1f.png">

**Comment by jsfunfun** [comment]
device shot

<img width="326" alt="screen shot 2018-06-09 at 1 34 01 pm" src="https://user-images.githubusercontent.com/3376550/41194488-cc36ce8a-6be9-11e8-8beb-50863363e1ef.png">

**Comment by christocracy** [comment]
Wasn’t aware of this.  Yes, I can add that.

**Comment by jsfunfun** [comment]
thx ..

**Comment by jsfunfun** [comment]
Chris, 

In response to the Plugin's Logger Database issue:

```
E/SQLiteDatabase: Failed to open database
'/data/data/com.transistorsoft.backgroundgeolocation.demo/databases/transistor_logback.db'.
```

The issue is that for a very early part of my TS testing I decided to work on a pristine clean account and I made myself a new Android account on my phone.

Running TS on any account other than the "root" phone account causes the failed database issue. I attached the full stack herein.

I also went back to see how that Android "location mode" setting works across users. Even though I had my "root" account is set for the High Accuracy mode - when I just now made a new test account on my phone the location mode for my new user defaulted back to "Device Only" - which we now know prohibits Geofencing. 

Cheers,

Joe

[non-root-android-account-logger-bug.txt](https://github.com/transistorsoft/background-geolocation-lt/files/2090893/non-root-android-account-logger-bug.txt)

**Comment by christocracy** [comment]
Are you aware of the [`locationproviderchange`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md#locationproviderchange) event?  You can capture changes to Location settings with that.

The event is fired with each boot of the device so you can know the current state.  Be sure to listen to it *before* you execute `#ready` (`#ready` *causes* the event to fire).
