### ISSUE TITLE
Unable to archive iOS build with new plugin

### ISSUE THREAD

**Issue by satishkolawale** [transistorsoft/background-geolocation-lt#21]
I have updated new location plugin in my existing code. And it is successfully installed on my device while archiving project it is throwing an error "
no such file or directory:'/Users/ravijoshi/Library/Developer/Xcode/DerivedData/Serendipity-gdtfomavpjvejmdrxhfgjqitonyc/Build/Intermediates.noindex/ArchiveIntermediates/Serendipity/BuildProductsPath/Release-iphoneos/libCocoaLumberjack.a"
Could you please help me out what I'm missing? This is urgent so please reply me back ASAP.

**Comment by christocracy** [comment]
[See Installation docs](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/INSTALL-IOS.md#install-cocoalumberjack)

**Comment by satishkolawale** [comment]
Already we referred this doc but could not.

**Comment by satishkolawale** [comment]
Chris my Xcode version is 9.2. is above mentioned issue is related to Xcode version?

**Comment by christocracy** [comment]
Follow the installation instructions for [CocaoLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack)
