### ISSUE TITLE
Android - Not Tracking Geofences

### ISSUE THREAD

**Issue by ps-dfritzsch** [transistorsoft/background-geolocation-lt#23]
## Your Environment
* Plugin version: **2.12.12**
* Platform: **Android**
* OS version: **8+** (used multiple devices)
* Device manufacturer / model: One Plus 3 & 5, Xiami Mi A1
* Plugin **config**: 
```
config.updateWithBuilder()
         .setDebug(true) // currently true
         .setActivityRecognitionInterval(60000L)
         .setGeofenceProximityRadius(99999L)
         .setDesiredAccuracy(100)
         .setDistanceFilter(50.0f)
         .setMaxDaysToPersist(7)
         .setDisableElasticity(false)
         .setDisableStopDetection(false)
         .setStopOnTerminate(false)
         .setStartOnBoot(true)
         .setUrl(“XXXX“)
         .setHeader("XXXX”)
         .setBatchSync(true)
         .setAutoSyncThreshold(5)
         .setMaxBatchSize(200)
         .setExtras({
             “platform”: “android”,
             “route”: “XXXX”,
             “token”: “XXXX”,
         })
       .commit();
```

## Expected Behavior
Track geofences on geofence enter/exit.

## Actual Behavior
**Not tracking geofences** on enter/exit.

The library seems to be running correctly (making sounds & logging traces). No geofence is found although location & geofence show the **same latitude / longitude**.

## Steps to Reproduce
1. Set library to **ready**
1. Add **geofences** (**4 geofences, 150m & 500m radius** for start & end location)
1. **Start** library
1. No geofences tracked on enter/exit...

## Context
Configured everything according to your readme and **similar to our iOS & Cordova config** (where tracking is working sometimes).

### Geofences from backgroundGeolocation.getGeofences():
```
{
    "identifier": "Start_150",
    "radius": 150,
    "latitude": 15.432579000000004,
    "longitude": 47.06463600000001,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
}
{
    "identifier": "Start_500",
    "radius": 500,
    "latitude": 15.432579000000004,
    "longitude": 47.06463600000001,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
}
{
    "identifier": "End_150",
    "radius": 150,
    "latitude": 15.423763500000064,
    "longitude": 47.07408600000008,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
}
{
    "identifier": "End_500",
    "radius": 500,
    "latitude": 15.423763500000064,
    "longitude": 47.07408600000008,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
}
```

### Location updates from backgroundGeolocation.onLocation() callback:
```
// tsLocation.getGeofence()
"geofence": null

// tsLocation.toJson()
{
    "event": "motionchange",
    "is_moving": false,
    "uuid": "XXXX",
    "timestamp": "2018-06-14T10:42:07.000Z",
    "odometer": 0,
    "coords": {
        "latitude": 47.0666983,
        "longitude": 15.4316983,
        "accuracy": 20,
        "speed": -1,
        "heading": -1,
        "altitude": 0
    },
    "activity": {
        "type": "still",
        "confidence": 100
    },
    "battery": {
        "is_charging": true,
        "level": 1
    },
    "extras": {
        "platform": "android",
        "route": "XXXX",
        "token": "XXXX"
    }
}
```

**Comment by christocracy** [comment]
Two of your geofences show `"radius": 100`.  I don't trust these.

Are you testing in field or with Mocked location?

Fetch the logs.  See `#getLog` method in docs.

**Comment by ps-dfritzsch** [comment]
@christocracy I just updated the debug logs, we are currently using a **radius of 150 & 500**.

We are testing with **real devices** while moving & with mocked locations in the **emulator** that should also behave like real-world location updates.

**Comment by christocracy** [comment]
Geofences don't fire with mocked locations, unfortunately.

**Comment by ps-dfritzsch** [comment]
They also did not fire when using real devices. We tried it with several ones on several different trips, none have been tracking geofences so far.

**Comment by christocracy** [comment]
- Ensure Wifi enabled.
- Use a device with provisioned SIM card.

**Comment by christocracy** [comment]
There is important information in the logs.

**Comment by ps-dfritzsch** [comment]
Phones were used with **wifi enabled & provisioned** sim card.

**Comment by ps-dfritzsch** [comment]
We are currently including the `#getLog` debug method and will provide the logs afterward.

**Comment by christocracy** [comment]
I await your logs.  in the meantime, in Device Settings->Location:  What is location mode set to?
- High Accuracy?
- Battery Saving?
- Device Only?

**Comment by christocracy** [comment]
You can also use `#emailLog`.

**Comment by ps-dfritzsch** [comment]
2 devices used **High Accuracy** for the others I cannot tell for sure.

**Comment by ps-dfritzsch** [comment]
Should it work with **debug builds** or must it be a release build (using the license)?

**Comment by christocracy** [comment]
- The plugin is fully operational in DEBUG builds.  In fact I develop / test without a license.
- Only RELEASE build requires a license.

**Comment by ps-dfritzsch** [comment]
`#emailLog` **config** output:
```
{
    "activityRecognitionInterval": 60000,
    "allowIdenticalLocations": false,
    "autoSync": true,
    "autoSyncThreshold": 5,
    "batchSync": true,
    "debug": false,
    "deferTime": 0,
    "desiredAccuracy": 100,
    "desiredOdometerAccuracy": 100,
    "disableElasticity": false,
    "disableStopDetection": false,
    "distanceFilter": 50,
    "elasticityMultiplier": 1,
    "enableHeadless": false,
    "extras": {
        "platform": "android",
        "route": "https:\/\/pseudo.domain.com\/users\/XXXXXX\/traces",
        "token": "Bearer XXXXXX”
    },
    "fastestLocationUpdateInterval": 10000,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 99999,
    "geofenceTemplate": "",
    "headers": {
        "Authorization": "Bearer XXXXXX"
    },
    "headlessJobService": "",
    "heartbeatInterval": -1,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": true,
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 1000,
    "locationsOrderDirection": "ASC",
    "logLevel": 5,
    "logMaxDays": 3,
    "maxBatchSize": 200,
    "maxDaysToPersist": 7,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 75,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "",
    "params": {},
    "persist": true,
    "schedule": [],
    "startOnBoot": true,
    "stationaryRadius": 25,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 5,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "https:\/\/pseudo.domain.com\/users\/XXXXXX\/traces",
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 3021.969970703125,
    "isFirstBoot": false
}
```

**Comment by ps-dfritzsch** [comment]
`logEmail` attachment (obfuscated):
[Issue 23_logEmail_Output.txt](https://github.com/transistorsoft/background-geolocation-lt/files/2122538/Issue.23_logEmail_Output.txt)

**Comment by ps-dfritzsch** [comment]
When **comparing to our iOS config**, we can see the following differences:

Android is `missing`:
1. **activityType** = true
1. **useSignificantChangesOnly** = false

Android `differences`:
1. **heartbeatInterval** = -1 (60 for iOS)
1. **minimumActivityRecognitionConfidence** = 75 (70 for iOS)
1. **stopAfterElapsedMinutes** = 0 (-1 for iOS)
1. **urls / escaped** (not escaped for iOS)

**Comment by christocracy** [comment]
- activityType = true
- useSignificantChangesOnly = false

These are iOS-only options.

>heartbeatInterval = -1 (60 for iOS)

This is correct.  iOS `heartbeat` event is only fired when `preventSuspend = true`.  The plugin enforces a minimum `heartbeatInterval =  60` for iOS, so you don't shoot yourself in the foot.

>minimumActivityRecognitionConfidence = 75 (70 for iOS)

Correct.  iOS has different granularity of reported confidence.

>urls / escaped (not escaped for iOS)

This is just from printing to logs.

>stopAfterElapsedMinutes = 0 (-1 for iOS)

Both mean disabled.  The plugin reacts to this config option only when value `>0`.

None of these options have any effect on geofencing.

**Comment by christocracy** [comment]
So your logs now:  You can see in the logs where the plugin is performing its periodic geospatial query to determine geofences within range:
```
06-21 08:12:49.673 DEBUG [LocationService onLocation] 
╔═════════════════════════════════════════════
║ LocationService: location
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.073304,15.419606 hAcc=12 et=+13h45m25s348ms alt=438.4161376953125 vAcc=8 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 12ms, time: 1529561570000
.
06-21 08:12:49.724 DEBUG [TSGeofenceManager a] 
╔═════════════════════════════════════════════
║ TSGeofenceManager found 0/4 within 99999 meters
╠═════════════════════════════════════════════
╚═════════════════════════════════════════════
```
Here is your current location [47.073304,15.419606](https://www.google.com/maps/place/47%C2%B004'23.9%22N+15%C2%B025'10.6%22E/@47.073304,10.9371788,6z/data=!4m5!3m4!1s0x0:0x0!8m2!3d47.073304!4d15.419606).  You are in Austria, near a town called Graz.

Here is your geofence:
```
{
    "identifier": "Start_150",
    "radius": 150,
    "latitude": 15.432579000000004,
    "longitude": 47.06463600000001,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
}
```
[15.432579000000004,47.06463600000001](https://www.google.com/maps/place/15%C2%B025'57.3%22N+47%C2%B003'52.7%22E/@15.432579,45.9440252,8z/data=!4m5!3m4!1s0x0:0x0!8m2!3d15.432579!4d47.064636).  Somewhere in the desert of Yemen.

**Comment by christocracy** [comment]
You have your `latitude / longitude` backwards.  Your geofence is supposed to be:
```
{
    "identifier": "Start_150",
    "radius": 150,
    "latitude": 47.06463600000001,
    "longitude": 15.432579000000004,
    "notifyOnEntry": true,
    "notifyOnExit": true,
    "notifyOnDwell": false,
    "loiteringDelay": 0
}
```

**Comment by ps-dfritzsch** [comment]
Thank you Chris, your checks & this observation have been very helpful!
