### ISSUE TITLE
Android: Constant Release Tracking Notification

### ISSUE THREAD

**Issue by ps-dfritzsch** [transistorsoft/background-geolocation-lt#24]
## Your Environment
* Plugin version: **2.12.12**
* Platform: **Android**
* OS version: **8+** (used multiple devices)
* Device manufacturer / model: One Plus 3 & 5, Xiami Mi A1
* Plugin **config**: 
```
config.updateWithBuilder()
         .setDebug(BuildConfig.DEBUG)
         .setActivityRecognitionInterval(60000L)
         .setGeofenceProximityRadius(99999L)
         .setDesiredAccuracy(100)
         .setDistanceFilter(50.0f)
         .setMaxDaysToPersist(7)
         .setDisableElasticity(false)
         .setDisableStopDetection(false)
         .setStopOnTerminate(false)
         .setStartOnBoot(true)
         .setUrl(“XXXX“)
         .setHeader("XXXX”)
         .setBatchSync(true)
         .setAutoSyncThreshold(5)
         .setMaxBatchSize(200)
         .setExtras({
             “platform”: “android”,
             “route”: “XXXX”,
             “token”: “XXXX”,
         })
       .commit();
```

## Expected Behavior
Release build app is tracking without constantly showing a non-dismissable notification bar.

## Actual Behavior
Release build app is tracking while constantly showing a **non-dismissable notification ba**r.

## Steps to Reproduce
1. **Start** library

**Comment by christocracy** [comment]
The plugin must run as a foreground-service in Android 8+ Due to strict new Android Background execution limits.

The notification is required by the OS and cannot be hidden.

**Comment by ps-dfritzsch** [comment]
We were wondering why there is a foreground service running at all since the google location API should handle the tracking, which does not have to be started using a foreground task: [Google location API](https://developer.android.com/training/location/receive-location-updates)

Is this mainly due to the configuration within a library or what is the reason for this?

**Comment by christocracy** [comment]
If you engage location services outside of a foreground-service, tracking would terminate when the MainActivity terminates (ie stopOnTerminate: false, startOnBoot: true would not be possible)

**Comment by ps-dfritzsch** [comment]
Is it really necessary to show it **all the time**? As far as we understand it, the foreground service could only be started once the device is **outside of its geofences**.

In this case, the notification would only be shown once the user/device is moving and not "sitting" at one of its geofences.

**Comment by ps-dfritzsch** [comment]
I am referring to this:
https://developer.android.com/training/location/geofencing#HandleGeofenceTransitions
