### ISSUE TITLE
playServicesVersion = "15.0.1"

### ISSUE THREAD

**Issue by Baniares** [transistorsoft/background-geolocation-lt#25]
Apparently the library does not support the latest version os the google play services and I think is should be fixed.

## Your Environment
* Plugin version: 0.1.1
* Platform: Android

## Expected Behavior
we should be able to use the latest Google play services version
## Actual Behavior
`Cannot invoke method get() on null object` I get that error when I try to sync the project with ` playServicesVersion = "15.0.1"`

**Comment by christocracy** [comment]
I’m using ‘15.0.1` with the plugin in a number apps.  You have a dependency conflict with something else.

Post your `platforms/android/project.properties`

**Comment by Baniares** [comment]
Just found out that the problem was firebase itself.
