### ISSUE TITLE
Sync Failed

### ISSUE THREAD

**Issue by melkopisi** [transistorsoft/background-geolocation-lt#26]
## Your Environment
* Plugin version: 0.1.1
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: Xiaomi Mi A2Lite
* Plugin config

## Expected Behavior
A Successful Sync

## Actual Behavior
Sync Failed

` Failed to resolve: com.transistorsoft:tslocationmanager:+
`

**Comment by christocracy** [comment]
Did you follow the [Setup Docs](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/INSTALL-ANDROID.md#android-installation)?

**Comment by melkopisi** [comment]
Yes Sir

**Comment by christocracy** [comment]
Did you try booting the Example app in this repo?

**Comment by melkopisi** [comment]
No but let me try it

**Comment by melkopisi** [comment]
The Example is working fine

**Comment by christocracy** [comment]
compare the example's `settings.gradle`, `build.gradle`, `app/build.gradle` to your own.

**Comment by melkopisi** [comment]
thanks man it works fine now

**Comment by christocracy** [comment]
For the benefit of future others, what was it?

Do the setup docs need something?

**Comment by melkopisi** [comment]
you need to update the versions in the documentation with the working versions in the demo

i mean those version in 

`ext{

}`

**Comment by melkopisi** [comment]
sorry for opening this issue again but i have a build failed condition due to

> Failed to resolve: com.transistorsoft:tslocationmanager:+

i'm adding your library to my new SDK for Location Utilities so how can i fix this error

**Comment by christocracy** [comment]
For the `ext`, it's assumed you'll put your own desired values there.  Presumably the latest available versions.

Post your gradle files:
- `settings.gradle`
- `build.gradle`
- `app/build.gradle`

**Comment by melkopisi** [comment]
yes i know that but those old version was conflicting with my gradle  and build tools version

###settings.gradle`

 `include ':app', ':background-geolocation'
project(':background-geolocation').projectDir = new File(rootProject.projectDir, './Libraries/background-geolocation-lt/android/background-geolocation')`

###build.gradle
and i don't use `ext` for now i'm just adding the
` maven { url project(':background-geolocation').projectDir.absolutePath + "/libs"}`

###app/build.gradle
in dependencies i'm adding
`  implementation project(':background-geolocation')`

**Comment by christocracy** [comment]
Is this still an issue?
