### ISSUE TITLE
onGeofence event delay

### ISSUE THREAD

**Issue by selyon** [transistorsoft/background-geolocation-lt#27]
* Plugin version: 0.1.1
* Platform: Android
* OS version: 5.1

Expected Behavior
onGeofence callback called when the device enter/exit a geofence

Actual Behavior
the callback is called with few minutes delay

Logs:
10-04 16:40:43.104 DEBUG [MainActivity$3 onLocation] [location] {"is_moving":true,"timestamp":"2018-10-04T14:40:44.000Z","odometer":19137.8,"coords":{"latitude":44.7912283,"longitude":11.6123083,"accuracy":10,"speed":24.24,"heading":88,"altitude":-6.9},"activity":{"type":"in_vehicle","confidence":44}}

This location was recorded at 16:40 pm but the same minute a geofence event was raised

10-04 16:40:43.260 DEBUG [MainActivity lambda$createGeofenceCallback$0] [geofence] {"location":{"event":"geofence","is_moving":true,"timestamp":"2018-10-04T14:36:39.000Z","odometer":22280.4,"coords":{"latitude":44.8026717,"longitude":11.5759883,"accuracy":10,"speed":16.34,"heading":224,"altitude":-6.3},"activity":{"type":"in_vehicle","confidence":44},"geofence":{"identifier":"3","action":"ENTER"}},"identifier":"3","action":"ENTER"}

The ENTER event is 4 minutes late in this case (the timestamp in the JSON says 14 pm but it's UTC time and i'm in a different timezone, it's 16:36 pm the time of the event). I had the same problem with other ENTER/EXIT events

**Comment by christocracy** [comment]
Check your Settings->Location:  Make sure mode is "High Accuracy"
