### ISSUE TITLE
Crash in TSDatabase

### ISSUE THREAD

**Issue by ps-mmaierhuber** [transistorsoft/background-geolocation-lt#28]
Segfault Crash in TSDatabase

## Your Environment

* Plugin version: 0.1.1
* Platform: iOS
* OS version: Any
* Device manufacturer / model: Any
* Plugin config
autoSyncThreshold: 5,
desiredAccuracy: 100,
distanceFilter: 50,
maxDaysToPersist: 7,
maxBatchSize: 200,
stopDetectionDelay: 0,
activityRecognitionInterval: 60000,
geofenceProximityRadius: 99999,
batchSync: true, 
debug: false,
disableElasticity: false,
disableMotionActivityUpdates: false,
disableStopDetection: false,
startOnBoot: true,
stopOnTerminate: false,
activityType: "Other",
locationAuthorizationRequest: "Always"

## Expected Behavior

No crashes

## Actual Behavior

Crashing when app is running in the background

## Steps to Reproduce

Unknown

## Debug logs
SIGSEGV · Attempted to dereference garbage pointer 0x105.
1	MyApp	
TSDatabase.m:1076:21
-[TSDatabase executeUpdate:error:withArgumentsInArray:orDictionary:orVAList:]
2	MyApp	
TSDatabase.m:1204:19
-[TSDatabase executeUpdate:]
3	MyApp	
TSDBLogger.m:249:13
-[TSDBLogger db_save]
4	DDAbstractDatabaseLogger.m	
-[DDAbstractDatabaseLogger performSaveAndSuspendSaveTimer]
5	MyApp	
DDAbstractDatabaseLogger.m:146:61
__52-[DDAbstractDatabaseLogger createSuspendedSaveTimer]_block_invoke

**Comment by ps-mmaierhuber** [comment]
Another one, maybe related:

SIGSEGV: Attempted to dereference garbage pointer 0x3ff0000000000000.

0  libobjc.A.dylib            _objc_msgSend
1  UIKitCore                  __UIViewDescriptionAppendFrame
2  UIKitCore                  -[UIView(UIDebugging) description]
3  MyApp                      -[TSDatabase bindObject:toColumn:inStatement:] (TSDatabase.m:659:40)
4  MyApp                      -[TSDatabase executeUpdate:error:withArgumentsInArray:orDictionary:orVAList:] (TSDatabase.m:1094:13)
5  MyApp                      -[TSDatabase executeUpdate:] (TSDatabase.m:1204:19)
6  MyApp                      -[TSDBLogger db_save] (TSDBLogger.m:249:13)
7  DDAbstractDatabaseLogger.m -[DDAbstractDatabaseLogger performSaveAndSuspendSaveTimer]
8  MyApp                      __52-[DDAbstractDatabaseLogger createSuspendedSaveTimer]_block_invoke (DDAbstractDatabaseLogger.m:146:61)

**Comment by christocracy** [comment]
Show me your code.  Does this happen immediately on app boot?

**Comment by ps-mmaierhuber** [comment]
From what i can see in the crash reports from users it happens some hours or even days while being in the background.

The tracking library is running a setup like this:
"configuration" is what you've seen above

```swift
self?.locationManager.configure(configuration)

            let url = APIClient.shared.currentSite.siteUrl

            self?.locationManager.setLogLevel(tsLogLevelVerbose)
            let tsConfig = TSConfig.sharedInstance()
            tsConfig?.update({ (builder) in
                builder?.url = url
                builder?.headers = [kAuthorizationHeader: token]
                builder?.batchSync = true
                builder?.method = "POST"
                builder?.autoSync = true
                builder?.autoSyncThreshold = 5
                builder?.maxBatchSize = 200
                builder?.extras = ["platform": "ios", "route": url, "token": token]
            })

                self?.locationManager.sync({ _ in }, failure: { _ in })
                self?.locationManager.ready()
                self?.locationManager.start()
```

**Comment by christocracy** [comment]
Please review the [Example](https://github.com/transistorsoft/background-geolocation-lt#ios)

Why are you using `[tsConfig update]`?  That's not documented.

Nor is `TSLocationManager setLogLevel`.  See [logLevel](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-iOS.md#config-tsloglevel-loglevel-tslogleveloff)

What is this?
```
builder?.extras = ["platform": "ios", "route": url, "token": token]
```

Isn't that supposed to be `{"platform":"ios", "route": url, "token": token}`

**Comment by ps-mmaierhuber** [comment]
This is a swift project, updateWithBlock is automatically translated to
```swift
func update(_ block: ((TSConfigBuilder?) -> Void)!)
```

same for the extras object being a swift dictionary that is declared with [] instead of @{} as in objc

**Comment by christocracy** [comment]
Whey are you using the method `locationManager.configure`?

The [example says to use `#ready`](https://github.com/transistorsoft/background-geolocation-lt#ios)

**Comment by ps-mmaierhuber** [comment]
Legacy, i migrated the app from a cordova project to a native project and the previous project was calling locationManager.configure, so i did the same. but i see that since 0.1.1 the TSConfigBuilder has all the properties available, so i will update this accordingly.

And locationManager.ready() is already being called after updating tsConfig.
