### ISSUE TITLE
Not getting location details after killing app from background

### ISSUE THREAD

**Issue by kalyan711987kalyan** [transistorsoft/background-geolocation-lt#3]
* Platform: iOS 
I tracking my app location using "background-geolocation-It"
After terminating my app from background, I don't see the location tracking.
I have set following propertied 
**preventSuspendTask = 1
stopOnTerminate = false**

Are there any other settings I should set?

**Comment by christocracy** [comment]
This repo is not ready for use.  Are you *actually* using the **Native** version, or are you using the *Cordova* or *React Native* version?

**Comment by christocracy** [comment]
You didn't get [my other message to you](https://github.com/transistorsoft/background-geolocation-lt/issues/2#issuecomment-345478016) where I mentioned this repo is not ready for use?

**Comment by kalyan711987kalyan** [comment]
I'm using native iOS version. One of our client suggest to use this SDK as he bought paid version.

**Comment by christocracy** [comment]
What is your client's name?

**Comment by kalyan711987kalyan** [comment]
Hopin

**Comment by christocracy** [comment]
I have no record of a "Hopin".  I need an email address.

[Watch this video](https://www.youtube.com/watch?v=aR6r8qV1TI8&t=273s)

An iOS app *IS* terminated.  However, the OS will reboot it in the background after the device *moves* at least 200 meters.

Have you read the docs for [`stopOnTerminate`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README.md#config-boolean-stoponterminate-true)

**Comment by kalyan711987kalyan** [comment]
This is his email "presidentpatel@gmail.com".

**Comment by christocracy** [comment]
Your client purchased the NativeScript version.  I don't currently provide support for native apps yet.
