### ISSUE TITLE
No action performs on both buttons in android sample app.

### ISSUE THREAD

**Issue by iVcardo** [transistorsoft/background-geolocation-lt#33]
## Your Environment
* Platform: Android

## Actual Behavior
When app opens then first i click on add geofences button then i only see toast with the message geofences added. after 5 to 10 minute I click on remove geofences button again toast display with geofences removed, nothing happened.

**Comment by christocracy** [comment]
My [demo app](https://github.com/transistorsoft/background-geolocation-lt/blob/master/android/app/src/main/java/com/transistorsoft/backgroundgeolocation/demo/MainActivity.java) has no "add geofences button".

**Comment by iVcardo** [comment]
I'm confused now, can you please share code of geofencing because in this demo app only geolocation and i eagerly waiting for geofencing. 
And one more question I have sample geofencing project with the package name **com.test.geofencingdemo**, and i can't able to find this project on GitHub is it yours?

**Comment by christocracy** [comment]
>And one more question I have sample geofencing project with the package name com.test.geofencingdemo

Not mine.

**Comment by iVcardo** [comment]
Okay, So can you please share code of geofencing because in this demo app only geolocation and i eagerly waiting for geofencing.

**Comment by christocracy** [comment]
See docs:
- [`addGeofence`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md#addgeofencetsgeofence-tscallback)
- Listen to [`onGeofence`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md#geofence) event.

**Comment by iVcardo** [comment]
Hello Chris,

I have added Geofence code in demo application, also run app. but not get any enter and exit boundary message (Toast), and i also try to check my locations entry through below url but no records are there.

[http://tracker.transistorsoft.com/locations/1test](url)

I have also added java file can you please check and let me know is there any issue?
[MainActivity.txt](https://github.com/transistorsoft/background-geolocation-lt/files/2606778/MainActivity.txt)

**Comment by christocracy** [comment]
Minimum radius is `200` meters.  `10` won't work.

**Comment by christocracy** [comment]
And why are you adding the geofence **twice**??
```java
bgGeo.addGeofence(geofence);

                // Finally, signal #ready to the SDK and #startGeofences
                bgGeo.ready(new TSCallback() {
                    @Override public void onSuccess() {
                        Log.i(TAG, "[ready] success");
                        bgGeo.startGeofences();
                    }
                    @Override public void onFailure(String error) {
                        Log.i(TAG, "[ready] FAILURE: " + error);
                    }
                });

// You may optionally supply a TSCallback to be notified of insert errors
                bgGeo.addGeofence(geofence, new TSCallback() {
                    @Override
                    public void onSuccess() {
                        Log.i(TAG, "[addGeofence] success");
                        Toast.makeText(MainActivity.this, "You'r in geofence", Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void onFailure(String error) {
                        Log.i(TAG, "[addGeofence] FAILURE: " + error);
                        Toast.makeText(MainActivity.this, "You'r out of geofence", Toast.LENGTH_LONG).show();
                    }
                });
```

**Comment by iVcardo** [comment]
Hello Chris,
I have added comment above 5 days ago and still not any response from your side.
Can you please help me to sort out this problem so I can implement in my app.
Thanks.

**Comment by christocracy** [comment]
Your logs don't show a geofence being monitored.

The callback to `addGeofence` is executed when a geofence was *successfully added and monitored*, **not when the geofence is fired.**.

You **LISTEN** to geofence via `onGeofence` method.  You code is totally wrong.

You have a chicken / egg problem.

**Comment by iVcardo** [comment]
Hello Chris,

Forgot all things. Now, let me know how app geofencing actually working?. and if it is working fine then please provide me actual code or demo project that is using geofencing in app and also working. so, i can implement that functionality in my android and iOS app. but, first please provide me the actual code that really working in android app. 

I think i wasted so much time and money for geofencing that is not working and no one is able to give proper solution. I think there are no technical guys to response client on time.

For response in GitHub communication I have to wait for many hours or days. here it totally time waste of mine. so, kindly give me access to slack as you promise in premium membership, I paid for premium membership.

**Comment by christocracy** [comment]
1.  Listen to the `onGeofence` event.

BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(getApplicationContext(), getIntent());

bgGeo.onGeofence(new TSGeofenceCallback() {
    @Override
    public void onGeofence(GeofenceEvent event) {
        TSLocation tsLocation = event.getLocation();
        Location location = tsLocation.getLocation();
        TSGeofence tsGeofence = event.getGeofence();
        GeofencingEvent geofencingEvent = event.getGeofencingEvent();
        
        Log.i(TAG, "[geofence] " + event.toJson());
    }
});

2.  Create a Geofence instance.
```java
TSGeofence geofence = new TSGeofence.Builder()
                        .setIdentifier("Office")
                        .setLatitude(21.237357)
                        .setLongitude(72.877497)
                        .setRadius(10)
                        .setNotifyOnEntry(true)
                        .setNotifyOnExit(true)
                        .setExtras(extras)
                        .build();

bgGeo.addGeofence(geofence);

                

// You may optionally supply a TSCallback to be notified of insert errors
                bgGeo.addGeofence(geofence, new TSCallback() {
                    @Override
                    public void onSuccess() {
                        Log.i(TAG, "[addGeofence] success");
                        Toast.makeText(MainActivity.this, "You'r in geofence", Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void onFailure(String error) {
                        Log.i(TAG, "[addGeofence] FAILURE: " + error);
                        Toast.makeText(MainActivity.this, "You'r out of geofence", Toast.LENGTH_LONG).show();
                    }
                });
```

3.  **Start monitoring** the geofence with `#addGeofence`.

```java
bgGeo.addGeofence(geofence, new TSCallback() {
                    @Override
                    public void onSuccess() {
                        Log.i(TAG, "[addGeofence] success");
                        Toast.makeText(MainActivity.this, "You'r in geofence", Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void onFailure(String error) {
                        Log.i(TAG, "[addGeofence] FAILURE: " + error);
                        Toast.makeText(MainActivity.this, "You'r out of geofence", Toast.LENGTH_LONG).show();
                    }
                });
```

3.  *Listen* for geofence events.
