### ISSUE TITLE
Issue on Geofence Tracking in iOS Native sdk when the App is terminated completely

### ISSUE THREAD

**Issue by mxnmike** [transistorsoft/background-geolocation-lt#34]
## Your Environment
* Plugin version: 0.2.0
* Platform: iOS
* OS version: 12.1
* Device manufacturer / model: Apple
* Plugin config

self.config = TSConfig.sharedInstance()
		self.config?.update({ (builder) in
			builder?.debug = true
			builder?.logLevel = tsLogLevelDebug
			builder?.desiredAccuracy = kCLLocationAccuracyBest
			builder?.locationAuthorizationRequest = "Always"
			builder?.distanceFilter = 10
			builder?.stationaryRadius = 10
			builder?.desiredOdometerAccuracy = CLLocationAccuracy(exactly: 100)!
			builder?.geofenceProximityRadius = CLLocationDistance(exactly: 1000)!
			builder?.stopOnTerminate = false
			builder?.startOnBoot = true
			builder?.geofenceInitialTriggerEntry = true
		})
		

## Expected Behavior
When I terminate the app, I should still trigger the onGeofence method and create my notification and report to my server.... this is my code....

self.bgGeo?.onGeofence({ (event) in
					print("onGeofence: \(String(describing: event))")
					if let event = event {
						if event.action == "ENTER" {
							print("Entered Geofence:\(String(describing: event.geofence.identifier))")
							self.createNotification(action: event.action, place: event.geofence)
							self._interactor.registerEntry(place: event.geofence, date: Date())
							
							#if DEBUG_VERSION
								self._eventDescriptionPublisher.onNext("EnterGeofence: \(String(describing: event.geofence.identifier))")
							#endif
							
						} else {
							print("Exited Geofence:\(String(describing: event.geofence.identifier))")
							self._interactor.registerExit(place: event.geofence, date: Date())
							
							self.createNotification(action: event.action, place: event.geofence)
							#if DEBUG_VERSION
								self._eventDescriptionPublisher.onNext("ExitGeofence: \(String(describing: event.geofence.identifier))")
							#endif
							
						}
					}
				})

## Actual Behavior
It never calls the onGeofence method, what is unclear on the documentation is if I should use the Apple's CoreLocation API Delegate methods (like didEnterRegion/didExitRegion) to detect the entry/exit methods when the app is terminated

## Steps to Reproduce
1.-  I open my app, login with my user, get the user's beacons and geofences, setup and start monitoring the geofences and beacons.
2.- Terminate the app.
3.- Walk into a Geofence

## Context
What im trying to do is with the app NOT running,  detect and report to my server which geofence the user entered/exited and based on that information do execute some logic on the backend.

## Debug logs

When I tried to email the logs I get this error for this code....

self.bgGeo?.emailLog("mxnmike@me.com", success: {
						NSLog("Log Emailed")
					}, failure: { (error) in
						NSLog("Log emailed failed: %@", error!)
					})
 The TSDatabase <TSDatabase: 0x28041afd0> is currently in use.
‼️-[TSLog emailLog:viewController:success:failure:] ROOT_VIEW_CONTROLLER_NOT_FOUND

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

I don't know why, is giving me this "instructions" if is set to "Always" in my initial config and in my app settings is set to Always the location.

2018-12-07 12:04:27.438206-0800 ActiveFit[1969:522738] - Log: 2018-12-06 17:56:41.418 ℹ️-[TSLocationManager init] {
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    elasticityMultiplier = 1;
    enabled = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    isFirstBoot = 1;
    isMoving = 0;
    lastLocationAuthorizationStatus = 0;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsB

**Comment by christocracy** [comment]
What is the radius of you geofence? 

You can fetch the logs with `#getLog` method.

**Comment by christocracy** [comment]
> what is unclear on the documentation is if I should use the Apple's CoreLocation API Delegate methods (like didEnterRegion/didExitRegion) to detect the entry/exit methods when the app is terminated

No.

**Comment by mxnmike** [comment]
> What is the radius of your geofence

The Radius of the geofences im trying to catch varies from 10 meters to 500 meters
> 
> You can fetch the logs with `#getLog` method.

I did. use that method, I paste them in the issue description, both errors

**Comment by christocracy** [comment]
The minimum reliable radius is `200` meters.

**Comment by christocracy** [comment]
You can test this in the simulator.

Geofences are handled purely by the OS.  When an iOS app has registered a geofence, that geofence is monitored forever.  If a geofence is triggered while an iOS app is terminated, iOS will re-launch that app in the background to service that event.

Make sure your app is calling the SDK's `#ready` event when your app is re-launched in the background (and make sure your `onGeofence` event-handler is registered.

**Comment by christocracy** [comment]
and provide the result of `#getLog`.  The SDK stores 3 days worth of logs by default.

**Comment by mxnmike** [comment]
> You can test this in the simulator.
> 
> Geofences are handled purely by the OS. When an iOS app has registered a geofence, that geofence is monitored forever. If a geofence is triggered while an iOS app is terminated, iOS will re-launch that app in the background to service that event.
> 
> Make sure your app is calling the SDK's `#ready` event when your app is re-launched in the background (and make sure your `onGeofence` event-handler is registered.

I added this extra line as you suggested, the background fetch call was already there as you instructed in your documentation...

`func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

let fetchManager = TSBackgroundFetch.sharedInstance()		
		fetchManager?.perform(completionHandler: completionHandler, applicationState: application.applicationState)
		TSLocationManager.sharedInstance()?.ready()



##Regarding the log...

This is everything the log returns, nothing else, it looks like its cut, but don't know how to get it all.

(lldb) print log
(String?) $R0 = "2018-12-06 17:56:41.418 ℹ️-[TSLocationManager init] {\n    activityRecognitionInterval = 10000;\n    activityType = 1;\n    autoSync = 1;\n    autoSyncThreshold = 0;\n    batchSync = 0;\n    debug = 1;\n    desiredAccuracy = \"-1\";\n    desiredOdometerAccuracy = 100;\n    disableElasticity = 0;\n    disableLocationAuthorizationAlert = 0;\n    disableMotionActivityUpdates = 0;\n    disableStopDetection = 0;\n    distanceFilter = 10;\n    elasticityMultiplier = 1;\n    enabled = 0;\n    extras =     {\n    };\n    geofenceInitialTriggerEntry = 1;\n    geofenceProximityRadius = 1000;\n    geofenceTemplate = \"\";\n    headers =     {\n    };\n    heartbeatInterval = 60;\n    httpRootProperty = location;\n    httpTimeout = 60000;\n    isFirstBoot = 1;\n    isMoving = 0;\n    lastLocationAuthorizationStatus = 0;\n    locationAuthorizationAlert =     {\n        cancelButton = Cancel;\n        instructions = \"To use background location, you must enable \'{locationAuthorizationRequest}\' in the Location Services settings\";\n        settingsButton = Sett"...
2018-12-07 12:43:15.974727-0800 ActiveFit[2024:535702] - Log: 2018-12-06 17:56:41.418 ℹ️-[TSLocationManager init] {
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    elasticityMultiplier = 1;
    enabled = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    isFirstBoot = 1;
    isMoving = 0;
    lastLocationAuthorizationStatus = 0;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsB
<UNNotificationContent: 0x280a45440; title: , subtitle: (null), body: 📢ENTER Geofence: 68175, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null),
🔵-[TSGeofenceManager evaluateProximity:delay:]_block_invoke Re-evaluation timer fired
2018-12-07 12:43:15.988291-0800 ActiveFit[2024:537794] 🔵-[TSGeofenceManager evaluateProximity:delay:]_block_invoke Re-evaluation timer fired
2018-12-07 12:43:15.992091-0800 ActiveFit[2024:537683] ✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 64 OF (
    64
)
✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 64 OF (
    64
)
2018-12-07 12:43:24.068339-0800 ActiveFit[2024:535702] - Log: 2018-12-06 17:56:41.418 ℹ️-[TSLocationManager init] {
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    elasticityMultiplier = 1;
    enabled = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    isFirstBoot = 1;
    isMoving = 0;
    lastLocationAuthorizationStatus = 0;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsB

**Comment by mxnmike** [comment]
Hi, any news on this issue Chris?
Thanks

**Comment by christocracy** [comment]
No.  I await your full logs.  You might also post your code you’re using with the plugin.

**Comment by mxnmike** [comment]
The full logs is there, that is what I get when I do either print or NSLog to the log variable inside the getLog callback method, it looks like is information missing, but that's all I get... Any ideas of why I just get that little of log?

### **Code** 
**Initial setup**
```
private func initialSetup() {
		self.createTriggers { (_, _) in
			print("Create Triggers Complete")
		}
		self.config = TSConfig.sharedInstance()
		self.config?.update({ (builder) in
			builder?.debug = true
			builder?.logLevel = tsLogLevelDebug
			builder?.desiredAccuracy = kCLLocationAccuracyBest
			builder?.locationAuthorizationRequest = "Always"
			builder?.distanceFilter = 10
			builder?.stationaryRadius = 10
			builder?.desiredOdometerAccuracy = CLLocationAccuracy(exactly: 100)!
			builder?.geofenceProximityRadius = CLLocationDistance(exactly: 1000)!
			builder?.stopOnTerminate = false
			builder?.startOnBoot = true
			builder?.geofenceInitialTriggerEntry = true
		})
		
	}
```

**Geofence Setup**	
```
	private func createTriggers(for club: ClubInfoModel) {
		var beacon = [String: Any]()
		beacon["beaconFactoryId"] = club.beaconFactoryIdentifier
		beacon["uuid"] = club.beaconUUID
		beacon["major"] = club.beaconMajor
		beacon["minor"] = club.beaconMinor
		beacon["deviceId"] = club.beaconDeviceId
		self.beaconDictionaryArray.append(beacon)
		
		if let geofence = TSGeofence(identifier: club.locationId,
								  radius: CLLocationDistance(exactly: club.radius!)!,
								  latitude: CLLocationDegrees(exactly: club.lat)!,
								  longitude: CLLocationDegrees(exactly: club.lng)!,
								  notifyOnEntry: club.notifyOnEntry ?? true,
								  notifyOnExit: club.notifyOnExit ?? true,
								  notifyOnDwell: club.notifyOnDwell ?? false,
								  loiteringDelay: club.loiteringDelay ?? 0.0) {
			
			self.geofenceArray.append(geofence)
		}
	}
```

**Start Monitoring**

```	private func enableGeofencing() {
		self.bgGeo = TSLocationManager.sharedInstance()

		self.bgGeo?.addGeofences(self.geofenceArray, success: {
			if !self.config!.enabled {
				self.bgGeo?.ready()
				DispatchQueue.main.async {
					self.bgGeo?.startGeofences()
				}
				
				self.bgGeo?.onGeofence({ (event) in
					print("onGeofence: \(String(describing: event))")
					if let event = event {
						if event.action == "ENTER" {
							print("Entered Geofence:\(String(describing: event.geofence.identifier))")
							self.createNotification(action: event.action, place: event.geofence)
							self._interactor.registerEntry(place: event.geofence, date: Date())
							
							#if DEBUG_VERSION
								self._eventDescriptionPublisher.onNext("EnterGeofence: \(String(describing: event.geofence.identifier))")
							#endif
							
						} else {
							print("Exited Geofence:\(String(describing: event.geofence.identifier))")
							self._interactor.registerExit(place: event.geofence, date: Date())
							
							self.createNotification(action: event.action, place: event.geofence)
							#if DEBUG_VERSION
								self._eventDescriptionPublisher.onNext("ExitGeofence: \(String(describing: event.geofence.identifier))")
							#endif
							
						}
					}
					self.bgGeo?.getLog({ (log) in
						NSLog("- Log: %@", log!)
					}, failure: { (error) in
						NSLog("Log failed:", error!)
					})
			}
		}, failure: { (error) in
			#if DEBUG_VERSION
				self._eventDescriptionPublisher.onNext("Not able to add geofences")
			#endif
		})
	}
```

**Comment by christocracy** [comment]
The plugin holds 3 days worth of logs.  That’s several megabytes, not the couple of hundred bytes you’ve posted above.

**Comment by mxnmike** [comment]
> The plugin holds 3 days worth of logs. That’s several megabytes, not the couple of hundred bytes you’ve posted above.

Any Idea why is just returning that so?

**Comment by mxnmike** [comment]
> The plugin holds 3 days worth of logs. That’s several megabytes, not the couple of hundred bytes you’ve posted above.

Look, is a breakpoint print

```
**(lldb) print log**
(String?) $R0 = "2018-12-06 17:56:41.418 ℹ️-[TSLocationManager init] {\n activityRecognitionInterval = 10000;\n activityType = 1;\n autoSync = 1;\n autoSyncThreshold = 0;\n batchSync = 0;\n debug = 1;\n desiredAccuracy = "-1";\n desiredOdometerAccuracy = 100;\n disableElasticity = 0;\n disableLocationAuthorizationAlert = 0;\n disableMotionActivityUpdates = 0;\n disableStopDetection = 0;\n distanceFilter = 10;\n elasticityMultiplier = 1;\n enabled = 0;\n extras = {\n };\n geofenceInitialTriggerEntry = 1;\n geofenceProximityRadius = 1000;\n geofenceTemplate = "";\n headers = {\n };\n heartbeatInterval = 60;\n httpRootProperty = location;\n httpTimeout = 60000;\n isFirstBoot = 1;\n isMoving = 0;\n lastLocationAuthorizationStatus = 0;\n locationAuthorizationAlert = {\n cancelButton = Cancel;\n instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";\n settingsButton = Sett"...
2018-12-07 12:43:15.974727-0800 ActiveFit[2024:535702] - Log: 2018-12-06 17:56:41.418 ℹ️-[TSLocationManager init] {
activityRecognitionInterval = 10000;
activityType = 1;
autoSync = 1;
autoSyncThreshold = 0;
batchSync = 0;
debug = 1;
desiredAccuracy = "-1";
desiredOdometerAccuracy = 100;
disableElasticity = 0;
disableLocationAuthorizationAlert = 0;
disableMotionActivityUpdates = 0;
disableStopDetection = 0;
distanceFilter = 10;
elasticityMultiplier = 1;
enabled = 0;
extras = {
};
geofenceInitialTriggerEntry = 1;
geofenceProximityRadius = 1000;
geofenceTemplate = "";
headers = {
};
heartbeatInterval = 60;
httpRootProperty = location;
httpTimeout = 60000;
isFirstBoot = 1;
isMoving = 0;
lastLocationAuthorizationStatus = 0;
locationAuthorizationAlert = {
cancelButton = Cancel;
instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
settingsB

```

**Comment by christocracy** [comment]
And what is the `length` of that NSString you’re NSLogging?

**Comment by mxnmike** [comment]
> And what is the `length` of that NSString you’re NSLogging?

I followed your instructions to print the logs, so Is the one your method is returning in the call back

```
					self.bgGeo?.getLog({ (log) in
						NSLog("- Log: %@", log!)
					}, failure: { (error) in
						NSLog("Log failed:", error!)
					})
```

**Comment by mxnmike** [comment]
Hey Chris, I was unable to get the logs properly, so I kept trying, I have set the bgGeo.ready(), if I enable the debug option, I get the local notifications that the plugin sends when I entry and exit the geofence, the problem I have created my own local notification inside the method that I normally detect the enter/exit event, and is not getting fired.... my question is, should I do all the configuration process again in the AppDelegate just for when the app is terminated??
