### ISSUE TITLE
How to get Speed

### ISSUE THREAD

**Issue by StevenStarz** [transistorsoft/background-geolocation-lt#36]
Hello, i have a run tracker app, that user can start, pause, and stop their running tracker, like Strava App (and the other running tracker app), i already got the distance, but I don't know how to get speed, is it this library providing that, or I need to calculate it manually ?

if I can get the speed from this library, how can I achieve that?

**Comment by christocracy** [comment]
- iOS see [`TSLocation`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-iOS.md#tslocation).  It contains a reference to the `CLLocation` object which contains the speed.
- Android: See [`TSLocation#getLocation`](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md#tslocation).  Returns a reference to the Android `Location` instance.

And of course `speed` is only available when the location came from GPS.  If you're indoors (where location likely came from Wifi, there is **no speed**.

**Comment by StevenStarz** [comment]
@christocracy Ok, I found it, but when I try to simulate walking, the speed value is always -1?

**Comment by StevenStarz** [comment]
I simulation using custom gpx, Here is my custom gpx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx
    xmlns="http://www.topografix.com/GPX/1/1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"
    version="1.1"
    creator="gpx-poi.com">
    <wpt lat="34.418488" lon="-118.564748">
        <time>2016-08-11T06:36:10Z</time>
    </wpt>
    <wpt lat="34.418488" lon="-118.564748">
        <time>2016-08-11T06:36:20Z</time>
    </wpt>
    <wpt lat="34.418304" lon="-118.564178">
        <time>2016-08-11T06:36:30Z</time>
    </wpt>
    <wpt lat="34.418113" lon="-118.563585">
        <time>2016-08-11T06:36:40Z</time>
    </wpt>
    <wpt lat="34.418232" lon="-118.561691">
        <time>2016-08-11T06:36:50Z</time>
    </wpt>
    <wpt lat="34.418272" lon="-118.563601">
        <time>2016-08-11T06:37:00Z</time>
    </wpt>
    <wpt lat="34.418488" lon="-118.564748">
        <time>2016-08-11T06:37:10Z</time>
    </wpt>
</gpx>

**Comment by StevenStarz** [comment]
@christocracy ok hahahah

**Comment by StevenStarz** [comment]
@christocracy one thing again, now I can get the speed value, that means there should be a stopwatch on your library, do you provide the event listener that I can get the stopwatch? So that I can show it to the user or I need to add the stopwatch manually?

**Comment by christocracy** [comment]
Why do you think there’s a “stop watch”, there isn’t.

Speed is provided by the native location api.  The plugin has nothing to do with “calculating” speed.

**Comment by christocracy** [comment]
Then your device is not connecting to GPS.

If it’s Android, check Settings->Location->Mode.

Ensure it’s set to “High Accuracy” (not “Battery Saving”, which disables gps)

Also ensure you configured plugin’s desiredAccuracy for DESIRED_ACCURACY_HIGH

**Comment by StevenStarz** [comment]
Btw, I'm developing on ios device, is it same with kCLLocationAccuracyBestForNavigation ?

**Comment by StevenStarz** [comment]
Here is my config 
```
config.update({ builder in
            // Debug config
            builder?.debug = true
            builder?.logLevel = TSLogLevel(rawValue: 5)
            // Geolocation Config
            builder?.desiredAccuracy = kCLLocationAccuracyBestForNavigation
            builder?.distanceFilter = 20
            builder?.stopTimeout = 1
            // HTTP Config
            builder?.url = "http://tracker.transistorsoft.com/locations/\(username)"
            builder?.params = ["device": self.getDeviceInfo()]
            // Application Config
            builder?.stopOnTerminate = true
            builder?.startOnBoot = false
        })
```

**Comment by christocracy** [comment]
>Btw, I'm developing on ios device, is it same with kCLLocationAccuracyBestForNavigation ?

Yes, that’s all you can do.  Everything else is up to iOS to return locations from GPS where available.
