### ISSUE TITLE
Android 9/Pie - "Geofencing Event: ENTER" event onGeofence is never fired.

### ISSUE THREAD

**Issue by jsfunfun** [transistorsoft/background-geolocation-lt#37]
Chris, we determined that TS lib native Android does not work for Android 9. The "Geofencing Event: ENTER" is never fired.

Your Main Activity never exercised the geo-fence features of TS so we made a simple fence-only version of your sample app. See steps to reproduce.

In summary, you will find that this simplified app works for Android 7 and 8, but fails for Android 9. 

In particular: 

**For Android 7 one gets the events:**
	TSGeofenceManager found 1/1 within 1000 meters
	Geofencing Event: ENTER
	onGeofence is called
	Geofencing Event: DWELL ...
    
**For Android 8 one gets the events:**
	TSGeofenceManager found 1/1 within 1000 meters
	Geofencing Event: ENTER
	onGeofence is called    
	Geofencing Event: DWELL ...
    
**For Android 9 one gets the events:**
	TSGeofenceManager found 1/1 within 1000 meters
	(and no other events are triggered)
	
	Nothing has changed yet we get no ENTER, EXIT or DWELL events.
	onGeofence is NEVER called

## Your Environment: Android 7, 8, 9
* Plugin version: 2.14.2
* Platform: iOS or Android: Android
* OS version: 7, 8, 9
* Device manufacturer / model: Nexus, HUAWEI, Emulators;
* Plugin config:

.setDebug(true)
.setLogLevel(5)
.setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
.setDistanceFilter(50f)
.setForegroundService(true)
.setStopOnTerminate(false)
.setStartOnBoot(false)
.setHeartbeatInterval(60)
.setGeofenceInitialTriggerEntry(true)
.setGeofenceProximityRadius(1000L)
.commit();

## Expected Behavior
onGeofence should be triggered.

## Actual Behavior
on Android 7 & 8 it works, on 9 onGeofence is never called.

## Steps to Reproduce
Please take the MainActivity.java from background-geolocation-lt-master and replace it with the simplified version I provide herein as an attachment so you can run this example and confirm the issue.

[MainActivity.java.zip](https://github.com/transistorsoft/background-geolocation-lt/files/2887587/MainActivity.java.zip)

## Context
make an app that responds to the geo fence points.

## Debug logs

ANDROID 8 LOGS:
[android-8-logs.txt](https://github.com/transistorsoft/background-geolocation-lt/files/2887599/android-8-logs.txt)

ANDROID 9 LOGS:
[android-9-logs.txt](https://github.com/transistorsoft/background-geolocation-lt/files/2887598/android-9-logs.txt)

Could you kindly let us know what to do about this issue. Please let me know what other information you need.

Thanks Chris !

-Joe

**Comment by christocracy** [comment]
I develop primarily on a PIxel @ 9.0.0 and I have no issues.

**Comment by christocracy** [comment]
Have you seen https://dontkillmyapp.com/?

**Comment by jsfunfun** [comment]
Please take a look at the sample -did you actually test the firing of a single GeoFence point as the only activated feature of the TS lib? Or did you test location tracking with your Pixel 9.0.0.?

**Comment by christocracy** [comment]
Testing in emulators is problematic.  

I test geofences just about every day for the last 3 years.  geofences-only & location-tracking + geofences.  They always fire.
