### ISSUE TITLE
android.app.RemoteServiceException

### ISSUE THREAD

**Issue by aksonov** [transistorsoft/background-geolocation-lt#40]
We got it during start of RNBGL. Btw, we ordered only one license, but have two build variants - for testing server and for production, could it be the reason?

```
android.app.RemoteServiceException Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8dbbda1 u0 com.hippware.android.tinyrobot.staging/com.transistorsoft.locationmanager.BackgroundGeolocationService} 
    ActivityThread.java:1745 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:193 android.os.Looper.loop
    ActivityThread.java:6718 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:493 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:858 com.android.internal.os.ZygoteInit.main
```

**Comment by christocracy** [comment]
This is not the RN repo, it’s the pure native version.

**Comment by mobiRic** [comment]
Looks like a duplicate of https://github.com/transistorsoft/background-geolocation-lt/issues/63, found on a pure Android native app, which has still not been resolved.

**Comment by christocracy** [comment]
@mobiRic use [StrictMode](https://developer.android.com/reference/android/os/StrictMode) to determine which code in your app is blocking the main thread, *preventing* BackgroundGeolocation sdk from executing `startForeground` in time.

**Comment by mobiRic** [comment]
Thanks @christocracy I am part of the team that the other linked issue relates to. Just linking to the other issue in case the @aksonov gets any use out of the discussion on that other issue.

And in case you and we are able to resolve that other issue, which as you know, we have tried all these things, including strict mode etc. I believe you and Ngoni have been in discussion, and our team has been following all your advice so far without getting to the bottom of it.
