### ISSUE TITLE
IOS config not working in ionic4

### ISSUE THREAD

**Issue by BaskaranRamamoorthy** [transistorsoft/background-geolocation-lt#41]
this is my config   

config: {
    distanceFilter: 0,
    disableElasticity: true,
    activityRecognitionInterval: 5000,
    stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when app terminated.
    startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    batchSync: false,       // <-- Set true to sync locations to server in a single HTTP request.
    autoSync: true,         // <-- Set true to sync each location to server as it arrives.
    method: 'POST',
    url: HttpConfig.url + '/locations',
    httpRootProperty: 'locations',
    locationTemplate: [{latitude: `<%= latitude %>`,
                        longitude: `<%= longitude %>`,
                        speed: `<%= speed %>`,
                        accuracy: `<%= accuracy %>`,
                        heading: `<%= heading %>`,
                        altitude: `<%= altitude %>`,
                        altitudeAccuracy: `<%= accuracy %>`,
                        batteryLevel: 10,
                        batteryCharging: true }],
    headers: { Authorization: 'Bearer ' + '' },
    locationAuthorizationAlert: {
      titleWhenNotEnabled: 'Please enable locations for Tranzport.',
      titleWhenOff: 'Location Services are off.',
      instructions: 'Please enable \'Always\' in location-services.',
      cancelButton: 'Cancel',
      settingsButton: 'Settings'
    },
    allowIdenticalLocations: true,
    locationUpdateInterval: 5000,
    fastestLocationUpdateInterval: 5000
  }
![Screen Shot 2019-03-22 at 7 59 35 PM](https://user-images.githubusercontent.com/42064359/54832536-5d1cd000-4ce2-11e9-9ef5-df894cd7c9dd.png)

**Comment by christocracy** [comment]
Why have you **ignored the issue template** AND posted an Ionic issue into the **Native Version**?
