### ISSUE TITLE
Issue when trying to update the list of geofences in real time

### ISSUE THREAD

**Issue by mfamilariSnapp** [transistorsoft/background-geolocation-lt#42]
## Your Environment
* Plugin version: 0.2.0
* Platform: iOS
* OS version: >= 11
* Device manufacturer / model: all iPhones that support iOS 11 and higher
* Plugin config:
 ```        
debug = true
logLevel = tsLogLevelDebug
geofenceProximityRadius = 10000
stopOnTerminate = false
startOnBoot = true
geofenceInitialTriggerEntry = false
```

## Expected Behavior
Update the list of geofences in real time while the application is in background

## Actual Behavior
Infinite loop / The geofences' events were not called

## Context
Hello Chris,

For our project, we need to update the list of geofences in real time, while the application is in background, according to the areas in which the user moves.

### Our idea: 
In our Back-Office, we have defined two types of geofences, in addition to the standard ones, we have defined technical geofences, which have a greater visibility.
When they are triggered, we call our API, retrieve the geofences around the new area, remove the geofences from the previous area of the database and add the new geofences recovered.

### Our logic:
When starting the application, we call the method "addGeofences()", with the geofences of the current area.
Then the SDK is started with the "startGeofences()" method.
When the "onGeofence()" method is trigger, if the geofence is a technical one, we get the lattitude and longitude of the TSGeofence, we send these coordinates to our API which will send us a new list of geofences for this new area.
As soon as we receive the data, we call the method "removeGeofences()" to clean the database of geofences from the previous area, and we recall the method "addGeofences()" to add the geofences of the new area.

### Pseudo code:
```swift
    private let config = TSConfig.sharedInstance()
    private let bgGeo = TSLocationManager.sharedInstance()

    override func viewDidLoad() {
        super.viewDidLoad()

        self.config?.update({ builder in
            builder?.debug = true
            builder?.logLevel = tsLogLevelDebug
            builder?.geofenceProximityRadius = 10000
            builder?.stopOnTerminate = false
            builder?.startOnBoot = true
            builder?.geofenceInitialTriggerEntry = false
        })
        
        self.addGeofences()
        
        self.onGeofence()
        
        self.bgGeo?.ready()
        
        self.bgGeo?.startGeofences()
    }

    private func addGeofences() {
        // Remove old geofences from previous area
        self.bgGeo?.removeGeofences()
        // Add new geofences from new area
        self.bgGeo?.addGeofences()
    }

    private func onGeofence() {
        self.bgGeo?.onGeofence() {
            if (techincalGeofence) {
                // Call addGeofences() method with list of geofences of the new area
                self.addGeofences()
            }
        }
    }
```

### Result:
We have found an undefined behaviour, it seems that the "addGeofences()" method, when called while the SDK is running, recalls the "onGeofence()" one.
Which, if "geofenceInitialTriggerEntry" is set to true, gives us an infinite loop: "addGeofences()" -> "onGeofence()" -> if (technical geofence) -> "addGeofences()" etc.
By setting "geofenceInitialTriggerEntry" to false, there is no longer an infinite loop, but according to our tests, it does not always work as expected.

One explanation would be that the "addGeofences()" and "removeGeofences()" methods are not designed to be called once the SDK is started, but beforehand during configuration.

If this hypothesis is verified, how can we update our list of geofences in real time while the SDK is running?
Should the SDK be stopped before calling "addGeofences()" method (in onGeofence() one), and restarted once the new geofences have been added to the database?
Are there other methods to update the list of geofences once the SDK has started?

**Comment by christocracy** [comment]
Don’t addGeofenes in #onGeofemce listener.

Why are you doing that?  The plugin allows you to add infinite geofences.  Add them all at once.

**Comment by mfamilariSnapp** [comment]
Thank you for the quick answer

This is because we receive new geofences every day from our partners
And we would like the SDK to support them without opening the application

**Comment by christocracy** [comment]
Why don’t you send the new geofences to the plugin via server push?

**Comment by mfamilariSnapp** [comment]
I'm not sure I understand

**Comment by christocracy** [comment]
What don't you understand?  You don't understand what a ["server push request"](https://www.quora.com/What-is-the-best-way-to-push-real-time-data-to-a-mobile-app-from-a-backend) is?

**Comment by mfamilariSnapp** [comment]
I don't really understand, are you talking about Push Notification Services and Silent Push Solution to trigger the geofence's list update ?

**Comment by christocracy** [comment]
I'm talking about sending a "silent push" notification from your server to the device that needs new geofences, yes.

**Comment by mfamilariSnapp** [comment]
Ok I understand, we will try this solution, thank you.

One last question, can I call "removeGeofences()" method just before calling "addGeofences()" one ?
Does the SDK handle this situation ?

**Comment by christocracy** [comment]
Call `addGeofences` in the callback to `removeGeofences`

**Comment by mfamilariSnapp** [comment]
Thanks
