### ISSUE TITLE
Android- Not update location

### ISSUE THREAD

**Issue by sopheakn** [transistorsoft/background-geolocation-lt#43]
## Your Environment
* Plugin version: last version
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Plugin config
                .setDebug(false)
                .setLogLevel(0)
                .setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
                .setDistanceFilter(15F) // min dist in meters
                .setElasticityMultiplier(0.5F)
                .setMinimumActivityRecognitionConfidence(50)
                .setStopOnTerminate(false)
                .setForegroundService(true)
                .setStopTimeout(10L)
                .setAllowIdenticalLocations(true)
                .setStartOnBoot(true) 

After I stay on one place long time and than I move to some place, Location is not update. Maybe 2 km or more just location update. Do you have solution please help.

**Comment by IanMcGhie** [comment]
Enable debugging & send your logs.
