### ISSUE TITLE
Android - is there a method for Last Known Location?

### ISSUE THREAD

**Issue by mobiRic** [transistorsoft/background-geolocation-lt#44]
Is there a method on the TransistorSoft Android SDK to query synchronously for the last known location of the device?

i.e. Analogous to `LocationManager.getLastKnownLocation(String)` which can be called before starting the provider.

I would like to know the last location on the device with immediate feedback upon starting background tracking. I'm quite happy to write those couple of lines in my own codebase if I'm not duplicating an existing TransistorSoft method.

## Your Environment
* Platform: Android

**Comment by christocracy** [comment]
Use `#getCurrentPosition`.  provide `setMaximumAge > 0` to [TSCurrentPositionRequest.Builder](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-Android.md#tscurrentpositionrequestbuilder)
