### ISSUE TITLE
background-geolocation-lt is failing on initial install

### ISSUE THREAD

**Issue by liveaffiliates** [transistorsoft/background-geolocation-lt#46]
Hi,

I was wanting to use this library in some flutter apps but can't get it even installed. This is the sequence of events:

1. I generate a new flutter project (the default flutter project, no extra code added or changes made) then run the project in an emulator and it works.

2. I add flutter_background_geolocation: ^1.0.5 to the pubspec.yaml and get the following error:

`Error:
	Attribute application@label value=(geolocationapp) from AndroidManifest.xml:11:9-39
	is also present at [:flutter_background_geolocation] AndroidManifest.xml:7:18-50 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:9:5-32:19 to override.` 

3. I then try and fix that error by adding: 

tools:replace="android:label" 
and 
xmlns:tools="http://schemas.android.com/tools"

in my android manifest like this:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.roboticc.geolocationapp"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"
        android:label="geolocationapp"
        android:icon="@mipmap/ic_launcher">`

4. Now the error goes away and the app runs but immediately crashes with no error messge.

I have seen you had this same problem implementing this with React Native and the answer was never completely resolved. They came up with it being a part of the camera library but it is clearly more than that considering it is failing as soon as the plugin is added.

Thanks

**Comment by christocracy** [comment]
Wrong repo.  Flutter version is here:
https://github.com/transistorsoft/flutter_background_geolocation/graphs/traffic

**Comment by liveaffiliates** [comment]
Thanks
