### ISSUE TITLE
Server side location json values become null

### ISSUE THREAD

**Issue by bhavesh350** [transistorsoft/background-geolocation-lt#49]
## Android Studio
* Plugin version: 0.2.0
* Platform: Android
* OS version: All android version
* Device manufacturer / model: All
* Plugin config 

## Expected Behavior
Json formed by the new location capture from the plugin, is all fine and well formed Json we are getting on app side, that we can see into log 
it's the json capture at app side
```
{

  "event": "motionchange",

  "is_moving": false,

  "uuid": "eb008781-d633-4dd2-85f8-317d894769eb",

  "timestamp": "2019-05-10T07:55:25.197Z",

  "odometer": 0,

  "coords": {

    "latitude": 26.8339167,

    "longitude": 75.8026677,

    "accuracy": 16,

    "speed": -1,

    "heading": -1,

    "altitude": -1

  },

  "activity": {

    "type": "still",

    "confidence": 100

  },

  "battery": {

    "is_charging": true,

    "level": 1

  },

  "extras": {

    "user_id": "7126",

    "device_id": "358967062539380"

  }

}
```

That is all perfect
and servers side also it should get this json 

## Actual Behavior
But what server side it's capturing is like

LOCATION DATA SYNCED TO HTTP URL

{"event":null,"is_moving":false,"uuid":null,"timestamp":"0001-01-01T00:00:00","odometer":0,"coords":null,"activity":null,"battery":null,"extras":null}
Here we can see all values are null or blank

## Steps to Reproduce
Opening app is capturing location in json format data. 

## Context
We are trying to post it on server, but server side it's getting all null values.

## Debug logs
Mentioned in expected behavior

So please help us to make it all fine at server end as well to save data.

**Comment by christocracy** [comment]
You are likely observing the default data from an empty-model on your server because you're not actually *finding* the actual JSON posted to the server.

Are you using php on your server?  What *are* you using on the server?  The data is posted in the *JSON body of the Request*.  PHP often fail at this because they expect the data to exist in `$_POST`.

**Comment by bhavesh350** [comment]
sever side we are using .net. and the same request we are trying with postman and everything is working fine. So server side code is not picking up only default value, but picking whatever we are posting it.
![image](https://user-images.githubusercontent.com/23273844/58243238-e5b0fe80-7d6d-11e9-87b5-53a0181557c1.png)
and with response you can see
![image](https://user-images.githubusercontent.com/23273844/58243279-f9f4fb80-7d6d-11e9-8edc-bd24e184d809.png)

**Comment by christocracy** [comment]
Are you watching the plugin logs?

**Comment by LucaJeevanjee** [comment]
Have you found any fixes? I am getting the same problem
When I start my app the plugin tries to post to the server several times with the coords values being null resulting in an error
