### ISSUE TITLE
iOS not sending location updates when app is hard closed

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/background-geolocation-lt#5]
On iOS it has now reduced sending location updates when the user is not moving but the app no longer sends updates when the app is hard closed/suspended. The iOS code is on bitbucket. We also need to know the right settings to use for everything knowing our use case which is to show location updates at all times there are updates to the users location but stop when user is not moving while at work or home.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Please read the docs for [stopOnTerminate](https://github.com/transistorsoft/background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true).

After terminating the iOS app, the device must move at least 200 meters before the OS will reboot the device and tracking resumes.  This is easily verified in the simulator, as in [this video](https://youtu.be/aR6r8qV1TI8) (see 3:35)

**Comment by sunilw123** [comment]
Please advise the exact settings we need to use for our use case.

**Comment by christocracy** [comment]
For this issue, `stopOnTerminate:  NO`
