### ISSUE TITLE
Accuracy of activity detection

### ISSUE THREAD

**Issue by felistrs** [transistorsoft/background-geolocation-lt#50]
## Environment
* Plugin version: **2.14.2**
* Platform: **Android**
* OS version: **7.0.1**
* Device manufacturer / model: **Honeywell / Dolphin CT60**
* Plugin config:
```
.setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY) // the best accuracy option
.setDistanceFilter(5f) // 5 meters, 10-default
.setStationaryRadius(5) // 10 meters
.setElasticityMultiplier(0.5f) // default - 1.0f
.setActivityRecognitionInterval(0L) // in milliseconds, 10000 - default
.setTriggerActivities("in_vehicle,on_foot,running,still,walking") // activities
```

## Expected Behavior
Get activity changes close to real.

## Actual Behavior
Activity does not change well from walking to driving (often) and oposite (some times).

[Case A](https://drive.google.com/file/d/1blgMfllA65MA8_4GVKzE62rzlCHG8WiX/view?usp=sharing)
[Case B](https://drive.google.com/file/d/1aF2XNkmJkKmGlf8DCz8GqeiCi6DLPJ2-/view?usp=sharing)

## Steps to Reproduce
Drive -> Walk (2-5 minutes) -> Drive

## Context
The application uses library in the background and sends all locations and activities to bacl-end.

I played with these parameters:
* _setMinimumActivityRecognitionConfidence_ - tried different values, default (75) worked the best. Higher - bigger time to detect activity change. Smaller - many false positives.
* _setDistanceFilter_, _setLocationUpdateInterval_, _setFastestLocationUpdateInterval_ - influences the accuracy of GNSS data
* _setStationaryRadius_ - pure GNSS data if set to minimum

# **Question**

Which configuration will solve this task better?, We can increase battery consumption.
It would be great to understand capabilities, limitations and accuracy  in “activity tracking” functionality.

**Comment by christocracy** [comment]
I don't see a problem here.  The plugin depends upon the Android [ActivityRecognitionClient](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient) to be informed about the current activity.

Yes, different Android device models will perform better or worse than others, depending upon the existence and quality of the device sensors (accelerometer, gyroscope, magnetometer).  Yes, it could take several hundred meters of movement before a valid motion-activity is emitted, causing the plugin to engage location-services.

Perhaps try installing from the branch [release-3.0.0](https://github.com/transistorsoft/background-geolocation-lt/tree/release-3.0.0)
