### ISSUE TITLE
Typo in your documentation isMoving should be is_moving

### ISSUE THREAD

**Issue by sfdfklskldf** [transistorsoft/background-geolocation-lt#56]
In your documentation: https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.config.html#locationtemplate in section  locationTemplate you have following example:
`  locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"event":"<%= event %>",isMoving:<%= isMoving %>}' `
but this seems to be wrong, correct would be:
`   locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"event":"<%= event %>",isMoving:<%= is_moving %>}' `

**Comment by christocracy** [comment]
Thanks, but you're posting at the wrong Github repo.  This is the **Native Version**, not the **Cordova Version**.

https://github.com/transistorsoft/cordova-background-geolocation-lt

This plugin is available for:
- Cordova
- React Native
- Flutter
- Pure native
