### ISSUE TITLE
Cannot find module 'cordova-background-geolocation-lt'

### ISSUE THREAD

**Issue by iprimaek** [transistorsoft/background-geolocation-lt#57]
## Your Environment
* Plugin version: 3.0.8
* Platform: Android
* OS version: Windows 10
* Device manufacturer / model: Not there yet
* Plugin config

## Expected Behavior

I should be able to import the plugin.

## Actual Behavior

Can't import the plugin.

## Steps to Reproduce

1.
2.
3.
4.

## Context

I tried to follow the documentation you mentioned and implement the code.
However, in the cordova-background-geolocation.ts, when I tried to import 'BackgroundGeolocation", it seems that can't find the module while the installation has been done as the plugin is already in place.
![image](https://user-images.githubusercontent.com/38557412/62932008-ecda2c80-bdf1-11e9-9363-e75cd2ed80ab.png)

**Comment by christocracy** [comment]
Wrong repo.  This is the pure native version.
