### ISSUE TITLE
Invalid license key when I integrate with Background Geolocation Firebase Adapter

### ISSUE THREAD

**Issue by ngoni** [transistorsoft/background-geolocation-lt#58]
## Your Environment
* Plugin version: 3.0.24
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung 
* Plugin config

`

        final BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(context);
        final TSConfig config = TSConfig.getInstance(context);

        // Configure Foreground Service notification
        final TSConfig.Notification notification = buildNotification();

        // build custom fields for the API
        JSONObject params = buildHttpParams();

        // Configure the SDK:
        config.updateWithBuilder()

                // Configure Debugging
                .setDebug(
                        context.getResources().getBoolean(
                                R.bool.transistorsoft_background_geolocation_debug_mode))
                .setLogLevel(
                        context.getResources().getInteger(
                                R.integer.transistorsoft_background_geolocation_log_level))

                // Configure Geolocation
                .setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
                .setDistanceFilter(0f)
                .setDisableElasticity(true)
                .setLocationUpdateInterval(3000L)
                .setFastestLocationUpdateInterval(3000L)
                .setDeferTime(1000L)
                .setAllowIdenticalLocations(false)

                .setActivityRecognitionInterval(10L)
                .setStopOnStationary(false) // unused
                .setStopTimeout(15L) // unused
                .setDisableStopDetection(true) // unused

                // Configure Application behaviour
                .setForegroundService(true)
                .setStopOnTerminate(false)
                .setStartOnBoot(true)
                .setEnableHeadless(false)
                .setHeartbeatInterval(10)

                // Foreground Service notification
               .setNotification(notification)

                // Configure HTTP
                .setAutoSync(true)
                .setAutoSyncThreshold(0)
                .setBatchSync(true)
                .setMaxBatchSize(100)
                .setParams(params)
                .commit();

`

## Expected Behavior

1. After upgrading the native Background Geolocation library from v2.14.2 to v3.0.24 and using the new license key obtained from the dashboard (for versions 3 and above), the license key should work.

2.  Integrating the Firebase proxy adapter plugin v0.0.3 with the native Background Geolocation library (v3.0.24), I expect both license keys to work.

## Actual Behavior

1. When I run the native Background Geolocation library v3.0.24 library by itself (without the firebase adapter), the license key for the native Background Geolocation library v3.0.24 is valid

2. When I integrate the Background geolocation firebase adapter (v0.03) and the native background geolocation library v3.0.24, the license key for the native background geolocation library v3.0.24 fails, while the license key for the Background geolocation firebase adapter is valid

## Steps to Reproduce

1. Upgrade the native background geolocation plugin from v2.14.2 to v3.0.24 and add the license key for this library obtained from the dashboard (for versions 3 and above), to the Android manifest file. If you run the application at this stage, the license key is valid.
2. Add the Firebase proxy adapter plugin v0.0.3 and add the license key for this library obtained from the dashboard, to the Android manifest file. If you run the application at this stage, the native background geolocation license key fails, while that of the Firebase proxy adapter works.

## Context

I want to send my location data to Firebase, using the Firebase proxy adapter plugin (v0.0.3) and the native android Background Geolocation library (v3.0.24)

Repository Sources:
Native Background Geolocation library v3.0.24
https://github.com/transistorsoft/background-geolocation-lt/tree/release-3.0.0

Background Geolocation Firebase Adapter 
https://github.com/transistorsoft/react-native-background-geolocation-firebase

## Debug logs

![Screenshot 2019-08-16 at 12 29 49](https://user-images.githubusercontent.com/1165257/63162099-0792e800-c022-11e9-9e29-645344781538.png)

![Screenshot 2019-08-16 at 12 07 03](https://user-images.githubusercontent.com/1165257/63160577-68b8bc80-c01e-11e9-8dad-ebdd3110941f.png)

![Screenshot 2019-08-16 at 12 09 28](https://user-images.githubusercontent.com/1165257/63160725-bf25fb00-c01e-11e9-8e5b-31421a0bbe0d.png)

**Comment by christocracy** [comment]
Looking into it.

**Comment by ngoni** [comment]
@christocracy Wanted to find out if there's any update on this?

**Comment by christocracy** [comment]
I've just tested the firebase proxy in a native app and it works fine for me.

- Email me your `AndroidManifest.xml` to `info@transistorsoft.com`
- Send me the two keys you're using as well for each plugin.

**Comment by christocracy** [comment]
Btw, I just merged `1.0.0` to master (I made naming mistake in the branch `release-3.0.0`, should've been `release-1.0.0`).

There are significant improvements to both iOS and Android setup, so see the new [Setup Docs](https://github.com/transistorsoft/background-geolocation-lt#large_blue_diamond-setup-guides), including new *Cocoapods Setup for iOS*.

**Comment by christocracy** [comment]
Ok, there was a bug in the view code for the Product Dashboard.  Refresh the dashboard and you'll see v3 licenses for *Background Geolocation for Native Apps*.

**Comment by ngoni** [comment]
@christocracy we refreshed the dashboard and the license key's i'm seeing are similar to the old one's we had (the one's i sent you in an email). Also just to confirm, i'm testing this on the v3.0.24 which was release-3.0.0 and not the new changes you merged into master v1.0.0 yesterday.

**Comment by christocracy** [comment]
The AndroidManifest you sent me:
```
package="com.rapiddeploy.mobile">
```
- You are using key beginning: `43df2`.  This is the **wrong** key.
- You *should* be using the key beginning: `b4a7c`

Think of `package` like a *username* and `licence` like password.  Ask yourself:  "What is the *password* for the username `com.rapiddeploy.mobile`?

**Comment by ngoni** [comment]
Do you use the applicationId or package for validating?

**Comment by christocracy** [comment]
[`Context.getPackageName`](https://developer.android.com/reference/android/content/Context#getPackageName())

**Comment by ngoni** [comment]
Issue finally resolved. The sample project helped. Issue was with regards to how the Firebase Proxy library was being setup into the app. Had previously used same pattern as for Native Background geolocation library, but now only just loading the ".aar" file.

**Comment by christocracy** [comment]
[background-geolocation-firebase](https://github.com/transistorsoft/background-geolocation-firebase) will be ready next week for pure native projects.

**Comment by christocracy** [comment]
Ok, it was easier than I thought.  Try out my initial stab at it, released as `0.0.1`.  [background-geolocation-firebase](https://github.com/transistorsoft/background-geolocation-firebase)
