### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground():

### ISSUE THREAD

**Issue by ngoni** [transistorsoft/background-geolocation-lt#63]
## Your Environment
* Plugin version: 3.0.24 & 3.0.28
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy S8, Note9, S10, S10+
* Plugin config

        TSFirebaseProxy proxy = TSFirebaseProxy.getInstance(getApplicationContext());
        proxy.register(getApplicationContext());

        TSConfig config = TSConfig.getInstance(getApplicationContext());
        config.updateWithBuilder()
                .setDebug(true)
                .setLogLevel(5)
                .setForegroundService(true)
                .setStopOnTerminate(false)
                .commit();

        final BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(getApplicationContext());
        bgGeo.ready(new TSCallback() {
            @Override
            public void onSuccess() {
                TSLog.logger.debug("[ready] successe");
                bgGeo.start();
            }

            @Override
            public void onFailure(String s) {
                TSLog.logger.debug("[ready] FAILURE: " + s);
            }
        });

## Expected Behavior

1. The application shouldn't crash

## Actual Behavior

1. The application crashes if you follow the steps to reproduce the bug.

## Steps to Reproduce

1. Use the [referenced](https://github.com/transistorsoft/native-bggeo-foo) sample project to test. Ensure you `.setForegroundService(true)` for the config in the project.
2.  Follow this [guide](https://www.samsung.com/us/support/tip/TIP00080625/) by Samsung on adding an application to the "Sleeping Apps" list. By default inactive apps are automatically added to this list after 3days (but this can be modified)
3. Add your application to the list of "Sleeping Apps"
4. Ensure that on the devices Developer Options both these two features are enabled to view crash dialogs. 

![20190923_170736](https://user-images.githubusercontent.com/1165257/65438143-47b96780-de25-11e9-9bae-a7b38ed63ab2.jpg)

5. Force close your application
6. Launch the application (as the application is launching, shake the device. You might need to do this multiple times, till you see the application crash. Or possibly for about a minute or two.)
7. Continuously repeat Steps 5 & 6, till you get the application to crash.

## Context
Some of our users running Samsung Devices probably from Galaxy S8 onwards, experience this crash in certain instances.

I recognise that this is a well known bug for Android Developers, but it seems after discussion with fellow developers who've experienced the issue, they've managed to narrow down potential causes and a possible solution to fix it. Find below extracts on the conversations I had with them. Hopefully this can help in addressing the bug.

![Screenshot 2019-09-23 at 17 21 55](https://user-images.githubusercontent.com/1165257/65439161-06c25280-de27-11e9-889d-3e7483446d82.png)

![Screenshot 2019-09-23 at 17 22 07](https://user-images.githubusercontent.com/1165257/65439181-0e81f700-de27-11e9-9563-8be5db49c1ff.png)

![Screenshot 2019-09-23 at 17 24 09](https://user-images.githubusercontent.com/1165257/65439195-13df4180-de27-11e9-8400-bf50c6788c50.png)

## Debug logs
![Screenshot 2019-09-23 at 16 27 48](https://user-images.githubusercontent.com/1165257/65436435-6d913d00-de22-11e9-8b45-0100525ac5a2.png)

![Screenshot 2019-09-23 at 16 55 43](https://user-images.githubusercontent.com/1165257/65436860-150e6f80-de23-11e9-8660-3f816df749b5.png)

**Comment by christocracy** [comment]
Yes, I've been aware of and working on this for a couple of months with the people using the Cordova and React Native versions.  I'm aware of the Android thread you're reading and have implemented all the suggestions there, including calling `startForeground` from both `onCreate` and `onStartCommand`.

**Comment by ngoni** [comment]
@christocracy is there any timeline on we could expect similar fixes for this repo?

**Comment by christocracy** [comment]
Latest is merged to master and tagged `1.0.2`

**Comment by ngoni** [comment]
@christocracy Thanks will test it out, and give feedback later on.

**Comment by ngoni** [comment]
@christocracy i'm still experiencing a crash when i test on a Samsung Galaxy 8 (after adding the app to the "Sleeping apps" list) and follow the repo steps i'd outlined in the first post. It took me about 3-4 attempts to get the crash.

![Screenshot 2019-09-26 at 12 08 12](https://user-images.githubusercontent.com/1165257/65680557-7b7bd380-e057-11e9-9843-a894c0cdacb1.png)

**Comment by christocracy** [comment]
Are you doing anything in the SDK’s event-handlers that would tax the main thread?

**Comment by ngoni** [comment]
@christocracy I don't think so, to verify this i will test with [this](https://github.com/transistorsoft/native-bggeo-foo) sample project you created for me.

**Comment by ngoni** [comment]
@christocracy I managed to replicate the crash in the sample project. It took quite of a bit of time though, had to test while walking also.

![Screenshot 2019-09-26 at 13 00 19](https://user-images.githubusercontent.com/1165257/65687098-a589c180-e068-11e9-9a90-a582cc7952e4.png)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1165257/65687127-cf42e880-e068-11e9-9fa7-ffb3d9ec3da9.png)

**Comment by christocracy** [comment]
Can it be replicated with mock location app (I use Lockito)?

**Comment by christocracy** [comment]
And send me more logs (in text, not screenshot) with at least several minutes leading up.  Use the sdk’s #emailLog method.

**Comment by ngoni** [comment]
@christocracy I sent you an email with the Logs.

**Comment by ngoni** [comment]
> Can it be replicated with mock location app (I use Lockito)?

i've just been testing with real locations values from the device.

**Comment by christocracy** [comment]
Yes, I'm asking you:  "Can you please try reproducing with mock locations".

**Comment by christocracy** [comment]
I'm hammering my Samsung A510 @ 8.0.0 and I cannot reproduce this with Lockito.  However, I made a few tweaks.

Try installing from [branch `dev`](https://github.com/transistorsoft/background-geolocation-lt/tree/dev)

**Comment by ngoni** [comment]
Hi Chris,


I actually managed to get it to crash with Lockito (like you after a big
struggle), I will send the Logs in about two hours.

I will install the new update in the morning, and feedback promptly.

Regards,
Ngoni

**Comment by ngoni** [comment]
Hi Chris,

I've done a bit of testing on the latest update you made, using our app and
your sample project. With both of these I  can't replicate the bug anymore.
Seems to be resolved.

Regards,
Ngoni

**Comment by ngoni** [comment]
@christocracy would you be able to give me a timeline on getting a release version of the library we tested?

**Comment by ngoni** [comment]
@christocracy Hello there. Still waiting on feedback from you regarding a release version for the above.

**Comment by christocracy** [comment]
Next week

**Comment by deepanjali11** [comment]
@christocracy Any update on this issue(E TSLocationManager:   ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground())

**Comment by ngoni** [comment]
@christocracy Hey there. We are still experiencing the crash on the latest version of the library.
For now, the only "Logs" I have is below (coming from our user). I will try obtain the "Logs" from the SDK using the #emailLog method.

`android.app.ActivityThread$H.handleMessage
ActivityThread.java, line 1871
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7ab2d1a u0 com.r.b/com.transistorsoft.locationmanager.service.TrackingService}`

**Comment by dorthwein** [comment]
we're running into this as well 
```
android.app.RemoteServiceException Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d24bf2d u0 com.truckdriverpower.app/com.transistorsoft.locationmanager.service.TrackingService}      ActivityThread.java:1871 android.app.ActivityThread$H.handleMessage     Handler.java:106 android.os.Handler.dispatchMessage     Looper.java:214 android.os.Looper.loop     ActivityThread.java:7037 android.app.ActivityThread.main     Method.java:-2 java.lang.reflect.Method.invoke     RuntimeInit.java:494 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run     ZygoteInit.java:965 com.android.internal.os.ZygoteInit.main
--

```

**Comment by christocracy** [comment]
Are you using the latest release?  [CHANGELOG](https://github.com/transistorsoft/background-geolocation-lt/blob/master/CHANGELOG.md)

**Comment by ngoni** [comment]
@christocracy Yes i am
