### ISSUE TITLE
Foregroundservice killed by Huawei - debug=true is the medicine.

### ISSUE THREAD

**Issue by LarsBocons** [transistorsoft/background-geolocation-lt#64]
## Your Environment
* Plugin version: 3.2.1
* Platform: Android
* OS version: 9
* Device manufacturer / model: Huawei P20 Lite
* Plugin config:
var config = {
			desiredAccuracy: window.BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 0,
			disableElasticity: true,
			stopOnTerminate: false,
			stationaryRadius: 1,
			desiredOdometerAccuracy: 10,
			locationAuthorizationRequest: "Always",
			locationAuthorizationAlert: {
				titleWhenNotEnabled: "Lokalitetstjenester er ikke aktiveret",
				titleWhenOff: "Lokalitetstjenester er slået fra",
				instructions: "Denne app kræver at 'Altid' er valgt i lokalitetstjenester",
				cancelButton: "Fortryd",
				settingsButton: "Indtillinger"
			},
			locationUpdateInterval: 900,
			fastestLocationUpdateInterval: 900,
			allowIdenticalLocations: true,
			pausesLocationUpdatesAutomatically: false,
			disableStopDetection: true,
			minimumActivityRecognitionConfidence: 20,
			activityRecognitionInterval: 500,
			heartbeatInterval: 30,
			preventSuspend: true, 
			foregroundService: true,
			stopTimeout: 60, 
			logMaxDays: 1,
			logLevel: logLevel,
			debug: debug
		};

## Expected Behavior
App should not get killed.

## Actual Behavior
App gets killed.

## Steps to Reproduce
Just call start() with debug=false turn off the screen.

## Context
Trying to keep my app alive. Even with powermanagement preventing the screen from turning off, an incoming call will kill the app.

I have been having good result with keeping my app alive in the background on a Huawei Honor 7 lite (Android 6) but have now changed to a newer Huawei P20 Lite (Android 9). With the P20 Lite the background function is no longer stable, and it seems impossible to draw any conclusions from my tests, until it struck me that with debug=true it always worked.

So I made a simple Cordova app that does nothing but read locations using the background geolocation plugin. It is started with ”foregroundService: true” so it should survive until I call stop. However, it does not survive longer than 5-10 minutes before it is killed. With debug=true though, it survives indefinitely.
I am able to reproduce the results each time I try…debug=true keeps the app alive while debug=false does not.

I know it is often mentioned that Huawei is notorious for killing apps in the background, but this test clearly shows that it is possible to make the plugin survive. With Huawei having the 3rd biggest market share in the world, I think this shouldn’t be ignored. 

The question is: what else does the plugin do when debug=true? Is it only the sounds?
If it’s only the sounds, would it be possible to override the “got-location” sound with a silent sound, so people wan’t go mad with the phone continuously beeping ?

## Debug logs
[background-geolocation-debug-false.log](https://github.com/transistorsoft/background-geolocation-lt/files/3680218/background-geolocation-debug-false.log)

[background-geolocation-debug-true.log](https://github.com/transistorsoft/background-geolocation-lt/files/3680219/background-geolocation-debug-true.log)

**Comment by christocracy** [comment]
debug: true does nothing but play sound FX, that’s it.

I have a P20 Lite and I cannot make it work (I have debug: true).  The fault is with the OS.

As documented at http://dontkillmyapp.com:  “No developer solution”.  There is nothing I can do to make Huawei work.

**Comment by LarsBocons** [comment]
Could it be due to different config. e.g. I aquire one location per second. If I am able to keep the app alive, why shouldn't you?

Could you test my app to see if you can prevent it being killed?
Just set debug=1, klik start and move until things get going, then put the app in the background and listen to the beeps continue forever (hopefully)
[code.zip](https://github.com/transistorsoft/background-geolocation-lt/files/3680799/code.zip)

**Comment by LarsBocons** [comment]
Well, you said "debug: true does nothing but play sound FX", so I thought I would try leaving debug false and play my own sound when receiving a location.
This actually works too, so it seems that playing a sound frequently will keep the app alive.

**Comment by christocracy** [comment]
The point of this plugin is to detect when the device is moving and automatically turn location services on and begin tracking.

When the device is stationary and screen off, the plugin doesn’t record locations.  It’s supposed to work regardless if the app is terminated (where your Cordova app no longer exists) or device rebooted without having to launch the app.

This works flawlessly on 10 of my Android devices, ranging from Android 4.4.4 to latest 10.  All except Huawei.

**Comment by LarsBocons** [comment]
> When the device is stationary and screen off, the plugin doesn’t record locations.
Mine device is lying on the table beside me, ticking locations away, so that may be the intention but not reality. 

Have you tried my app? It should be easy - from your P20 Lite, click on the app.zip and then on the apk file.

**Comment by LarsBocons** [comment]
Here's a theory and it has nothing to do with the plugin: When I repeatedly play a sound without too much pause in between, the P20 thinks an music app is playing and therefore allows it to run in the background. 

If it's due to the above theory I don't know but my app now runs in the background after I implemented an 1 sec timer playing a "tick".

**Comment by christocracy** [comment]
> but my app now runs in the background after I implemented an 1 sec timer playing a "tick".

I don't understand.  While sitting stationary, the plugin isn't supposed to do anything.  Only when you move it supposed to make a sound.

**Comment by LarsBocons** [comment]
Could it be due to inacurracy of the locations (which is normally higher indoors). They differ slightly even though the device is not moving. On a map I can se location center jump a few meters now and then.

**Comment by christocracy** [comment]
btw, you know this is the *Pure Native* repo, not the [cordova-background-geolocation](https://github.com/transistorsoft/cordova-background-geolocation-lt) repo?  This plugin is available for React Native, Cordova, Flutter and Pure native apps.

**Comment by christocracy** [comment]
I suggest you try your demo app in the terminated state.

**Comment by LarsBocons** [comment]
> btw, you know this is the Pure Native repo

No, I thought is was a "General" rep, sorry.

> I suggest you try your demo app in the terminated state.

I did try it...why?

Anyway, the "sound hack" does seem to make the app run in the background, but unfortunately it will not prevent it being killed on an incomming (long) call :-( Even if I run my app in the foreground with power management preventing it going to sleep, the app is gone when I return from a (long) call...just crazy :-(

which was the most important thing for me :-(

**Comment by christocracy** [comment]
> I did try it...why?

Why do you think?  Naturally an app is operating under more constraints by the os in the terminated state and your Cordova JavaScript app no longer exists, where you’re playing with your “sound hack”.

You’ll be damned each way you turn with Huawei.  I know exactly what Huawei does: they don’t actually *ignore* these events the plugin has subscribed (eg motion-activity api, geofencing api) — they merely queue them up and run them all-at-once next time the device is unlocked.  Of course, receiving those events later in time is pointless, because those are the events which were to have trigger location-tracking in the first place.

Not even a WakeLock works to consistently receive those crucial motion api events in real-time.

Huawei is purposely crippling the background operation of Android APIs.
