### ISSUE TITLE
Question: Is it possible to filter out coordinates based on Wifi and leave only GPS coords

### ISSUE THREAD

**Issue by stefanminch** [transistorsoft/background-geolocation-lt#65]
this is more of a question ( I have bought the plugin for a second year)
Is it possible to filter out coordinates that are based on WiFi or cellular data and leave only GPS based points? Preferable on both both platforms but if not possible on Android is sufficient.

Thanks!

## Your Environment
* Plugin version: latest
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model: any
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Do you know this is the *Pure Native* repo?  Are you not using *Cordova*?
