### ISSUE TITLE
MainActivity launched when the App is in background or terminated

### ISSUE THREAD

**Issue by INDAPP** [transistorsoft/background-geolocation-lt#67]
## Your Environment
* Plugin version: 3.0.26
* Platform: Android
* OS version: 9 & 10
* Device manufacturer / model: Google Pixel 3 & OnePlus 6T
* Plugin config

        val bgGeo = BackgroundGeolocation.getInstance(applicationContext, intent)
        val config = TSConfig.getInstance(applicationContext)

        config.updateWithBuilder()
            .setDebug(false) 
            .setLogLevel(0) 
            .setDesiredAccuracy(TSConfig.DEFAULT_DESIRED_ACCURACY)
            .setDistanceFilter(10f)
            .setDisableElasticity(false)
            .setElasticityMultiplier(1f)
            .setGeofenceProximityRadius(1000L)
            .setStopAfterElapsedMinutes(0)
            .setDesiredOdometerAccuracy(100f)
            .setUseSignificantChangesOnly(false)
            .setLocationUpdateInterval(1000L)
            .setFastestLocationUpdateInterval(0L)
            .setDeferTime(0L)
            .setStopTimeout(1L)
            .setStopOnTerminate(false)
            .setStartOnBoot(true)
            .setHeartbeatInterval(60)
            .setEnableHeadless(true)
            .setForegroundService(true)
            .setHeadlessJobService("${javaClass.`package`.name}.LocationEventReceiver")
            .setAutoSync(true)
            .setAutoSyncThreshold(0)
            .setUrl("${BuildConfig.baseUrl}v2/pts/tracking/position")
            .setHeader("Authorization", "Bearer ${UserRepository.jwt}")
            .setHttpRootProperty(".")
            .setLocationTemplate("{\"lat\":<%= latitude %>,\"lng\":<%= longitude %>,\"altitude\":<%= altitude %>,\"speed\":<%= speed %>}")
            .setParams(JSONObject().apply {
                putOpt("uid", UserRepository.currentUid)
                putOpt("os", "android")
                putOpt("source", "transistorsoft")
                putOpt("brand", Build.MANUFACTURER)
                putOpt("model", Build.MODEL)
                putOpt("appVersion", BuildConfig.VERSION_NAME)
            })
            .setNotification(TSConfig.Notification().apply {
                smallIcon = "drawable/ic_launcher_foreground"
                priority = NotificationCompat.PRIORITY_DEFAULT
            })
            .commit()

        bgGeo.onLocation(object: TSLocationCallback {
            override fun onLocation(location: TSLocation) {
                Log.i("BACKGROUND_LOCATION_M", "[location] " + location.toJson())
                LocationEventReceiver.onLocationUpdate(location)
            }

            override fun onError(code: Int) {
                Log.i("BACKGROUND_LOCATION_M", "[location] ERROR: $code")
                Throwable("Background Location error: $code").log()
            }
        })

        bgGeo.ready(object: TSCallback {
            override fun onSuccess() {
                Log.i("BACKGROUND_LOCATION", "[ready] success")
                if (!config.enabled) {
                    bgGeo.start()
                }
            }
            override fun onFailure(error: String) {
                Log.i("BACKGROUND_LOCATION", "[ready] FAILURE: $error")
            }
        })

## Expected Behavior

The application shouldn't launch MainActivity from background execution

## Actual Behavior

When device is moved, sometimes MainActivity starts

## Steps to Reproduce

1. Start BackgroundGeolocation with this Config
2. Exit from application MainActivity
3. Move the device

## Debug logs

No device logs, because it happens occasionally, when the device is disconnected

**Comment by christocracy** [comment]
```
.setLogLevel(5)  // there's a const for this but I forget where it is.
```

See docs `BackgroundGeolocation.emailLog`
