### ISSUE TITLE
Headless Background location fetch not working in Xiaomi device.

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/background-geolocation-lt#68]
In xiaomi device, with background headless task configured, when the app is terminated by the user from background. The headless task is not getting invoked. This is, however, working properly in  Samsung devices.

## Your Environment
* Plugin version: It's a demo project which has the module included       
        VersionCode 1
        VersionName "0.0.1"

* Platform: Android
* OS version:  8.1.0
* Device manufacturer / model: Xiaomi - Redmi 5 Plus
* Plugin config

## Expected Behavior
The headless task should be invoked even when the app is terminated.

## Actual Behavior
The headless task is not getting invoked and when the demo app is launched again, the switch at the top is off i.e background location tracking is off.

## Steps to Reproduce
 1. Launch the app
2. The app is getting location, in the foreground, in the background when the device is moving or even stationary. i.e toast is showing 
3. The app is removed from the background.
    The headless task is not invoking.

## Context
We are trying to get the location and send it to backend even when app is terminated and the app is stationary.

## Debug logs
Since app is terminated, we can not produce the debug logs.

Our configuration is however:

```java
BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(getApplicationContext(), getIntent());
        final TSConfig config = TSConfig.getInstance(getApplicationContext());
 config.updateWithBuilder()
                // Configure Debugging
                .setDebug(true)
                .setLogLevel(0)
                // Configure Geolocation
                .setHeadlessJobService("com.transistorsoft.backgroundgeolocation.demo.HeadlessJobService")
                .setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
                .setDistanceFilter(2f)
                .setStopTimeout(1L)
                .setStationaryRadius(10)
                // Configure Application behaviour
                .setForegroundService(true)
                .setStopOnTerminate(false)
                .setStartOnBoot(true)
                .setDisableElasticity(true)
                .setActivityRecognitionInterval(0L)
                .setHeartbeatInterval(20)
                .setEnableHeadless(true)
                .setForceReloadOnBoot(true)
                // Configure HTTP
                .setUrl(url)
                .setParams(params)
                .setHeader("X-FOO", "FOO")  // <-- Optional HTTP headers
                .setHeader("X-BAR", "BAR")
                .commit();
```

We have a notification in notification tray to view the geolog i.e. show that a service is running in background. But when app terminated, the notification in tray also gets removed.

**Comment by christocracy** [comment]
Are you watching logcat?  See wiki “Debugging”

**Comment by christocracy** [comment]
And see http://dontkillmyapp.com

**Comment by LarsBocons** [comment]
I have been fighting similar issues with Huwai devices. It seems that some Chinese devices are more interested in battery live than having apps that actually works. 

I solved the problem by having the background geolocation plugin continuously emit sound (debug=true in config). It's a solution but not a very good one I admit. I use the "hack" in conjunction with a background-detect plugin so the sound is only on when the app is actually in the background.
