### ISSUE TITLE
iOS Native App - Framework not found

### ISSUE THREAD

**Issue by Jeyavijay** [transistorsoft/background-geolocation-lt#7]
Hi,
I have added the TSLocationManager SDK and TSBackgroundFetch SDK while building the app showing the error No framework found .
I tried by adding in the framework search paths too but the error was not solving.

Can you please help me this out.

**Comment by christocracy** [comment]
1.  Create group **Frameworks**
2.  Right-click **Frameworks**:  Add `TSLocationManager.framework`, 'TSBackgroundFetch.framework`
![](https://dl.dropboxusercontent.com/s/v3o4qmd6btd5hkz/Screenshot%202018-03-06%2014.20.56.png?dl=1)
3.  Create group "Libraries"
4.  Download [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack).  Download Zip.
![](https://dl.dropboxusercontent.com/s/4n2fn8ol9qvfkgv/Screenshot%202018-03-06%2014.22.54.png?dl=1)
5.  Unzip downloaded file.  Move to the "Libraries" folder.
6. Add `CocoaLumberjack.xcodeproj` to "Libraries" folder
![](https://dl.dropboxusercontent.com/s/rv31v9jj15fisb0/Screenshot%202018-03-06%2014.24.06.png?dl=1)
7.  **Build Phases**:  Ensure the following libraries and frameworks are added to **Link Binary With Libraries**
![](https://dl.dropboxusercontent.com/s/cj3bdkwt4mc8ksn/Screenshot%202018-03-06%2014.25.02.png?dl=1)

**Comment by Jeyavijay** [comment]
I followed these steps but  still the issue exists 
 ld: framework not found TSBackgroundFetch
Clang: error: linker command failed with exit code 1(use -v to see invocation)

Can you please help me

**Comment by Jeyavijay** [comment]
![screen shot 2018-03-07 at 5 08 15 pm](https://user-images.githubusercontent.com/13938507/37090396-38995ebc-222a-11e8-9259-e7962994d08f.png)

Hi i have imported TSBackgroundFetch , TSLocationManager and LumberJack with no error but getting these errors while initializing as an Object
 for eg: 
let manager = TSLocationManager()

Can you please help me out

**Comment by christocracy** [comment]
You don't have CocoaLumberjack linked.  Show me screenshot of **Link Binary With LIbrarires**.
![](https://dl.dropboxusercontent.com/s/3j17df4wdw71jhj/Screenshot%202018-03-07%2009.49.53.png?dl=1)

**Comment by Jeyavijay** [comment]
Oh Thankyou. Sorry for the inconvenience after adding the framework it isn't copied to the source. Thats the mistake from my side Thanks for your support.

Is there a way to alert with local push once the user started to move. Any sample resource is available or any?

**Comment by christocracy** [comment]
You're on your own for local-notifications.  Just use standard iOS api for that.

**Comment by Jeyavijay** [comment]
Can i have the source where you have used the steps of configuring the app

**Comment by christocracy** [comment]
I’ll be posting more next week.

**Comment by Jeyavijay** [comment]
Thanks :)

**Comment by bpshonyak** [comment]
Yup, I had to update the framework search paths. More specifically I had to add `$(PROJECT_DIR)/../node_modules/react-native-background-geolocation/ios` @christocracy can this be fixed so link works properly?

**Comment by christocracy** [comment]
@bpshonyak This is not the RN repo.  This is the pure native repo.
