### ISSUE TITLE
Background geolocation stops working after about 3-4 weeks

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/background-geolocation-lt#73]
## Your Environment
* Plugin version: all
* Platform: iOS
* OS version: 12.4.2
* Device manufacturer / model: iPhone 6 plus
* Plugin config
[config updateWithBlock:^(TSConfigBuilder *builder) {
            builder.debug = DEBUG_LOCATION;   // Enable debug mode for having notifications while moving in location!!!!
            builder.logLevel = tsLogLevelVerbose;
            builder.desiredAccuracy = kCLLocationAccuracyBestForNavigation;
            builder.distanceFilter = 3; // filter for mooving across area. Currently changed to 3 meters
            builder.stopOnTerminate = NO;
            builder.stationaryRadius = 1;
            builder.stopOnStationary = NO;
            builder.startOnBoot = YES;
            builder.disableElasticity = YES;
            builder.autoSync = YES;
            builder.url = urlString;
            builder.method = @"PUT";
            builder.heartbeatInterval = 900;
            builder.stopTimeout = 15;
            builder.headers = @{@"Content-Type": @"application/json; charset=utf-8",
                    @"Authorization": server.token
            };
        }];

## Expected Behavior
The app works perfectly in all time( we config it runs in background and "always" in location setting

## Actual Behavior
The app stops working on all phones after about 3 weeks, it doesn't update location anymore 

Please let me know about this issue and how to resolve it. Thanks!

**Comment by christocracy** [comment]
> Plugin version: all

This makes no sense.  **What plugin version are you using??**

**Comment by christocracy** [comment]
Please provide logs from #emailLog method from the day when “tracking stops”.

**Comment by sunilw123** [comment]
The plugin version is 3.4
Can you guide me how to get #emailLog method?

Thanks

**Comment by christocracy** [comment]
Search the [API docs](https://github.com/transistorsoft/background-geolocation-lt/blob/master/docs/README-iOS.md) for "emailLog".

**Comment by sunilw123** [comment]
Hi @christocracy ,

I send you the emailLog:

```
{
   activityRecognitionInterval = 10000;
   activityType = 1;
   authorization =    {
   };
   autoSync = 1;
   autoSyncThreshold = 0;
   batchSync = 0;
   debug = 0;
   desiredAccuracy = "-2";
   desiredOdometerAccuracy = 100;
   didLaunchInBackground = 0;
   disableAutoSyncOnCellular = 0;
   disableElasticity = 1;
   disableLocationAuthorizationAlert = 0;
   disableMotionActivityUpdates = 0;
   disableStopDetection = 0;
   distanceFilter = 3;
   elasticityMultiplier = 1;
   enableTimestampMeta = 0;
   enabled = 1;
   encrypt = 0;
   extras =    {
   };
   geofenceInitialTriggerEntry = 1;
   geofenceProximityRadius = 1000;
   geofenceTemplate = "";
   headers =    {
       Authorization = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEyNTYsImlzcyI6Imh0dHBzOi8vZGV2LnNlcmVuZGlwaXR5LmFwcC9hcGkvdXNlcnMvbG9naW4iLCJpYXQiOjE1Nzg1MzI1NDUsImV4cCI6MTU3OTc0MjE0NSwibmJmIjoxNTc4NTMyNTQ1LCJqdGkiOiJCVG1pUkd3TkgyUVlPSUYzIn0.Hy8q9e050dzQcwTa94qvBwjNO4q29CK3L4rwNyMzXm4";
       "Content-Type" = "application/json; charset=utf-8";
   };
   heartbeatInterval = 900;
   httpRootProperty = location;
   httpTimeout = 60000;
   iOSHasWarnedLocationServicesOff = 0;
   isFirstBoot = 0;
   isMoving = 0;
   lastLocationAuthorizationStatus = 3;
   locationAuthorizationAlert =    {
       cancelButton = Cancel;
       instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
       settingsButton = Settings;
       titleWhenNotEnabled = "Background location is not enabled";
       titleWhenOff = "Location services are off";
   };
   locationAuthorizationRequest = Always;
   locationTemplate = "";
   locationTimeout = 60;
   locationsOrderDirection = ASC;
   logLevel = 5;
   logMaxDays = 3;
   maxBatchSize = "-1";
   maxDaysToPersist = 1;
   maxRecordsToPersist = "-1";
   method = PUT;
   minimumActivityRecognitionConfidence = 70;
   odometer = "33851.0750270969";
   params =    {
   };
   pausesLocationUpdatesAutomatically = 0;
   persistMode = 2;
   preventSuspend = 1;
   schedule =    (
   );
   schedulerEnabled = 0;
   startOnBoot = 1;
   stationaryRadius = 25;
   stopAfterElapsedMinutes = "-1";
   stopDetectionDelay = 0;
   stopOnStationary = 0;
   stopOnTerminate = 0;
   stopTimeout = 15;
   trackingMode = 1;
   url = "http://dev.serendipity.app/api/user-location/1256";
   useSignificantChangesOnly = 0;
}
```
Hope you can debug it, please let me know if you need further information.

Thanks!

**Comment by sunilw123** [comment]
I also attach background log
[background-geolocation.log.gz](https://github.com/transistorsoft/background-geolocation-lt/files/4038342/background-geolocation.log.gz)

**Comment by christocracy** [comment]
What time intervals in the logs are of interest to you?

Are you aware your logs are full of these warnings:
```
2020-01-08 18:20:17.124 ⚠️-[HttpResponse handleResponse] HTTP ERROR: 301
***
* {"status":"success","response":{"location":{"id":"631","user_id":"1256","lat":"33.730168249489","lon":"-117.77298286568","live_address":"26, Burlingame, Lower Peters Canyon, Irvine, Orange County, California, 92602, United States of America","direction":"","speed":"0","location_captured_time":"2020-01-09 02:20:17","geohash":"9murbh27","geohash_full":"9murbh276pwp","initial_cardinal":"S","final_cardinal":"E","offset_lat":"33.730168249489","offset_lon":"-117.77298286568","offset_address":"26, Burlingame, Lower Peters Canyon, Irvine, Orange County, California, 92602, United States of America","direction_degree":"116.02","created_by":"","updated_by":"","created_at":"2020-01-09 02:20:17","updated_at":"2020-01-09 02:20:17","deleted_at":""}}}
* The operation couldn’t be completed. (TSHttpService error 1.)
*
{
    NSUnderlyingError = "301/302 redirect are disallowed";
}

```

**Comment by sunilw123** [comment]
@christocracy it's between 10pm - 11pm
 I noticed to this log, but when I call directly api via postman and don't see this issue. We are trying to debug to know why it occurs.

**Comment by christocracy** [comment]
Don't do redirects on the server.

**Comment by sunilw123** [comment]
Yes thanks, we will check the config on the server to stop it

**Comment by tinhbka** [comment]
[logfile.log](https://github.com/transistorsoft/background-geolocation-lt/files/4163595/logfile.log)
@christocracy please take a look my logs. i have same issue, location not updated
Thank you

**Comment by christocracy** [comment]
@tinhbka Your logs span the time `2020-02-05 13:19:37.164 ` to `2020-02-05 22:21:34.108`.  I see nothing wrong.
