### ISSUE TITLE
Ionic v4 cordova - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by kevob1994** [transistorsoft/background-geolocation-lt#77]
Getting a compilation problem in iOS.

The treaty reinstalling the plugins, the node_modules folder, even probe by adding the plugin https://github.com/transistorsoft/cordova-plugin-cocoalumberjack and nothing seems to work. It's always the same problem

## Your Environment
* Platform: iOS.
* OS version: macOS Catalina v10.15.2
* Plugin config

Undefined symbols for architecture x86_64:
  "_OBJC_IVAR_$_DDLogMessage._tag", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_METACLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_METACLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_CLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_CLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._message", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDAbstractLogger._logFormatter", referenced from:
      -[TSDBLogger db_log:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._saveThreshold", referenced from:
      -[TSDBLogger initWithLogDirectory:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._timestamp", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._flag", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._context", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._function", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._maxAge", referenced from:
      -[TSDBLogger getLog:] in TSLocationManager(TSDBLogger.o)
      -[TSDBLogger db_delete] in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in TSLocationManager(LocationAuthorization.o)
      objc-class-ref in TSLocationManager(TSConfig.o)
      objc-class-ref in TSLocationManager(HttpResponse.o)
      objc-class-ref in TSLocationManager(TSDBLogger.o)
      objc-class-ref in TSLocationManager(TSScheduler.o)
      objc-class-ref in TSLocationManager(RPC.o)
      objc-class-ref in TSLocationManager(TSGeofenceEvent.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
        Ld build/emulator/SmarTrace.app/SmarTrace normal x86_64
(1 failure)
Command finished with error code 65: xcodebuild -workspace,SmarTrace.xcworkspace,-scheme,SmarTrace,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/adminfs/Desktop/github/geoSmart/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/adminfs/Desktop/github/geoSmart/platforms/ios/build/sharedpch,-UseModernBuildSystem=0
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/adminfs/Desktop/github/geoSmart/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --verbose --buildFlag=-UseModernBuildSystem=0 exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 65) +73ms
## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
This is not the *Cordova* version, this is the *pure native version*.  Background Geolocation is ported to many frameworks, including *React Native* and *Flutter* as well.

Cordova version is here:
https://github.com/transistorsoft/cordova-background-geolocation-lt
