### ISSUE TITLE
IOS background: Terminated due to signal 9

### ISSUE THREAD

**Issue by nconcepts** [transistorsoft/background-geolocation-lt#79]
## Your Environment
* Plugin version: 1.2.0
* Platform: iOS
* OS version: 11.4.1
* Device manufacturer / model: Iphone X
* Plugin config
        builder.debug = NO;
        builder.logLevel = tsLogLevelOff;
        // Geolocation Config
        builder.desiredAccuracy = kCLLocationAccuracyBestForNavigation;
        builder.distanceFilter = 10;
        builder.stopTimeout = 1;
        builder.stationaryRadius = 10;
        builder.stopOnTerminate = NO;
        builder.startOnBoot = YES;

## Expected Behavior
The application should keep running continuously

## Actual Behavior
While driving in a vehicle, after an average of 20min, the application in background, the screen turned off, the application receive a SIGKILL 9 message.
Message from debugger: Terminated due to signal 9

## Context
When we are driving, we store the new location in our personal SQLITE db, no other treatment is done on it.

## Question
Does the plugin continue to store in it's DB even if we close all the logs?
What should be the best practice in background:
- Handle directly the locations when they arrive ?
- Let the plugin handle it and use it's db after wakeup ?
- Do we have to inform IOS when we finish to handle the locations in background ?

Thanks for all.
Best regards,
Yannick

**Comment by christocracy** [comment]
Show me the full stacktrace?

**Comment by nconcepts** [comment]
Last time I could see it, I had nothing in the stack, it breaks directly without warning, neither error message, just:
- Message from debugger: Terminated due to signal 9

**Comment by christocracy** [comment]
Check *XCode->Window->Devices and Simulators->Your Device*.

Or run in Simulator.

**Comment by nconcepts** [comment]
Yes, I'm working on it to try to catch it (xcode wired or wireless) but most of the time when I'm on debug mode, I don't see it, while it's frequent in normal use.

**Comment by nconcepts** [comment]
still, any advise on :
What should be the best practice in background:

Handle directly the locations when they arrive ?
Let the plugin handle it and use it's db after wakeup ?
Do we have to inform IOS when we finish to handle the locations in background ?

**Comment by christocracy** [comment]
>What should be the best practice in background:

The plugin persists every recorded location in it SQLite database.  If you provide the plugin an `url`, it will automatically upload each recorded location to your server (it's very good at this).  When your server returns HTTP 200, the plugin will delete its copy.

If you don't provide an `url`, these locations can only be deleted by executing `#destroyLocations` or when `maxDaysToPersist` expires those records, when they'll automatically be deleted.

>Do we have to inform IOS when we finish to handle the locations in background ?

The plugin does not `beginBackgroundTaskWithExpirationHandler`.  That's up to you.

**Comment by nconcepts** [comment]
Thanks for your answers.
I finally found the logs, I guess it's what you asked me from the start but I didn't know the existence of it.

It looks like a dead end recurrence...
Really strange as not so frequent, difficult to reproduce.

[IkarMobileCrash.zip](https://github.com/transistorsoft/background-geolocation-lt/files/4220852/IkarMobileCrash.zip)

**Comment by nconcepts** [comment]
Can it be an accumulation of events which release all at the same time when the app gets running in background ?

**Comment by christocracy** [comment]
>Can it be an accumulation of events which release all at the same time when the app gets running in background ?

There's nothing in your crash logs that reference the plugin's namespace `TSLocationManager`.
