### ISSUE TITLE
Question about Heartbeat on iOS

### ISSUE THREAD

**Issue by anton-sharpdev** [transistorsoft/background-geolocation-lt#80]
## Your Environment
* Plugin version: this commit: fc744eb66554afadc8c6786ab2be29a785b59b9d
* Platform: iOS
* OS version: 13
* Device manufacturer / model: doesn't matter
* Plugin config
```
builder?.logLevel = tsLogLevelInfo
builder?.desiredAccuracy = kCLLocationAccuracyBest
builder?.distanceFilter = 10;
builder?.stopOnTerminate = false;
builder?.startOnBoot = true;
builder?.heartbeatInterval = 60 * 5
builder?.preventSuspend = true
```
other fields is default

We are using heartbeat to track location every 5 min. My question is: if restart app, will the heartbeat period vanished and start timer again or not?

**Comment by anton-sharpdev** [comment]
The goal is to track location exactly every 5 min

**Comment by christocracy** [comment]
> The goal is to track location exactly every 5 min 

Impossible.

**Comment by anton-sharpdev** [comment]
And no workaround for that?

**Comment by anton-sharpdev** [comment]
if I will use `watchPostion`, will location tracked when app is killed?

**Comment by christocracy** [comment]
this Plugin is designed to track when the device is *moving*. 

When the device is stationary, it’s pointless and energy-wasting to constantly request location.

When an iOS device is completely stationary with screen off and unplugged from power, iOS throttles timer events (ie heartbeat).  

You will never get location “every 5 min” when device is completely stationary with screen off and unplugged.

**Comment by christocracy** [comment]
> And no workaround for that?

There is no “workaround” for *impossible*.

> if I will use watchPostion, will location tracked when app is killed?

No.  #watchPosition is designed for use while app is in foreground.  #watchPosition is not required by the plugin’ Philosophy of Operation.

When the device moves, the plugin tracks.  When the device becomes stationary, the plugin stops tracking.  You don’t need to waste the battery constantly requesting location while device is known to be stationary.
