### ISSUE TITLE
com.transistorsoft.locationmanager.logger.TSSQLiteAppender.append

### ISSUE THREAD

**Issue by saudagarsulaimansait** [transistorsoft/background-geolocation-lt#85]
## Your Environment
* Plugin version: 1.0.2
* Platform: Android
* OS version: API Level 27
* Device manufacturer / model: Xiaomi

## Expected Behavior
None

## Actual Behavior
App Crashed

**Comment by christocracy** [comment]
I don’t see any evidence of a crash.
