### ISSUE TITLE
We are getting two different format of logs from  Android and ios devices, we need both are same format logs

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/background-geolocation-lt#87]
## Your Environment
* Plugin version: 3.63

* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* Plugin config
cordova-background-geolocation-lt 3.6.3 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 6.0.5 "CDVBackgroundFetch"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

## Expected Behavior

Same format of logs need to be received our Url.

## Actual Behavior

IOS Logs
{
   "UserID":"5",
   "DeviceID":"69",
   "company_token":null,
   "location":[
      {
         "coords":{
            "speed":18.16,
            "longitude":-90.50300173957622,
            "floor":null,
            "latitude":38.581009598454379,
            "accuracy":5,
            "altitude_accuracy":6,
            "altitude":181.30000000000001,
            "heading":102.66
         },
         "extras":{
            "RecordType":"15"
         },
         "is_moving":true,
         "odometer":4139.1000000000004,
         "uuid":"FF36EFE4-DB6C-4E1C-A630-EDAE39B88209",
         "activity":{
            "type":"in_vehicle",
            "confidence":100
         },
         "battery":{
            "level":0.10000000149011612,
            "is_charging":false
         },
         "timestamp":"2020-05-11T15:55:34.000Z"
      }
   ],
   "CompanyID":"2"
}

Android Logs
{
   "location":[
      {
         "is_moving":true,
         "uuid":"c7ddee90-118a-4de7-8b04-7eacadec1ca9",
         "timestamp":"2020-05-11T15:55:32.000Z",
         "odometer":3462.5,
         "coords":{
            "latitude":38.5812494,
            "longitude":-90.5032971,
            "accuracy":3.9,
            "speed":18.45,
            "heading":138,
            "altitude":154
         },
         "activity":{
            "type":"still",
            "confidence":100
         },
         "battery":{
            "is_charging":true,
            "level":0.22
         },
         "extras":{
            "RecordType":"15"
         }
      }
   ],
   "company_token":null,
   "CompanyID":"2",
   "DeviceID":"65",
   "UserID":"5"
}

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Please apply *syntax highlighting* to your code.
![](https://dl.dropbox.com/s/t2yv1m3wn8e9eef/Screenshot%202020-05-11%2013.47.01.png?dl=1)
