### ISSUE TITLE
Not Receiving Correct Enter and Exit events for Geo Fences.

### ISSUE THREAD

**Issue by jsfunfun** [transistorsoft/background-geolocation-lt#88]
When going between two locations, TS Lib is not firing the correct Enter and / or Exit events.
Given two sets of geo fences, (in this example Honolulu, HI, and Mexico City, MX)... TS Lib only fires the events relative to Mexico City. No Enter or Exits are fired for Honolulu, even though the circles drawn on the sample maps are the circles fetched from TS Lib as the fences.

## Your Environment
* Plugin version: tslocationmanager-3.0.49.aar

* Platform: iOS or Android
ANDROID
* OS version:
9

* Device manufacturer / model:
Android Studio Emulator Pixel 2

* Plugin config
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <int name="trackingMode" value="0" />
    <string name="com.transistorsoft.locationmanager.adapter.TSConfig$Builder">{&quot;activityRecognitionInterval&quot;:10000,&quot;allowIdenticalLocations&quot;:false,&quot;authorization&quot;:{},&quot;autoSync&quot;:true,&quot;autoSyncThreshold&quot;:0,&quot;batchSync&quot;:false,&quot;configUrl&quot;:&quot;&quot;,&quot;debug&quot;:true,&quot;deferTime&quot;:0,&quot;desiredAccuracy&quot;:100,&quot;desiredOdometerAccuracy&quot;:100,&quot;disableAutoSyncOnCellular&quot;:false,&quot;disableElasticity&quot;:false,&quot;disableLocationAuthorizationAlert&quot;:false,&quot;disableMotionActivityUpdates&quot;:true,&quot;disableStopDetection&quot;:false,&quot;distanceFilter&quot;:10,&quot;elasticityMultiplier&quot;:1,&quot;enableHeadless&quot;:true,&quot;enableTimestampMeta&quot;:false,&quot;encrypt&quot;:false,&quot;extras&quot;:{},&quot;fastestLocationUpdateInterval&quot;:-1,&quot;forceReloadOnBoot&quot;:false,&quot;forceReloadOnGeofence&quot;:false,&quot;forceReloadOnHeartbeat&quot;:false,&quot;forceReloadOnLocationChange&quot;:false,&quot;forceReloadOnMotionChange&quot;:false,&quot;forceReloadOnSchedule&quot;:false,&quot;foregroundService&quot;:false,&quot;geofenceInitialTriggerEntry&quot;:true,&quot;geofenceModeHighAccuracy&quot;:false,&quot;geofenceProximityRadius&quot;:1000,&quot;geofenceTemplate&quot;:&quot;&quot;,&quot;headers&quot;:{},&quot;headlessJobService&quot;:&quot;com.worldaware.geosdk.WAGTSJobService&quot;,&quot;heartbeatInterval&quot;:60,&quot;httpRootProperty&quot;:&quot;location&quot;,&quot;httpTimeout&quot;:60000,&quot;isMoving&quot;:false,&quot;locationAuthorizationRequest&quot;:&quot;Always&quot;,&quot;locationTemplate&quot;:&quot;&quot;,&quot;locationTimeout&quot;:60,&quot;locationUpdateInterval&quot;:1000,&quot;locationsOrderDirection&quot;:&quot;ASC&quot;,&quot;logLevel&quot;:5,&quot;logMaxDays&quot;:3,&quot;maxBatchSize&quot;:-1,&quot;maxDaysToPersist&quot;:1,&quot;maxRecordsToPersist&quot;:-1,&quot;method&quot;:&quot;POST&quot;,&quot;minimumActivityRecognitionConfidence&quot;:75,&quot;notification&quot;:{&quot;layout&quot;:&quot;&quot;,&quot;title&quot;:&quot;&quot;,&quot;text&quot;:&quot;Location Service activated&quot;,&quot;color&quot;:&quot;&quot;,&quot;channelName&quot;:&quot;TSLocationManager&quot;,&quot;smallIcon&quot;:&quot;&quot;,&quot;largeIcon&quot;:&quot;&quot;,&quot;priority&quot;:0,&quot;strings&quot;:{},&quot;actions&quot;:[]},&quot;params&quot;:{},&quot;persist&quot;:true,&quot;persistMode&quot;:2,&quot;schedule&quot;:[],&quot;scheduleUseAlarmManager&quot;:false,&quot;speedJumpFilter&quot;:300,&quot;startOnBoot&quot;:true,&quot;stationaryRadius&quot;:25,&quot;stopAfterElapsedMinutes&quot;:0,&quot;stopOnStationary&quot;:false,&quot;stopOnTerminate&quot;:false,&quot;stopTimeout&quot;:5,&quot;triggerActivities&quot;:&quot;in_vehicle, on_bicycle, on_foot, running, walking&quot;,&quot;url&quot;:&quot;&quot;,&quot;useSignificantChangesOnly&quot;:false}</string>
    <boolean name="enabled" value="true" />
</map>

## Expected Behavior
When I navigate to Honolulu I should be Enter events. When I navigate to Mexico City, I should get Exit evens from Honolulu.

## Actual Behavior
No Enter events are fired for entering Honolulu. No exit events are fired when exiting Honolulu and entering Mexico City. As a side note, If one also goes to a 3rd location - such as Honolulu to Sydney to Mexico City, then Mexico City events stop being fired too.

## Steps to Reproduce
1. Add or Remove geofences to build a current set;
2. In emulator navigate between two locations that have the fences;

## Context
Go from one location to the next location and have correct Enter and / or Exit events fired by TS. Lib.

## Debug logs
Logs:

[CONSOLE_OUTPUT_LOG.txt](https://github.com/transistorsoft/background-geolocation-lt/files/4696203/CONSOLE_OUTPUT_LOG.txt)

### Ex-01-Our-App-With-Fence-In-Honolulu
<img width="1186" alt="Ex-01-Our-App-With-Fence-In-Honolulu" src="https://user-images.githubusercontent.com/3376550/83155301-19380e80-a0cf-11ea-833b-2440f3100a09.png">

### Ex-02-Our-App-With-Fences-In-Mexico-City
<img width="1167" alt="Ex-02-Our-App-With-Fences-In-Mexico-City" src="https://user-images.githubusercontent.com/3376550/83155314-1c32ff00-a0cf-11ea-9f1c-2a6db7041f19.png">

### Ex-03-Two-Enter-Events-For-Mexico-City
<img width="330" alt="Ex-03-Two-Enter-Events-For-Mexico-City" src="https://user-images.githubusercontent.com/3376550/83155333-1fc68600-a0cf-11ea-9e19-25920b09c435.png">

### Ex-04-Enter-Event-Details-For-Mexico-City
<img width="408" alt="Ex-04-Enter-Event-Details-For-Mexico-City" src="https://user-images.githubusercontent.com/3376550/83155336-205f1c80-a0cf-11ea-82d3-8080be1f0561.png">

### Ex-05-Navigate-Back-To-Honolulu
<img width="1180" alt="Ex-05-Navigate-Back-To-Honolulu" src="https://user-images.githubusercontent.com/3376550/83155341-21904980-a0cf-11ea-9ad5-fb0e687675a6.png">

### Ex-06-Two-Exit-Events-For-Mexico-City-Fences
<img width="322" alt="Ex-06-Two-Exit-Events-For-Mexico-City-Fences" src="https://user-images.githubusercontent.com/3376550/83155351-235a0d00-a0cf-11ea-9d7d-63796425f431.png">

### Ex-07-Exit-Event-Details-For-Mexico-City-Fence
<img width="331" alt="Ex-07-Exit-Event-Details-For-Mexico-City-Fence" src="https://user-images.githubusercontent.com/3376550/83155354-248b3a00-a0cf-11ea-97d3-9504118a6366.png">

### Ex-08-There-Were-No-Enter-Events-For-Honolulu-And-Going-Back-To-Mexico-City-We-Get-Mexico-Enter-Events
<img width="1172" alt="Ex-08-There-Were-No-Enter-Events-For-Honolulu-And-Going-Back-To-Mexico-City-We-Get-Mexico-Enter-Events" src="https://user-images.githubusercontent.com/3376550/83155355-2523d080-a0cf-11ea-9ab8-b8cba746a431.png">

### Ex-09-Mexico-City-Enter-Events
<img width="327" alt="Ex-09-Mexico-City-Enter-Events" src="https://user-images.githubusercontent.com/3376550/83155370-28b75780-a0cf-11ea-8489-1275713ea3ea.png">

**Comment by christocracy** [comment]
>Android Studio Emulator Pixel 2

Geofences events perform poorly in emulator / simulated location.  The best way to test geofences is on real device in real world field-testing.

**Comment by jsfunfun** [comment]
That has not been my experience. Maybe 5 years ago I would agree with you on emulators / simulators - but now-a-days I find them working rather consistently. Let's switch to iOS, because I find this same missing Enter/Exit events on both platforms.

On iOS, you can use the following attached iOS source code - here - [GeoNotify.zip](https://github.com/transistorsoft/background-geolocation-lt/files/4698257/GeoNotify.zip)
 to add a few fences in cities like NYC, London, Sydney, Cape Town.. You can then use the Xcode simulator and the debug location changer and you will get every single Enter and Exit event. Every time.. you can do as many times as you want. The events always come..

**Comment by jsfunfun** [comment]
Now for the real issue, could you kindly tell me how to prove that TS Lib works when going from one location to another location .. each location with more than 20 circles.. and each location being constructed with your methods addFences and removeFences... 

Here in this log 
[Logs-Part-Two-iOS-Missing-Enter-Exit-Events.txt](https://github.com/transistorsoft/background-geolocation-lt/files/4698277/Logs-Part-Two-iOS-Missing-Enter-Exit-Events.txt)

You can see - we add fences, we remove fences, and then we get some Enter / Exit events up to a certain event and then they stop. 

You can see them in these captures - New York City, 
<img width="318" alt="Ex-iOS-01-NYC-Fences-Added-To-TS-Lib" src="https://user-images.githubusercontent.com/3376550/83194000-ebba8780-a105-11ea-98ed-0c33015c0130.png">

and here is London - 
<img width="323" alt="Ex-iOS-03-Go-To-London-No-ENTER-OR-EXIT-Events" src="https://user-images.githubusercontent.com/3376550/83194051-04c33880-a106-11ea-8928-b3a2f2f9f417.png">

and you can see in these that no Enter or Exit events get fired - 
<img width="320" alt="Ex-iOS-04-No-Events" src="https://user-images.githubusercontent.com/3376550/83194100-1ad0f900-a106-11ea-91fe-c6037bf1d5c0.png">

Why do they not get fired?

As I said, it works for a short while, from London to NYC ... from NYC to London ... London to NYC ... but then most often once I go to Sydney and go back to London or NYC - i get nothing. No events.

Kindly tell me how it can be proven that TS Lib works when changing locations. How can it be proven that TS Lib "loads the new closest 20 fences" .. because what I see happening is that TS Lib "unloads" (or in my logs "STOPPED monitoring" ... after going to Sydney) .. 

These are the STARTED and STOPPED monitoring - from your callback.
<img width="763" alt="Ex-iOS-05-I-NEVER-SEE-FENCES-ADDED-AFTER-GOING-TO-A-NON-TRACKED-LOCATION-SUCH-AS-SYDNEY" src="https://user-images.githubusercontent.com/3376550/83194723-16591000-a107-11ea-94fc-eca31b540153.png">


I never see TS Lib ever reload any fences for NYC or London again. How can it be proven that this is working in TS Lib? 

Thank you.

**Comment by christocracy** [comment]
This is an unnatural way to test, dramatically teleporting around the earth like that.  I suggest you create a set of geofences along the *Freeway Drive* route in the iOS Simulator.

These seem like unnaturally large geofence radius, as well.

**Comment by jsfunfun** [comment]
The fence radii are very large - agreed - but those are not within my control - it just happens to be the data given.. The use case is more common for our end customer than one might think. Their use case is very often dealing with travel. So, leaving London on an airplane (and turning their phones to Airplane mode), and arriving in NYC is a fairly common use for them. Think about it if you would .. I know we are digging deep into the nitty gritty of TS Lib for the proof here, sorry, but we need to be able to verify somehow that this is working as they expect.

**Comment by christocracy** [comment]
- make sure geofenceProximityRadius is greater than the largest geofence radius.
- the plugin has a limiter to prevent unnecessary geospatial queries in a short amount of time.  Teleporting around the world within a few seconds is not going to reload geofences in that new zone.
- After teleporting, I would add a test button on your UI to execute getCurrentPosition.  Pressing that button a few times after teleporting should get the plugin to re-execute it’s geospatial query.  #stop/#start would do it too.

**Comment by jsfunfun** [comment]
I'll give those a try.. Thank you... I'll get back in the next days about the results.

**Comment by christocracy** [comment]
Whenever I fly, I always place a geofence at my destination airport with my demo apps.  They fire.

**Comment by jsfunfun** [comment]
ok great to know. Thank you Chris.
