### ISSUE TITLE
Issue on Geofence Tracking in Android Background mode when the App is terminated completely

### ISSUE THREAD

**Issue by SowmiyaMadesh** [transistorsoft/background-geolocation-lt#9]
I have defined Geofence and methods to track after terminating the App. But I'm getting Toast Message saying " License Validation Failure...". I'm running in debug mode only. I'm not able to create any Local Notification to check Geofence Tracking after the App being terminated. 
Please look into these Log Files.
[Issue on Geofence Tracking in Android Background mode.txt](https://github.com/transistorsoft/background-geolocation-lt/files/1810779/Issue.on.Geofence.Tracking.in.Android.Background.mode.txt)
![screenshot_20180314-070927](https://user-images.githubusercontent.com/36696724/37399423-a91e5566-27a7-11e8-9467-21262c0a8fce.jpg)

Thanks

**Comment by christocracy** [comment]
When you terminate an app, your *entire* Javascript app is terminated.  If you're hoping to use Javascript callbacks to send a local notification that's not going to work.

You could use the plugin's [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) to perform this.

**Comment by christocracy** [comment]
Oh, sorry.  Thought this was the Cordova version.  In that case, you'll need to do a little extra setup.

I need to add some docs on how to receive "headless" tasks for native android version.

**Comment by SowmiyaMadesh** [comment]
Could you update document on Headless Task for Native Android and please let me know

Thanks

**Comment by SowmiyaMadesh** [comment]
Hi, Can you please update document on Headless Task, Services and Defining in Manifest? Do I need to add Application ID for debug mode also?

Thanks.

**Comment by SowmiyaMadesh** [comment]
Hi, is there any updation on Background Service in Native Android?

**Comment by SowmiyaMadesh** [comment]
Hi, Is there any updation on Background Service in Native Android?
