### ISSUE TITLE
NullPointerException while trying to send Location Logs from Android app

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/background-geolocation-lt#95]
## Your Environment
* Plugin version: 3.7.1
* Platform: iOS or Android  : Android
* OS version: 9.0 (Android Pie)
* Device manufacturer / model: RedMi Note 7, Redmi Note 5 Pro, Vivo z1x, Nokia 7.1 
* Plugin config: 
config.updateWithBuilder()
.setDebug(true).setIsMoving(true)
.setLogLevel(5)
.setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
.setDistanceFilter(150F).
setElasticityMultiplier(5F)
.setStopOnTerminate(false)
.setStationaryRadius(1)
.setStopOnStationary(false)
.setStartOnBoot(true)
.setDisableElasticity(true)
.setAutoSync(true)
.setUrl(getRequestUrl())
.setMethod("PUT")
.setHeartbeatInterval(900)
.setStopTimeout(15L).setForegroundService(true)
.setHeaders(getHeaders())
.commit();

## Expected Behavior
-> It should create a .gz file which contains the location logs of TSLocationManager library to be sent over email or share with other users. 

## Actual Behavior
-> As soon as user clicks on "Send Location Logs" in our app, the app is getting crashed. 

## Steps to Reproduce
We are using following code snippet (function) in order to create the Email intent to send location log file (.gz), which should be generated by the plugin. 
BackgroundGeolocation.getInstance(this, getIntent()).emailLog("email to whom send", this, new TSEmailLogCallback() {
                       @Override
                     public void onSuccess() {
                        Log.e("BackgroundGeolocation", "onSuccess");
                       }

                  @Override
                     public void onFailure(String s) {
                        Log.e("BackgroundGeolocation", "onFailure");
                 }
              });

## Context
=> We are trying to send location log data through email. We tried to wrap the code with try..catch statement as well. But it even does not go into the "onFailure" event of this library function. 

## Debug logs
Herewith attaching "TSLocationManger_Crash.txt" file for complete crash log. 
[TSLocationManger_Crash.txt](https://github.com/transistorsoft/background-geolocation-lt/files/4855962/TSLocationManger_Crash.txt)

Moreover, after upgrading the library to the latest version, when our app opens, it shows the Toast message with the error "Invalid license key". Currently our Android app is being used with Debug mode. So will it affect the location update functionality of the plugin? 
Invalid license key: 8f06390d3b1987591a347d9249153652531d27ba3a457b1773313ea7014e41b0
    ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.

Please let me know if any other details are needed for this. 

Thanks

**Comment by christocracy** [comment]
Oops.  I've deprecated `BackgroundGeolocation.emailLog` in favour of a new API.  The old API shouldn't produce an NPE and will be fixed in next release.

```java
SQLQuery query = new SQLQuery();

TSLog.emailLog(activity, email, query, new TSEmailLogCallback() {
        @Override public void onSuccess() {
            success.invoke();
        }
        @Override public void onFailure(String error) {
            failure.invoke(error);
        }
    });
```

**Comment by sunilw123** [comment]
Ok so an immediate fix would be to purchase the plugin right now then, correct?

**Comment by christocracy** [comment]
>NullPointerException while trying to send Location Logs from Android ap

No, the immediate fix for your issue is written in my post above.

**Comment by sunilw123** [comment]
Ok thanks. I keep trying to login to the customer portal to generate a key and it keeps saying Unauthorized.  Not sure what to do.  I connected my github to this account.
<img width="1792" alt="Screen Shot 2020-07-01 at 7 12 27 AM" src="https://user-images.githubusercontent.com/35516853/86254295-76a9fa00-bb6a-11ea-8ac6-d09034956aaf.png">

**Comment by christocracy** [comment]
If you've purchased a license, what is your Order#?

**Comment by christocracy** [comment]
>NullPointerException while trying to send Location Logs from Android app

Issue threads are **not** your own personal support thread for everything you want.  Please keep your questions on topic.

**Comment by sunilw123** [comment]
It was order# 2717.  I am trying to just get a key we can use while in development then purchase again after it works.    I did get an email stating my old devs probably tied this to their old github and not mine.  Maybe that is why it's not working. Not sure.

**Comment by christocracy** [comment]
I need an email from the License owner authorizing a change in admin for this account.

**Comment by sunilw123** [comment]
Chris I am the license owner, I paid for this on my credit card.  And my name is on the account. They just tied their github account for that employee (who was fired after he couldn't get this done as you may recall from conversations years ago) to this but the credit card and order was all me.  So I am the owner.  And the email I placed the order from is swagle@serendipityawaits.com which is my email account. I will send you an email from that account to you.

**Comment by christocracy** [comment]
I need **an email from the same email address that originally ordered the product** for proof.

**Comment by sunilw123** [comment]
Ok sure. Just sent it.
