### ISSUE TITLE
performStopDetection found mStoppedAtLocation == null

### ISSUE THREAD

**Issue by knyshdmitry** [transistorsoft/background-geolocation-lt#96]
## Your Environment
* Plugin version:
3.1.7 (363)
* Platform: iOS or Android
Android
* OS version: 7.1.1 (native)
* Device manufacturer / model: ZTE BLADE A0620
* Plugin config
TE v @ 7.1.1 (native)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": 100,
  "desiredOdometerAccuracy": 10,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": false,
  "distanceFilter": 0,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "enableTimestampMeta": false,
  "encrypt": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {
    "Authorization-gis": "-------------"
  },
  "headlessJobService": "",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 60000,
  "locationsOrderDirection": "ASC",
  "logLevel": 4,
  "logMaxDays": 60,
  "maxBatchSize": -1,
  "maxDaysToPersist": -1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "GPS enabled",
    "color": "",
    "channelName": "GPS",
    "smallIcon": "drawable\/ic_logo_big",
    "largeIcon": "drawable\/ic_location",
    "priority": 0,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [
    "2 07:00-20:00",
    "3 07:00-20:00",
    "4 07:00-20:00",
    "5 07:00-20:00",
    "6 07:00-20:00",
    "7 07:00-20:00"
  ],
  "scheduleUseAlarmManager": true,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": -1,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 1,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/geo-v2.zegoal.com\/locations\/zegoal",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": true,
  "trackingMode": 1,
  "odometer": 0,
  "isFirstBoot": false,
  "didLaunchInBackground": false
}

## Expected Behavior
Hi Chris, We have 2 equal devices: ZTE Blade with our app powered by your plugin. We expect that they both will collect and send locations to our server according to schedule 

## Actual Behavior
 The first device starts getting locations and send it to our server according to schedule. The second device start getting locations and after 5-10 minutes it stops to update locations data. In log file we see error "performStopDetection found mStoppedAtLocation == null". It can be fixed by turned off and turned on "location" in phone settings. Then after 5-10 minutes, it stops again. We thought that it's a local phone problem but when we install our older app with other location plugin it begins to work and send locations without any stops. Then we find some other phones with the same error with your plugin (Huawei Y6PRO, ZTE BLADE

## Steps to Reproduce

1. Open app with plugin. Schedule must be on. Locations data will update and send to a server.
2. Wait 5-10 minutes
3. Result location does not update. 
4.

## Debug logs
 
[no error log 1st device.txt](https://github.com/transistorsoft/background-geolocation-lt/files/4970970/no.error.log.1st.device.txt)
[error log 2nd device.txt](https://github.com/transistorsoft/background-geolocation-lt/files/4970971/error.log.2nd.device.txt)

**Comment by christocracy** [comment]
Are you doing actual field-testing or using mocked locations?

**Comment by knyshdmitry** [comment]
It's a production one. All this data from our current customers' devices and it's all real not mocked.

**Comment by christocracy** [comment]
>The second device start getting locations and after 5-10 minutes it stops to update locations data

See http://dontkillmyapp.com.  Huawei are the worst devices on earth for background-services.

**Comment by knyshdmitry** [comment]
Chris, both devices are ZTE Blade. In one device we have a perfect picture in the other (equal brand, model, OS version) we have a problem. When we found this error we try to find other cases among our clients' devices. So it was not Huawei device only but ZTE and some other too. Meanwhile, these devices work with other gps app without any errors. Do you have any things about how to solve it?

**Comment by knyshdmitry** [comment]
Hi. Any news about this issue?
I got today these devices from my client. We have installed your flutter app from play market and did the same setting (like in our app except set pace >true). App got locations for 5 minutes and then stoped to do it. Please find config bellow. Log attached. As I caught sight of when you open the app screen it finds one location and then "falls asleep".  One more thing. When we integrate your plugin into our app we had test on these devices. All worked well. After app release, we did one plugin update and got this situation. 
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.1.8 (364)
╠═════════════════════════════════════════════
╟─ ZTE ZTE BLADE A0620 @ 7.1.1 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {
    "strategy": "jwt",
    "accessToken": "eyJhb<redacted>",
    "refreshToken": "b6e55<redacted>",
    "refreshUrl": "http:\/\/tracker.transistorsoft.com\/api\/refresh_token",
    "refreshPayload": {
      "refresh_token": "{refreshToken}"
    },
    "expires": -1
  },
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": -2,
  "desiredOdometerAccuracy": 10,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": true,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "encrypt": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": 60,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 60000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": -1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": -1,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 1,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/tracker.transistorsoft.com\/api\/locations",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 0,
  "isFirstBoot": true,
  "didLaunchInBackground": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="BMI160 Accelerometer", vendor="BOSCH", version=2062500, type=1, maxRange=39.22661, resolution=0.0023956299, power=0.18, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="BMI160 Gyroscope", vendor="BOSCH", version=2062500, type=4, maxRange=17.453293, resolution=0.0010681152, power=0.9, minDelay=5000}
╟─ ⚠️  MAGNETOMETER:  none.  Motion-detection system performance will be degraded
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.17999268, minDelay=-1}
╚═════════════════════════════════════════════ 
[background-geolocation-12.log](https://github.com/transistorsoft/background-geolocation-lt/files/4995814/background-geolocation-12.log)

**Comment by christocracy** [comment]
I test the SampleApp almost every day on the following devices, I do not experience any issues.  See http://dontkillmyapp.com

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 11
- Google Pixel 3a @ 10
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by knyshdmitry** [comment]
Ok. Let us start from another side. What means this error "performStopDetection found mStoppedAtLocation == null"? I need to solve this issue for my client. He has 300 such devices.

**Comment by knyshdmitry** [comment]
Dear @christocracy , We have been chosen your plugin to empower our main app, but we have a huge problem with using your service. Today we got a notification from our customer that they'll stop our contract if we'll not fix the problem with background geolocation service. It's 1500 users! We are losing money and our business reputation! Please learn our problem as much deeper as you can.  For this moment we have the same issues as I wrote before. Your plugin stops to catch location after some time (see attachment 
[Zegoal Pro Xiaomi Redmi 4X 24-25 Aug PSD.txt](https://github.com/transistorsoft/background-geolocation-lt/files/5142978/Zegoal.Pro.Xiaomi.Redmi.4X.24-25.Aug.PSD.txt)
[Zegoal Light ZTE BLADE A452 28 Aug.txt](https://github.com/transistorsoft/background-geolocation-lt/files/5142989/Zegoal.Light.ZTE.BLADE.A452.28.Aug.txt)
[Zegoal light Huawei Y6PRO 27Aug .txt](https://github.com/transistorsoft/background-geolocation-lt/files/5142993/Zegoal.light.Huawei.Y6PRO.27Aug.txt)
It begins to work when you reload the service but after some time (depends on device from 10 min to couple hours) it begins to lose locations. Meantime it shows us status that plugin works. 

 . It also does not start to get location by schedule. See attachment. 
[Zegoal Light Samsung SM-G318H 20-21Aug.txt]
[Zegoal Light Samsung SM-G318H Pim 24-25Aug .txt](https://github.com/transistorsoft/background-geolocation-lt/files/5143009/Zegoal.Light.Samsung.SM-G318H.Pim.24-25Aug.txt)
[Zegoal Light Demo new user Xiaomi Redmi 8A) 28 Aug.txt.zip](https://github.com/transistorsoft/background-geolocation-lt/files/5143015/Zegoal.Light.Demo.new.user.Xiaomi.Redmi.8A.28.Aug.txt.zip)
[Zegoal Pro (DEMO D.K) Xiaomi REdmi 8A PSD 28 Aug.txt](https://github.com/transistorsoft/background-geolocation-lt/files/5143018/Zegoal.Pro.DEMO.D.K.Xiaomi.REdmi.8A.PSD.28.Aug.txt)





And also we have "detect performStopDetection found mStoppedAtLocation == null error". Please help us to solve these problems. We still have a chance to save our contract. Thanks in advance.

**Comment by christocracy** [comment]
see http://dontkillmyapp.com

**Comment by christocracy** [comment]
>mStoppedAtLocation == null error

It's not an error, it's a *warning*.

**Comment by christocracy** [comment]
>ZTE ZTE BLADE A0620 @ 7.1.1 (flutter)

Btw, your'e not posting to the correct repo.  This is the *pure native* repo, not the *flutter* repo.

**Comment by knyshdmitry** [comment]
I've learn http://dontkillmyapp.com from A to Z. There is nothing there that can help me. I have a gps service which we made by ourself. It works with all these devices without such problems but it doesn't have activity recognition mode. I thought that your service better than ours... So as I understood you do not know how to solve it?

**Comment by knyshdmitry** [comment]
> > ZTE ZTE BLADE A0620 @ 7.1.1 (flutter)
> 
> Btw, your'e not posting to the correct repo. This is the _pure native_ repo, not the _flutter_ repo.

Btw It's yours sample app which I try to use to find error. We are using native app. All logs attached in my last message.

**Comment by christocracy** [comment]
It's not a code problem, it's a problem with your device manufacturers violating the Android API, as documented at http://dontkillmyapp.com

It's a well known issue, and the Android Engineering Team *is* [aware of the problem](https://www.reddit.com/r/androiddev/comments/hk3hrq/were_on_the_android_engineering_team_ask_us/fxg9y4f/) and due to make changes in Android 11 to help prevent Android manufacturers from violating the Android API.
