### ISSUE TITLE
Question about heading only from GPS

### ISSUE THREAD

**Issue by bgervan** [transistorsoft/background-geolocation-lt#99]
## Your Environment
iOS and Android native apps

## Expected Behavior
The heading comes from Sensor too, for increased frequency (like 0.1 sec)

## Actual Behavior
The heading comes from the GPS only

There are cases when it is not enough, if the required frequency is higher than 1 sec. Most of the GNSS sensors are capable of 1 per sec location update or worse, in case of iOS.

Is it planned or possible?

**Comment by christocracy** [comment]
>Is it planned or possible?

It's not currently planned.
